### ISSUE TITLE
Support netstandard/netcoreapp

### ISSUE THREAD

**Issue by altso** [Sicos1977/MSGReader#100]
Please consider supporting net standard and/or net core. According to net portability analyzer, it's ~91% compatible already. Please see the reports attached.
[ApiPortAnalysis_Itenso.Rtf.Converter.Html.xlsx](https://github.com/Sicos1977/MSGReader/files/1875980/ApiPortAnalysis_Itenso.Rtf.Converter.Html.xlsx)
[ApiPortAnalysis_Itenso.Rtf.Parser.xlsx](https://github.com/Sicos1977/MSGReader/files/1875981/ApiPortAnalysis_Itenso.Rtf.Parser.xlsx)
[ApiPortAnalysis_Itenso.Sys.xlsx](https://github.com/Sicos1977/MSGReader/files/1875982/ApiPortAnalysis_Itenso.Sys.xlsx)
[ApiPortAnalysis_MsgReader.xlsx](https://github.com/Sicos1977/MSGReader/files/1875983/ApiPortAnalysis_MsgReader.xlsx)

**Comment by Sicos1977** [comment]
I added it on my todo list ... but it can take some time before I get to it :-)

**Comment by Sicos1977** [comment]
To let you know that there is some progress, see commit 2d4fd5d879e8b8dbb9b7492fa09c34177af2611c

**Comment by XplittR** [comment]
Based on the filenames, a quick google suggests it is from the microsoft-tool [dotnet-apiport](https://github.com/Microsoft/dotnet-apiport).

**Comment by altso** [comment]
Correct, the reports were generated with dotnet-apiport.

**Comment by altso** [comment]
Also, I can help with the migration if you can split the whole process into smaller pieces.

**Comment by Sicos1977** [comment]
I first need to finish the migration to OpenMCDF (what is almost done) ... after that I'm going to start the migration to .NET Core.

**Comment by altso** [comment]
@Sicos1977 Do you have a migration plan or any ideas of how to make it compatible with netstandard/netcore? If so, I might help you with that.

**Comment by Sicos1977** [comment]
I could need all the help you can give, at the moment I just have to little spare time to do some coding. Sorry that it is taking longer then expected.

**Comment by altso** [comment]
I tried to compile the latest version from git but it fails with errors in `MsgReader.Outlook.Message.Send()` related to `NativeMethods` and `memoryStorage`. I guess the work on the migration to OpenMCDF is still in progress.

Please correct me if I wrong, but it looks like everything in `Itenso.*` namespace is related to RTF to HTML conversion. If so, would it make sense to use a 3rd party library for that (e.g. [RtfPipe](https://github.com/erdomke/RtfPipe) - most likely based on the same code base)? It would simplify the migration process, as you no longer need to migrate `Converter` project that heavily relies on `System.Web` assembly which is not part of .NET Standard for the most part.

Also, what's your expectations on the supported platforms? .NET Standard 2.0 introduces tons of .NET Framework compatible APIs, but only supported by .NET 4.6.1 and higher (see compatibility matrix here https://docs.microsoft.com/en-us/dotnet/standard/net-standard). As of now, `MsgReader` project targets .NET 4.5.

I have more thoughts/comments, but most of them depend on the answers to questions below.

**Comment by Sicos1977** [comment]
Hi,

The code should compile now. At the moment I just commented away the code that is giving the compile error. I'll try to fix that code as soon as possible. I also replaced the Intenso.* dll's with the RftPipe nuget package and that seems to be working without any problems. However I still left the "old" code in my GitHub repository just to be sure everything keeps working that way.  

I also upgraded the project to target .NET 4.6.1.

Greetings,
Kees van Spelde

**Comment by altso** [comment]
Wow, that was quick. I think the next step would be to resolve dependencies on `System.Drawing` and `System.Cryptography`. I'll take a deeper look by the end of this week.

**Comment by Sicos1977** [comment]
We probably can replace `System.Cryptography` with BouncyCastle .. see --> http://www.bouncycastle.org/csharp/ It supports .NET core

**Comment by altso** [comment]
https://www.nuget.org/packages/BouncyCastle/ does not support .net standard. Are you looking at a different one?

**Comment by altso** [comment]
https://www.nuget.org/packages/System.Drawing.Common/ might help with `System.Drawing`.

**Comment by altso** [comment]
I see you are actively working on netstandard support in a branch. I sent a PR to resolve some of the compilation errors.

**Comment by altso** [comment]
Also, please take a look at https://www.nuget.org/packages/System.Security.Cryptography.Pkcs/. I was able to compile MsgReaderCore with that lib.

**Comment by Sicos1977** [comment]
I wonder if this is everything that needs to be done... because this was easy to port :-)

**Comment by altso** [comment]
Ha. That's great news. Nice job.

I sent another [Pull Request](https://github.com/Sicos1977/MSGReader/pull/110) that changes target framework from `netcoreapp2.0` to `netstandard2.0` so the same library can be consumed from both .NET Core and .NET Framework.

Also, I changed all references from `MsgReader` to `MsgReaderCore` and updated the test project. One of the RTF to HTML tests fails - you might want to look at this. Could be related to `RtfPipe`.

OpenMCDF for .NET Standard is also work in progress (see https://github.com/ironfede/openmcdf/issues/19). The compiler gives me a warning as of now:

```
Warning	NU1701	Package 'OpenMcdf 2.1.6.28924' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	MsgReaderCore
```

**Comment by altso** [comment]
It appears there are 2 usages of `DllImport`. I do not know if it works on non-windows platforms, so it might be something to look into.

https://github.com/Sicos1977/MSGReader/blob/234d7f2833296632ecba4c17ede3ecabd13e6445/MsgReaderCore/Rtf/Util.cs#L38

https://github.com/Sicos1977/MSGReader/blob/234d7f2833296632ecba4c17ede3ecabd13e6445/MsgReaderCore/Helpers/FileIcon.cs#L143

**Comment by michaelp** [comment]
pull request for .net standard support for openMCDF is submitted

**Comment by altso** [comment]
@Sicos1977 I've spent some time looking at failing `Rtf_Content_Test` test and it looks like something is wrong with the encoding. I saved rtf string to a file and tried to open it with different applications. Word and WordPad could not recognize unicode? symbols properly.


I tempted to file a bug in RtfPipe, but now I think something is off in MsgReader. If you have any clues, I would be happy to take a deeper look.

[RtfSample.rtf.txt](https://github.com/Sicos1977/MSGReader/files/2207450/RtfSample.rtf.txt) (please remove trailing .txt extension before opening - GitHub does not allow uploading .rtf files)

![image](https://user-images.githubusercontent.com/1263018/42909105-f354335a-8ab0-11e8-9310-1b644aded3ff.png)


Here is the original exception:

```
Test method MsgReaderTests.BasicContentTests.Rtf_Content_Test threw exception: 
System.ArgumentException: '', hexadecimal value 0x1C, is an invalid character.
    at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at RtfPipe.Converter.Html.RtfHtmlConverter.DoVisitText(IRtfVisualText visualText)
   at RtfPipe.Converter.Html.RtfHtmlConverter.RenderRtfContent()
   at RtfPipe.Converter.Html.RtfHtmlConverter.RenderBodySection()
   at RtfPipe.Converter.Html.RtfHtmlConverter.RenderHtmlSection()
   at RtfPipe.Converter.Html.RtfHtmlConverter.Convert(XmlWriter writer)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlWriterSettings settings)
   at MsgReader.Outlook.RtfToHtmlConverter.ConvertRtfToHtml(String rtf)
```

Note, the test succeeds if I sanitize rtf text like that:
```csharp
Encoding encoding = Encoding.ASCII;
byte[] bytes = encoding.GetBytes(rtf);
rtf = encoding.GetString(bytes);
```

**Comment by Sicos1977** [comment]
Thanks for finding this out, I'll try to look into this this evening (morning now here in the Netherlands)

**Comment by Sicos1977** [comment]
I used your solution to fix the problem. I checked the RTF that came out of the test msg file and somehow there are some unicode chars in there. They are in the original message.

The RTF specification says the following:

A standard RTF file can consist of only 7-bit ASCII characters, but can encode characters beyond ASCII by escape sequences.[28] The character escapes are of two types: code page escapes and, starting with RTF 1.5, Unicode escapes. In a code page escape, two hexadecimal digits following a backslash and typewriter apostrophe are used for denoting a character taken from a Windows code page. For example, if the code page is set to Windows-1256, the sequence \'c8 will encode the Arabic letter bāʼ (ب). 

So it should not be a problem sanitizing the file.

**Comment by altso** [comment]
@Sicos1977 This is great. Thanks for the details. It seems to me the only missing item right now is netstandard version of OpenMCDF. Do you have anything else in mind?

**Comment by Sicos1977** [comment]
Nope... I want to wait for the OpenMCDF netstandard version and when it's there release a new MSGReader version.

**Comment by Sicos1977** [comment]
I just published MSGReader v3.1 on NuGet

**Comment by altso** [comment]
Great! Thank you.

**Comment by Sicos1977** [comment]
Your welcome and thanks for all the help
