### ISSUE TITLE
indirect dependency on the assembly Itenso.Rtf.Interpreter

### ISSUE THREAD

**Issue by RBoydo** [Sicos1977/MSGReader#101]
Hi there,
Not an issue as such unless this dependence should be listed but...
Got the following error after installing in VS using nuGet package manager.

> Severity	Code	Description	Project	File	Line	Suppression State
> Warning		The primary reference "Itenso.Rtf.Converter.Html, Version=1.7.0.0, Culture=neutral, PublicKeyToken=d7f23b760ed5c748, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Itenso.Rtf.Interpreter, Version=1.7.0.0, Culture=neutral, PublicKeyToken=d7f23b760ed5c748" which was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".	MaxtonSalesEmailer

Tried to find Itenso.Rtf to install/getdll but no luck. any pointers?

Thanks,
Richard

**Comment by Sicos1977** [comment]
Hi,

I checked the latest NuGet pack but the mentioned assembly is in there. Are you trying to use MSGReader from a C# .NET 4.0 ? project?

**Comment by Sicos1977** [comment]
A wait... I already see the problem... I forgot to upgrade the dependencies in the NuGet package itself.

**Comment by RBoydo** [comment]
Thanks 👍
