### ISSUE TITLE
Email address is not properly coming out in case of X500 format.

### ISSUE THREAD

**Issue by perumalsamya** [Sicos1977/MSGReader#102]
Hi, 
When I try to extract the email address information from the outlook file, it gives me in different different formats.  I parse the contact documents which are in ".MSG" format and also normal email documents.

When I try to read the sender information, it gives me in the below format
/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=1C8D8C873F4E474CA016BC809D293EFA-example@domain.com

  If it always gives me like above at least i can parse and remove unwanted characters and extract the email id as "example@domain.com" but in some cases it gives me in the below format
/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=1C8D8C873F4E474CA016BC809D293EFA-example1
Difference is domain name is not coming. 

Could you please let me know what is wrong here? I attached the sample "msg" document here below
[SampleFiles.zip](https://github.com/Sicos1977/MSGReader/files/1993942/SampleFiles.zip)

**Comment by Sicos1977** [comment]
Seems to be a bug, I'll try to look into it this weekend.

**Comment by perumalsamya** [comment]
Thanks... let me know if it is fixed

**Comment by TonyValenti** [comment]
I'm dealing with this same issue.  Any thoughts on a fix?

**Comment by Sicos1977** [comment]
Tony,

Can you also sent me the e-mail that is giving you the error? Please sent it to sicos2002@hotmail.com

**Comment by TonyValenti** [comment]
Here's a sample email with the issue.

[🏊 Tony_ come on in_ the points are great!.zip](https://github.com/Sicos1977/MSGReader/files/2238312/Tony_.come.on.in_.the.points.are.great.zip)

**Comment by Sicos1977** [comment]
I check your test e-mail and it seems to be working fine over here. Can you try to latest source on GitHub and if it still is not working reopen this issue?

![image](https://user-images.githubusercontent.com/6692947/43667674-4ca617aa-9779-11e8-9178-3f51c8fd2331.png)

**Comment by TonyValenti** [comment]
Thanks!  Could you publish an update to Nuget?  I use nuget and not the
GitHub sources.  Thanks!

Tony Valenti

Schedule a meeting with me <https://Fasterlaw.com/schedule-meeting>
