### ISSUE TITLE
IPM.DistList msg file is not supported

### ISSUE THREAD

**Issue by someusersomeuser** [Sicos1977/MSGReader#104]
This is sample
[test_distribution_list.zip](https://github.com/Sicos1977/MSGReader/files/2063676/test_distribution_list.zip)

**Comment by Sicos1977** [comment]
If possible then please send me the file that is giving this error so that I can support this kind of file type.

Please send it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
I check the file but this has almost nothing to do with an MSG (e-mail) file. For this reason I won't add support and am closing this issue.

**Comment by someusersomeuser** [comment]
> I check the file but this has almost nothing to do with an MSG (e-mail) file. For this reason I won't add support and am closing this issue.

![sicos1](https://user-images.githubusercontent.com/36192774/54282582-5e951c80-45ad-11e9-87b4-78b8452e5f11.png)

![sicos2](https://user-images.githubusercontent.com/36192774/54282594-66ed5780-45ad-11e9-885a-d3fe8bcd60c7.png)
