### ISSUE TITLE
How to resolve "Duplicate font id" problem?

### ISSUE THREAD

**Issue by long1000** [Sicos1977/MSGReader#106]
Hi,
I created a simple rich text email using MS Outlook 2013.
When I tried to run ExtractToFolder, it gave me the exception "Duplicate font id".
How can I resolve this?
Thanks in advance.

**Comment by Sicos1977** [comment]
Can you send me the msg file that is giving you this error? Please send it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Closed due to no response

**Comment by long1000** [comment]
Sorry, I just emailed u today. I miss out the notification email.
