### ISSUE TITLE
Odd HTML encoding in HtmlBody in place of <br>, emoji

### ISSUE THREAD

**Issue by palmsey** [Sicos1977/MSGReader#108]
I have an email with the party popper emoji in it (🎉 which should be `&#127881;` when HTML encoded, 
[see fiddle](https://dotnetfiddle.net/ijjXux)) but it's showing up in HtmlBody as `&#-10180;&#-8311;`.

I noticed in another message several instances of `&#-257;` where there should be a `<br>`. 

In both cases, I compared the HTML output from MsgReader with the HTML from Outlook's view source.

I haven't seen negative HTML encoded entities like that before.

Attaching the email with the emoji: 

- [Introducing Hundreds Of Trello Sample Boards.zip](https://github.com/Sicos1977/MSGReader/files/2138222/Introducing.Hundreds.Of.Trello.Sample.Boards.zip)

**Comment by Sicos1977** [comment]
I confirmed that it is a bug. I think that I use an integer somewhere that is overflowing. Have to figure out where... I'll let you know when I find something

**Comment by Sicos1977** [comment]
Can you check if the latest commit (33338cff0a62c346ebef0d85dd1d412b10a5258a) fixes your problem. I added support to parse 16 bits unicode rtf tokens.

![image](https://user-images.githubusercontent.com/6692947/43536815-dceca09e-95bd-11e8-9ce0-0b85d756368d.png)

**Comment by palmsey** [comment]
I'm having trouble verifying this - I still get the encoded entity instead of the emoji, but maybe I'm not doing something right. I'll check again with the next release.

Thank you!

**Comment by Sicos1977** [comment]
Did you use the source code from GitHub?

**Comment by palmsey** [comment]
Yes - I cloned this repository and built it, then replaced my NuGet references with direct references to the locally compiled version. I had to add references to OpenMCDF and System.Drawing.Common, which seemed like a good indication that it was really using the updated code.

Your screenshot looks good, but when I tested this in my application with the same msg file I still got the overflowed encoded entity.

**Comment by Sicos1977** [comment]
At the moment I'm upgrading my Visual Studio Enterprise 2017 with the latest patch but after that is finished I'll retry your e-mail to see if all my changes are committed to GitHub

**Comment by palmsey** [comment]
Thanks, I didn't notice MSGViewer. It looks good in there, not sure what the problem is in my app.

Also, I noticed the arrow character (→) in that message doesn't seem to display correctly. Here it is in Outlook:

![image](https://user-images.githubusercontent.com/198051/43651870-33ccc672-9709-11e8-9a1f-bca2f6ee1526.png)

And in MSGViewer:

![image](https://user-images.githubusercontent.com/198051/43651885-3c5294c0-9709-11e8-8110-7b39cdfe46cd.png)

I'm guessing this is a different issue since it doesn't look like it's trying to encode it, but thought I'd mention it.

**Comment by Sicos1977** [comment]
What app are you using to view the HTML output?

**Comment by palmsey** [comment]
It's displaying in the browser (Chrome in my testing). I'm using MSGReader in a website. I do some other transformations to the markup, but nothing that should change encoding (or produce that overflowed value).

**Comment by Sicos1977** [comment]
I just check what outlook does when I convert the MSG file to HTML. That one uses the HTML code you mentioned. What I produce is different but done the way the RTF 1.9.1 specs says it need to be done. So I'm now trying to figure out if I missed something

**Comment by Sicos1977** [comment]
I got everything working now (even in FireFox and Google Chrome). It took me forever to figure out how Microsoft inserts UTF-16 chars into an RTF file (due to the lack of good documentation). See this commit for more details 8b9d23534990b84b9e08581011f0961e877f5a68 . Please try it out and let me know if it also works for you. If so then I'll release a new NuGet package.

![image](https://user-images.githubusercontent.com/6692947/43666334-b87114d6-9773-11e8-8ccf-cbe9f623e29c.png)

**Comment by palmsey** [comment]
Works for me, thanks!

**Comment by Sicos1977** [comment]
I just released MSGReader v3.2 on NuGet
