### ISSUE TITLE
Text after bullets disappears

### ISSUE THREAD

**Issue by cjames9001** [Sicos1977/MSGReader#119]
It looks like the fix to [117](https://github.com/Sicos1977/MSGReader/issues/117) may have caused issues on other emails and making some text after bullets disappear.

Here's an example:
From outlook:
![capture](https://user-images.githubusercontent.com/11615850/43671733-188811b2-9765-11e8-8f12-c4d842792a90.PNG)
With the new changes:
![capture2](https://user-images.githubusercontent.com/11615850/43671734-2033aaf2-9765-11e8-92c5-6472ff6f79f8.PNG)

I've just sent you the example email.

**Comment by Sicos1977** [comment]
Thanks, I'll look into it this evening (morning now over here).

**Comment by Sicos1977** [comment]
It should be fixed now.

![image](https://user-images.githubusercontent.com/6692947/43679381-6f1b5ed4-9824-11e8-82a2-1051eae59201.png)

![image](https://user-images.githubusercontent.com/6692947/43679394-7fcf3f52-9824-11e8-98bd-e41d34fbab31.png)

**Comment by cjames9001** [comment]
Great! I’ll check it out tomorrow. Thanks!

**Comment by cjames9001** [comment]
Looks great, I did a few regression tests with an email set I've been using to test the functionality and everything looks as I'd expect. Thanks again!

**Comment by Sicos1977** [comment]
I just released MSGReader v3.2 on NuGet
