### ISSUE TITLE
License URL is still using CPOL

### ISSUE THREAD

**Issue by odee2004** [Sicos1977/MSGReader#125]
Hi,

When I install your package in my project, the License URL is still pointed to CPOL. Also, in your license.txt file it is CPOL instead of MIT.

![image](https://user-images.githubusercontent.com/6821225/45577959-f783ee80-b83b-11e8-817c-294a98e4f32d.png)

I know this is nothing major, but just pointing out. 

Thanks!
Rod

**Comment by Sicos1977** [comment]
Thanks... I'll fix it in a next version.
