### ISSUE TITLE
Support custom message class

### ISSUE THREAD

**Issue by Wenjie-Liang** [Sicos1977/MSGReader#126]
Currently, Reader.ExtractToFolder throws for unknown MessageType. People uses custom Message Class for some messages, although the message is filled as a regular email message.

It would be great if a callback can be provided to allow the caller to resolve the message class to proper MessageType. Or allow a default MessageType input, which can be used to replace the "unknown" message type.

**Comment by Sicos1977** [comment]
I'll try to look into it this weekend
