### ISSUE TITLE
Values of Unknown Headers

### ISSUE THREAD

**Issue by bjsadev** [Sicos1977/MSGReader#127]
Hi,
I really need to access the values of Unknown Header keys, not just the name of the keys. Anyway to do this (or to get the full raw header) in the existing code, or could you add this?

**Comment by Sicos1977** [comment]
I'll try to look into it this weekend

**Comment by Sicos1977** [comment]
You can get the value from the UnknownHeader namevalue collection like this.

var value = message.Headers.UnknownHeaders["Thread-Index"];
