### ISSUE TITLE
Handle multiple occurences of the same header

### ISSUE THREAD

**Issue by alessaro92** [Sicos1977/MSGReader#128]
When loading a mail message from an eml file which contains more than one occurence of the "To" header, the "To" headers list of the MessageHeader class gets populated only with the value, or values in case of a comma separated address list, contained in the last of these header occurrences.

To reproduce the issue you have to load a message which has at least two lines of the "To" header like this example:
To: first.recipient@email.com
To: second.recipient@email.com

I really don't know what the expected behaviour should be because according to the specs described here http://tools.ietf.org/html/rfc5322#section-3.6.3 you have to separate recipients' addresses by inserting a comma when listing all of them in the same "To" header. Maybe reality differs from theory. Also, I don't know if this case is related only to the "To" header or there are any other headers that are written in different ways.

I would probably handle this issue by replacing the To property assignment with an AddRange call in the ParseHeader method of the MessageHeader class.

**Comment by Sicos1977** [comment]
There should only be one TO field in an EML e-mail header

**Comment by Sicos1977** [comment]
I added support to handle multiple To's. Please get the latest source from GitHub and see if that fixes your problem. You can see the changes in this commit --> 6208442042cefb5c5a26901d7a29fecae91dee95
