### ISSUE TITLE
Add request for Read Receipt and/or Delivery Receipt

### ISSUE THREAD

**Issue by jdroes** [Sicos1977/MSGReader#129]
This is not really a bug. However, I cannot figure out how to set a request for read receipt or delivery receipt when creating a draft. I was hoping it would be as simple as changing the priority of the message but I could not find any properties like that.

If there is a way of requesting a read receipt or delivery receipt when creating a draft, please let me know what it is. Otherwise, this is a feature request.

I am using C# to generate a .MSG draft file so we can open it in Outlook, review the message and attachments, and send it using Outlook.

**Desktop (please complete the following information):**
 - Windows 7 32-bit

James Roes

**Comment by Sicos1977** [comment]
At the moment it is not possible, I have to add the MAPI properties that make this possible.

**Comment by Sicos1977** [comment]
I see that I directed you to the wrong project so I closed the issue here and made a new one in the correct place :-) ... you can find your issue overhere --> https://github.com/Sicos1977/MsgKit/issues/40
