### ISSUE TITLE
COM error when attempting to view unsent msg file in MsgViewer

### ISSUE THREAD

**Issue by johnefuture** [Sicos1977/MSGReader#13]

**Comment by Sicos1977** [comment]
Can you send me a screenshot from the error and if possible the msg file itself? Please send it to sicos2002@hotmail.com

Please zip the msg file. Hotmail otherwise converts it to EML.

Greetings,
Kees van Spelde

**Comment by johnefuture** [comment]
Hi



This is the error and I have attached the msg file that caused it. Hope
that helps





John



*From:* Kees [mailto:notifications@github.com]
*Sent:* 13 January 2015 17:30
*To:* Sicos1977/MSGReader
*Cc:* johnefuture
*Subject:* Re: [MSGReader] COM error when attempting to view unsent msg
file in MsgViewer (#13)



Can you send me a screenshot from the error and if possible the msg file
itself? Please send it to sicos2002@hotmail.com

Please zip the msg file. Hotmail otherwise converts it to EML.

Greetings,
Kees van Spelde

—
Reply to this email directly or view it on GitHub
<https://github.com/Sicos1977/MSGReader/issues/13#issuecomment-69783547>.

**Comment by Sicos1977** [comment]
Hi,

I did not receive an E-mail.. are you sure you did send it to sicos2002@hotmail.com?

**Comment by johnefuture** [comment]
Sorry will re-send when back in work tomorrow morning

John

**Comment by Sicos1977** [comment]
Hi,

I tested your MSG file but that just works fine over here.
What version are you using? And on what kind of system are you... windows 7?

Greetings,
Kees van Spelde
![capture](https://cloud.githubusercontent.com/assets/6692947/5741265/5aae6320-9c0a-11e4-84d4-23d4247d4737.PNG)

**Comment by johnefuture** [comment]
Hi



I compiled the latest code from github in VS 2013 update 4, which gives me
v1.8.3 as in your image below. I am running on Windows 7 SP1 64bit. The msg
file was created in Outlook 2007. I have tried both the debug and release
builds.



John



*From:* Kees [mailto:notifications@github.com]
*Sent:* 14 January 2015 15:28
*To:* Sicos1977/MSGReader
*Cc:* johnefuture
*Subject:* Re: [MSGReader] COM error when attempting to view unsent msg
file in MsgViewer (#13)



Hi,

I tested your MSG file but that just works fine over here.
What version are you using? And on what kind of system are you... windows 7?

Greetings,
Kees van Spelde
[image: capture]
<https://cloud.githubusercontent.com/assets/6692947/5741265/5aae6320-9c0a-11e4-84d4-23d4247d4737.PNG>

—
Reply to this email directly or view it on GitHub
<https://github.com/Sicos1977/MSGReader/issues/13#issuecomment-69932741>.

**Comment by Sicos1977** [comment]
Uhm.. that should be ok. I’m also using VS2013 (Ultimate) with update 4.

I’m on a windows 8.1 system but that should not make any difference. I use the same code on my work on a windows 2003, 2008 and 2012 server and it works without problems.

 

On my work laptop I also have Windows 7 64 bits without local admin rights and it even works there.

 

Can you step through the code and see where it fails? The error indicates that it is losing a reference to the COM IPersistant interface

 

Greetings,

Kees van Spelde

 

Van: johnefuture [mailto:notifications@github.com] 
Verzonden: woensdag 14 januari 2015 17:12
Aan: Sicos1977/MSGReader
CC: Kees
Onderwerp: Re: [MSGReader] COM error when attempting to view unsent msg file in MsgViewer (#13)

 

Hi 



I compiled the latest code from github in VS 2013 update 4, which gives me 
v1.8.3 as in your image below. I am running on Windows 7 SP1 64bit. The msg 
file was created in Outlook 2007. I have tried both the debug and release 
builds. 



John 



*From:* Kees [ <mailto:notifications@github.com> mailto:notifications@github.com] 
*Sent:* 14 January 2015 15:28 
*To:* Sicos1977/MSGReader 
*Cc:* johnefuture 
*Subject:* Re: [MSGReader] COM error when attempting to view unsent msg 
file in MsgViewer (#13) 



Hi, 

I tested your MSG file but that just works fine over here. 
What version are you using? And on what kind of system are you... windows 7? 

Greetings, 
Kees van Spelde 
[image: capture] 
< <https://cloud.githubusercontent.com/assets/6692947/5741265/5aae6320-9c0a-11e4-84d4-23d4247d4737.PNG> https://cloud.githubusercontent.com/assets/6692947/5741265/5aae6320-9c0a-11e4-84d4-23d4247d4737.PNG> 

— 
Reply to this email directly or view it on GitHub 
< <https://github.com/Sicos1977/MSGReader/issues/13#issuecomment-69932741> https://github.com/Sicos1977/MSGReader/issues/13#issuecomment-69932741>.

**Comment by johnefuture** [comment]
Hi

I have recompiled on my home PC and Everything was fine. Just tried the executable on my work PC and it works fine here! I think it must be some sort of problem with my setup so I think you can close this issue now. Sorry for the inconvenience.

John
