### ISSUE TITLE
RtfPipe dependency not working for .net 4x project because it's not signed

### ISSUE THREAD

**Issue by SaphuA** [Sicos1977/MSGReader#130]
When using your library in a .net 4x project and trying to parse an rtf file it will throw an exception:
`Could not load file or assembly 'RtfPipe'...`

This is most likely due to MsgReader being signed, while RtfPipe is not.

The same exception is also thrown in your own WinForms test application MsgViewer when opening an rtf file.

There is a signed version of RtfPipe on NuGet, but it was created by someone else and not updated regularly.

**Comment by Sicos1977** [comment]
This commit should fix that error 473f18e95586d49a4416a13d6cbc826070432e49
