### ISSUE TITLE
Wrong value provided to CultureInfo constructor

### ISSUE THREAD

**Issue by SaphuA** [Sicos1977/MSGReader#131]
I think this is incorrect, but don't know what it's supposed to be.  On this line the wrong value is provided to the `CultureInfo` constructor. The value of `LanguageConsts.DataFormatWithTime` is F which is not a valid culture.

https://github.com/Sicos1977/MSGReader/blob/9b0b2dafa37326c4e0ebee16c777868bf0faee23/MsgReaderCore/Reader.cs#L833

**Comment by Sicos1977** [comment]
Thanks... that was a bug... fixed now.
