### ISSUE TITLE
ExtractMsgEmailBody does not include attachments even though docs say so

### ISSUE THREAD

**Issue by SaphuA** [Sicos1977/MSGReader#132]
When calling `Reader.ExtractMsgEmailBody` with `withHeaderTable=true` I am expecting a list of attachments to be included, because the docs say so here:

https://github.com/Sicos1977/MSGReader/blob/9b0b2dafa37326c4e0ebee16c777868bf0faee23/MsgReaderCore/Reader.cs#L340

And here:
https://github.com/Sicos1977/MSGReader/blob/9b0b2dafa37326c4e0ebee16c777868bf0faee23/MsgReaderCore/Reader.cs#L363

It would be easy to add this functionality by changing this:
https://github.com/Sicos1977/MSGReader/blob/9b0b2dafa37326c4e0ebee16c777868bf0faee23/MsgReaderCore/Reader.cs#L372

To this:

    var attachments = message?.Attachments?.OfType<Storage.Attachment>().Select(c => c.FileName).ToList();
    var emailHeader = ExtractMsgEmailHeader(message, htmlBody, hyperlinks, attachments);

Or would you rather have another boolean argument added? Either way I wouldn't mind making a pull request for this.

**Comment by Sicos1977** [comment]
Thanks... also fixed now
