### ISSUE TITLE
Question: which MSG format versions are supported?

### ISSUE THREAD

**Issue by SkyCrawl** [Sicos1977/MSGReader#133]
Hello everyone,

many thanks for this great-looking project. If it's alright to take up some of your time, I'd like to ask which [MSG format versions](https://msdn.microsoft.com/en-us/library/cc463912.aspx) are supported, or perhaps more generally, when a new version comes out or is adopted by a Microsoft product, how much initiative there is to bring support for it here?

My specific situation mandates support for, at least, Outlook 2010/2013/2016/2019 + Office 365.

Kind regards,
Jiri

**Comment by Sicos1977** [comment]
It should parse all MSG versions. There really isn't a big difference between Outlook 2010 up until Office 365.
