### ISSUE TITLE
RtfPipe.dll is missing from nuget

### ISSUE THREAD

**Issue by bartkusters** [Sicos1977/MSGReader#134]
RtfPipe.dll is missing from the nuget

1. Install nuget
2. Check build project
3. Check output
4. See that RtfPipe.dll is missing

**Comment by Sicos1977** [comment]
Weird... I'm certain that I included it in the packages? Are you using the latest package version?

**Comment by bartkusters** [comment]
Yes I am, tested it this morning with version 3.4.0.
Also opened the .nupkg to check the content, and I do not see any RtfPipe.dll

**Comment by Sicos1977** [comment]
I published a new package 3.4.1 to NuGet ... it has the missing rtfpipe.dll.

Thanks for mentioning it to me.

**Comment by bartkusters** [comment]
Awesome, thanks for your quick support.

**Comment by Sicos1977** [comment]
Just a question... because of your GitHub name... are you dutch?

**Comment by bartkusters** [comment]
Yes I am :-)

**Comment by Sicos1977** [comment]
Dat vermoeden had ik al :-)
