### ISSUE TITLE
Is there any ConversationTopic property?

### ISSUE THREAD

**Issue by mvpkenlin** [Sicos1977/MSGReader#138]
If I look into Microsoft.Exchange.WebServices.Data.EmailMessage, I can find a property called  ConversationTopic. 

I think, if we only collect the email subject, it might contains "RE:" or "FWD:" for email in English. But it will be in other char for email in other languages. And I can see there will be a need for the "ConversationTopic", which is removing the "RE:" and "FWD:". Is it possible to create this property?

**Comment by mvpkenlin** [comment]
I found that one of the InternetMessageHeaders has this value, Name: Thread-Topic

**Comment by Sicos1977** [comment]
Yes there is

![image](https://user-images.githubusercontent.com/6692947/51125612-4f9a2400-1821-11e9-908c-9291fc966769.png)
