### ISSUE TITLE
NullReference in ReferenceManager on program exit

### ISSUE THREAD

**Issue by AvaletDev** [Sicos1977/MSGReader#14]
I created a console app that loops through a directory with msg files. Every msg is analyzed and some data is extracted. It all works fine except when a msg file is opened. Of course it throws an exception and used a try/catch to catch the exception. 

This all works fine until the program is done executing. When I place breakpoints at the end of the main() function, it executes everything as it should, but after that it throws a null reference exception:

>An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.dll
>Additional information: Object reference not set to an instance of an object.
>
`mscorlib.dll!System.Runtime.InteropServices.Marshal.ReleaseComObject(object o)
 MsgReader.dll!MsgReader.Outlook.Storage.ReferenceManager.Finalize()`

**Comment by AvaletDev** [comment]
I downloaded the code and compiled it local with the following changes:
In Storage.cs line 189
````C#
if (storage == null)
    throw new Exception("Can not add empty object");
````

**Comment by Sicos1977** [comment]
Hi, 

Do you know why a null object is added? Is this because of a corrupt MSG file or something else?

Greetings,
Kees van Spelde

P.S. Ik ben ook Nederlander

**Comment by AvaletDev** [comment]
It is because the msg was used by another process.
--
Ah gezellig:)

**Comment by Sicos1977** [comment]
Merged
