### ISSUE TITLE
Error while reading eml file

### ISSUE THREAD

**Issue by JKennedy24** [Sicos1977/MSGReader#140]
**Describe the bug**
When trying to read an eml file I get the following error:

> Invalid OLE structured storage file
>    at OpenMcdf.Header.CheckSignature()
>    at OpenMcdf.Header.Read(Stream stream)
>    at OpenMcdf.CompoundFile.Load(Stream stream)
>    at OpenMcdf.CompoundFile.LoadFile(String fileName)
>    at OpenMcdf.CompoundFile..ctor(String fileName)
>    at MsgReader.Outlook.Storage..ctor(String storageFilePath, FileAccess fileAccess)
>    at MsgReader.Outlook.Storage.Message..ctor(String msgfile, FileAccess fileAccess)

I am reading the eml file like so:

```
        private static Email CreateEmail(string fullPath)
        {
            using (var msg = new MsgReader.Outlook.Storage.Message(fullPath))
            {
                var email = new Email();
                foreach (var recipient in msg.Recipients)
                {
                    email.ToEmailAddresses.Add(recipient.Email);
                }
                email.Subject = msg.Subject;
                email.BodyText = msg.BodyText;
                email.BodyHtml = msg.BodyHtml;
                return email;
            }
        }
```

I have also attached the eml file I am trying to read.

I am running on UWP in a .net standard 2.0 library (but I'm not sure that should affect it)

Any idea what this error means? Is my code wrong for trying to read eml files?

[confirmation.zip](https://github.com/Sicos1977/MSGReader/files/2744597/confirmation.zip)

**Comment by JKennedy24** [comment]
My Bad. I worked out how to read in an eml file. It may be worth having something like this on the front page:

```
        private static Email CreateEmail(string fullPath)
        {
            FileInfo fi = new FileInfo(fullPath);
            var msg = MsgReader.Mime.Message.Load(fi);
            var email = new Email();

            if (msg.Headers != null)
            {
                if (msg.Headers.To != null)
                {
                    foreach (var recipient in msg.Headers.To)
                    {
                        email.ToEmailAddresses.Add(recipient.Address);
                    }
                }

                email.Subject = msg.Headers.Subject;
            }

            if (msg.TextBody != null)
            {
                string body = System.Text.Encoding.UTF8.GetString(msg.TextBody.Body);
                email.BodyText = body;
            }
            if (msg.HtmlBody != null)
            {
                string body = System.Text.Encoding.UTF8.GetString(msg.TextBody.Body);
                email.BodyHtml = body;
            }

            return email;
        }
```

Where 'email' is my own class in this case

**Comment by Sicos1977** [comment]
Good point, I will add it to the frontpage.

Why are you creating a new Email object?

**Comment by JKennedy24** [comment]
@Sicos1977 Mainly just to decode the byte arrays into string properties to make it easier to use else where in my app.

Im open to suggestions if you think there's a neater way

**Comment by JKennedy24** [comment]
I don't mind. Feel free to use it

**Comment by Sicos1977** [comment]
Are you using msgreader just to read eml files or also for MSG files?

In case you want only to read eml files then MimeKit (https://github.com/jstedfast/MimeKit) is a better option to use. The only reason why I also support eml is because I needed it to decode secured msg files.
