### ISSUE TITLE
No data is available for Encoding 4024

### ISSUE THREAD

**Issue by mvpkenlin** [Sicos1977/MSGReader#141]
After passing the steam data to MsgReader.OutlookStorage.Message constructor, and got the following error when accessing BodyHtml,

"System.NotSupportedException: No data is available for encoding 4024"

I will send you the sample msg file for testing in email.

**Desktop (please complete the following information):**
 - OS: Win10
 - Language: C# 4.7.2

![body_notsupportedexception](https://user-images.githubusercontent.com/20411183/51099310-f1624680-180a-11e9-9a6e-9958c1adaff1.png)
![body_notsupportedexception_4024](https://user-images.githubusercontent.com/20411183/51099315-f58e6400-180a-11e9-9cdd-b220a83bb876.png)

**Comment by Sicos1977** [comment]
I'll try to look into it this evening

**Comment by Sicos1977** [comment]
Fixed with commit bf36e121cb61b30a198006c92d11c9629b110e73
