### ISSUE TITLE
Value of IsInline in attachment is not getting correctly

### ISSUE THREAD

**Issue by mvpkenlin** [Sicos1977/MSGReader#142]
I have one email, with 2 inline images, both of them I expected MsgReader should return me IsInline property to true. But it returns false and I found out that the Contentdescription and ContentDisposition is also null in this case. 

Sample email I will send to you in email. Please check your inbox. 

![incorrectinlinevalue](https://user-images.githubusercontent.com/20411183/51099545-52d6e500-180c-11e9-9159-b1ceef9e4414.png)

**Comment by Sicos1977** [comment]
I think I made a check somewhere that look into the html file if the content id exists and if missing it then decided the attachment is not inline.

**Comment by Sicos1977** [comment]
This commit fixes your issue cc5ca386e67533a81f0d8d59ce7d4f4166c5f3d4

**Comment by Sicos1977** [comment]
I just released a new version, you can find it overhere https://www.nuget.org/packages/MSGReader/3.5.0

**Comment by RaulBastian** [comment]
Hi, I'm using version 3.6.1, I'm also getting the behaviour as mentioned by @mvpkenlin. I have an email with an inline attachment but the Inline property returns false:

![image](https://user-images.githubusercontent.com/9720946/56563117-31c02600-65ab-11e9-8e5a-357d6b54d066.png)

Could I use a rendering position to determine if it's inline?  If > -1 then Inline ....

**Comment by Sicos1977** [comment]
Can you send me the e-mail that is giving this problem? You can send it to sicos2002@hotmail.com

**Comment by RaulBastian** [comment]
Hi, thanks, here’s a solution with a sample email which has an inline attachment but the Inline property returns false.

Let me know if you need anything else.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by RaulBastian** [comment]
Hi, I saw this post which might help in detecting when an attachment is inline:

![image](https://user-images.githubusercontent.com/9720946/56802383-29bcec00-6820-11e9-90ec-3398c3bfba32.png)


https://social.technet.microsoft.com/Forums/exchange/en-US/542f0c0c-4de3-4752-9390-db33b8e45bca/external-email-attachments-always-seen-as-inline-attachments-with-exchange-2010?forum=exchange2010

**Comment by RaulBastian** [comment]
Here it explains what the ATTACH_FLAG is:

PDF files:
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcmsg/7fd7ec40-deec-4c06-9493-1bc06b349682

Document: [MS-OXCMSG].pdf

Point: 2.2.2.18 PidTagAttachFlags Property

**Comment by Sicos1977** [comment]
> Here it explains what the ATTACH_FLAG is:

PDF files:
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcmsg/7fd7ec40-deec-4c06-9493-1bc06b349682

Document: [MS-OXCMSG].pdf

Point: 2.2.2.18 PidTagAttachFlags Property

**Comment by Sicos1977** [comment]
Yes you can use the rendering position, but then is only used when the body is in RTF format
