### ISSUE TITLE
Issue with RTFPipe

### ISSUE THREAD

**Issue by DarrinEdwards** [Sicos1977/MSGReader#145]
Hi Guys,

There appears to be an issue with RTFPipe - an exception is being thrown 

> Exception thrown: 'System.IO.FileLoadException' in MsgReader.dll
An exception of type 'System.IO.FileLoadException' occurred in MsgReader.dll but was not handled in user code
Could not load file or assembly 'RtfPipe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=317a45ec926873fc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Any suggestions how we can resolve this - I have cleared the lacked and downloaded the last version and not found the error to resolve -

Many thanks in advance

Regards

Darrin

**Comment by mvpkenlin** [comment]
I found Release 3.5.0 and 3.6.0 are not having the dll, probably the same happen as #134

**Comment by Sicos1977** [comment]
I'll rebuild the nuget package this evening.

**Comment by Sicos1977** [comment]
MsgReader 3.6.1 has just been published. It contains the missing RTFPipe assembly

https://www.nuget.org/packages/MsgReader/

**Comment by DarrinEdwards** [comment]
thank you 👍
