### ISSUE TITLE
Latin characters not parsing correctly.

### ISSUE THREAD

**Issue by Mahanstein** [Sicos1977/MSGReader#146]
My .msg has special characters like ç, ã, ó and they are not parsing correctly to html.
Textbody and Rtfbody are ok.

**Comment by Sicos1977** [comment]
Can you send me the message that is giving you this problem? You can send it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
No response... closed

**Comment by Sicos1977** [comment]
Fixed in this commit 3b01dda6f3c77780f09eda936637ee8fb29d656d
