### ISSUE TITLE
Question/Suggestion - Can MSG be decrypted?

### ISSUE THREAD

**Issue by darbid** [Sicos1977/MSGReader#147]
First I have just stumbled upon your project, I was unaware this existed. It looks great, thank you for open sourcing the project here.

**Describe the Question**
My understanding of encrypted emails are that the MSG contains 1 attachment which is in fact the email (2nd email) as a file just encrypted.  Thus my question / s are is this your understanding? Do you think it is possible to decrypt the attachment and extract it as an MSG file?

**To Reproduce**
Steps to reproduce the Question: using the CryptoAPI (WinAPI) decrypt the attached SMIME.P7M file and extract the attachment as an MSG.

**Desktop (please complete the following information):**
 - OS: Windows 10

Have you ever thought of adding this to your code?

**Comment by Sicos1977** [comment]
There is already support for this in MSGReader

https://github.com/Sicos1977/MSGReader/blob/ca6a3ba795f838145876b75000a353a2a2f1393a/MsgReaderCore/Outlook/Message.cs

Search for SMIME.P7M on that page.

**Comment by darbid** [comment]
Yes I see hints of this.  However the LoadSignedMessage method the code currently errors after trying to call SignedCms.Decond(attachment.Data)

The exception I have put into an image.
<img width="1419" alt="cryptoerror" src="https://user-images.githubusercontent.com/3191525/53086899-467a3200-3506-11e9-967e-1fdd85f16fa3.PNG">

**Comment by Sicos1977** [comment]
The error indicates that the encrypted message is not valid. Can you open the file in Outlook?

You also don't have to use the GetErrorMessage method, that is only there if you call ExtractToFolderFromCom

**Comment by darbid** [comment]
Yes the msg can be opened in Outlook.  The expectation is to get a prompt similar to this dialog

<img width="395" alt="smartcarddialog" src="https://user-images.githubusercontent.com/3191525/53088829-3284ff00-350b-11e9-88ac-3e92ade344d8.PNG">
[Test Encrypted.zip](https://github.com/Sicos1977/MSGReader/files/2884424/Test.Encrypted.zip)
I have added the MSG in the zip file.  I am not sure how far you will get as it is encrypted but I can give you info on the attachment if you need it.

**Comment by darbid** [comment]
Here is how to encrypt/decrypt using a smart card. 

[Encrypting/Decrypting using DigitalCertificates using C#](https://blog.aggregatedintelligence.com/2010/02/encryptingdecrypting-using.html)

In case the link dies

`using System;
using System.IO;
using System.Text;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace X509Certificate2_Encryption_Example
{
    class X509Certificate2_Cryptographer
    {
        //creating the certificate
        //makecert -r -pe -n "CN=WWW.AGGREGATEDINTELLIGENCE.COM" -b 01/01/2005 -e 01/01/2020 -sky exchange -ss my
        public static void Main()
        {
            try
            {
                X509Certificate2 x509_2 = LoadCertificate(StoreLocation.CurrentUser, "CN=WWW.AGGREGATEDINTELLIGENCE.COM");
                //DisplayX509CertificateInfo(x509_2);
                
                string plaintext = "HelloWorld";
                Console.WriteLine("Plain text: " + plaintext + Environment.NewLine);
                
                string encryptedstring = Encrypt(x509_2, plaintext);
                Console.WriteLine("Encrypted text: " + Environment.NewLine + encryptedstring + Environment.NewLine);
                
                string decryptedstring = Decrypt(x509_2, encryptedstring);
                Console.WriteLine("decrypted text: " + decryptedstring + Environment.NewLine);                
            }
            catch (Exception e)
            {
                Console.WriteLine("Error: {0}", e.Message);
            }
            Console.ReadLine();
        }
        
        public static X509Certificate2 LoadCertificate(StoreLocation storeLocation, string certificateName )
        {
            X509Store store = new X509Store(storeLocation);
            store.Open(OpenFlags.ReadOnly);
            X509Certificate2Collection certCollection = store.Certificates;
            X509Certificate2 x509 = null;
            foreach (X509Certificate2 c in certCollection)
            {
                if (c.Subject == certificateName)
                {
                    x509 = c;
                    break;
                }
            }
            if (x509 == null)
                Console.WriteLine("A x509 certificate for " + certificateName + " was not found");
            store.Close();
            return x509;
        }
        
        public static void DisplayX509CertificateInfo(X509Certificate2 x509)
        {
            if (x509 == null)
                throw new Exception("A x509 certificate must be provided");
                
            Console.WriteLine("{0}Subject: {1}{0}", Environment.NewLine,x509.Subject);
            Console.WriteLine("{0}Issuer: {1}{0}", Environment.NewLine,x509.Issuer);
            Console.WriteLine("{0}Version: {1}{0}", Environment.NewLine,x509.Version);
            Console.WriteLine("{0}Valid Date: {1}{0}", Environment.NewLine,x509.NotBefore);
            Console.WriteLine("{0}Expiry Date: {1}{0}", Environment.NewLine,x509.NotAfter);
            Console.WriteLine("{0}Thumbprint: {1}{0}", Environment.NewLine,x509.Thumbprint);
            Console.WriteLine("{0}Serial Number: {1}{0}", Environment.NewLine,x509.SerialNumber);
            Console.WriteLine("{0}Friendly Name: {1}{0}",Environment.NewLine,x509.PublicKey.Oid.FriendlyName);
            Console.WriteLine("{0}Public Key Format: {1}{0}",Environment.NewLine,x509.PublicKey.EncodedKeyValue.Format(true));
            Console.WriteLine("{0}Raw Data Length: {1}{0}", Environment.NewLine,x509.RawData.Length);
            Console.WriteLine("{0}Certificate to string: {1}{0}", Environment.NewLine,x509.ToString(true));

            Console.WriteLine("{0}Certificate to XML String: {1}{0}",Environment.NewLine,x509.PublicKey.Key.ToXmlString(false));
        }
        
        public static string Encrypt(X509Certificate2 x509, string stringToEncrypt)
        {
            if (x509 == null || string.IsNullOrEmpty(stringToEncrypt))
                throw new Exception("A x509 certificate and string for encryption must be provided");
                
            RSACryptoServiceProvider rsa = (RSACryptoServiceProvider)x509.PublicKey.Key;
            byte[] bytestoEncrypt = ASCIIEncoding.ASCII.GetBytes(stringToEncrypt);
            byte[] encryptedBytes = rsa.Encrypt(bytestoEncrypt, false);
            return Convert.ToBase64String(encryptedBytes);
        }
        
        public static string Decrypt(X509Certificate2 x509, string stringTodecrypt)
        {
            if (x509 == null || string.IsNullOrEmpty(stringTodecrypt))
                throw new Exception("A x509 certificate and string for decryption must be provided");
                
            if (!x509.HasPrivateKey)
                throw new Exception("x509 certicate does not contain a private key for decryption");
                
            RSACryptoServiceProvider rsa = (RSACryptoServiceProvider)x509.PrivateKey;
            byte[] bytestodecrypt = Convert.FromBase64String(stringTodecrypt);
            byte[] plainbytes = rsa.Decrypt(bytestodecrypt, false);
            System.Text.ASCIIEncoding enc = new System.Text.ASCIIEncoding();
            return enc.GetString(plainbytes);
        }
    }
}`




Note the call to Decrypt on the RSACryptoServiceProvider automatically loads the above dialog - Assuming that the right certificate is choosen.

**Comment by darbid** [comment]
I have played around with it a little bit. In ProcessSignedContent

1. you need to call LoadCertificate from the above code. User need to choose the appropriate store. I have 5 stored on my card I think it is the only one that is currently valid but I suppose it might be an older one.

2. Additional code needed looks like this

`X509Certificate2 x509_2 = LoadCertificate(StoreLocation.CurrentUser, "");
                    EnvelopedCms envDate = new EnvelopedCms(new ContentInfo(data));
                    CmsRecipient Recip = new CmsRecipient(SubjectIdentifierType.IssuerAndSerialNumber, x509_2);
                    X509Certificate2Collection col = new X509Certificate2Collection(x509_2);
                    envDate.Decode(data);
                    envDate.Decrypt(col);
                   decData = envDate.ContentInfo.Content;`

I then passed it into
// Get the decoded attachment
                using (var memoryStream = new MemoryStream(decData))

One thing that I have noticed is later on at ExtractMsgEmailHeader

 WriteHeaderLineNoEncoding(emailHeader, htmlBody, maxLength, LanguageConsts.EmailSignedBy, signerInfo);

for me the signerInfo is null which is not expected in this method.

**Comment by Sicos1977** [comment]
I'll try to look in to this this weekend. At the moment I'm a little bit busy with something else.

**Comment by darbid** [comment]
I thought I would help with this a little more.  Something like this works for me and might be what you are looking for, for this project.

```
byte[] decData = null;
EnvelopedCms envDate = new EnvelopedCms(new ContentInfo(data));
envDate.Decode(data);
// no need to guess which certificate just throw them all at the EnvelopedCms
X509Store store = new X509Store(StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
X509Certificate2Collection certCollection = store.Certificates;
//The user will be prompted to enter a pin or password if their privatekey is protected. Need to handle an error here for that and also if they dont have a certificate 
envDate.Decrypt(certCollection);
decData = envDate.ContentInfo.Content;
store.Close();
store.Dispose();
```

**Comment by Kroch7** [comment]
Question regarding this issue: Is there a solution in sight?
I have the same problems darbid faced and also tried the version he posted earlier in this thread. But decryption isn't working for me - can you maybe help? I have a SMIME encrypted mail sent to me and can't see the email body of it.

**Comment by Sicos1977** [comment]
Can you send me the message? If so then please send it to sicos2002@hotmail.com . Please zip it before sending.

**Comment by Sicos1977** [comment]
No response... closed

**Comment by darbid** [comment]
I’m assuming you are wanting another example from Kroch7 as I gave you an example on Feb 20 above

**Comment by Kroch7** [comment]
> Can you send me the message? If so then please send it to sicos2002@hotmail.com . Please zip it before sending.

Sorry for the last response, was on vacation.
Send you an example.
