### ISSUE TITLE
Unknown header parameter in Content-Disposition

### ISSUE THREAD

**Issue by HelgeL** [Sicos1977/MSGReader#150]
I have an E-mail with the following header:
Content-Disposition: attachment; filename="Beleg_1310693_250489.pdf";
 modification-date-parm="Wed, 23 Jan 2019 12:07:12 +0100"; size=505431

It throws an exception ("ask developer") when trying to load it. Once I change "modification-date-parm=" to modification-date=" it works as expected.

Unfortunately I know nothing about this parameter. Would it make sense to add an additional case in HeaderFieldParser.cs (line 205) or is this header just plain "wrong" or "illegal"?

Thanks and best regards,
Helge

**Comment by HelgeL** [comment]
Or if this header is harmless, would you take a patch to accept "modification-date-parm" as well as "modification-date" as a valid attribute name?

Thank you,
Helge

**Comment by Sicos1977** [comment]
sure no problems

**Comment by Sicos1977** [comment]
Merged
