### ISSUE TITLE
Special chars in BodyHTML not decoding correctly.

### ISSUE THREAD

**Issue by mjefim** [Sicos1977/MSGReader#151]
**Describe the bug**
The BodyHTML field does not decode special characters correctly for some mail items in the 3.6.1 version (though it works ok in 2.5.1). My example was the text "Spoštovani,..." - the latest version decoded it as "Spotovani, š...", so it sort of removes the special char and appends it at the end of the word. It does not happen for all mail items, some are working ok.

**To Reproduce**
Create a  Outlook.Storage.Message instance from a mail item containing html body with special chars.

**Expected behavior**
The special char shoud appear in the correct place.

**Comment by Sicos1977** [comment]
Can you send me the e-mail that is giving you this problem? You can send it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
No response... closed
