### ISSUE TITLE
Message file size remains unchanged after removing all attachments

### ISSUE THREAD

**Issue by opanjki** [Sicos1977/MSGReader#154]
Thanks for this great library. 
Seems there is a problem with removing attachments from MSG files. Message file size with removed attachment is same as with attachments. Seems attachment binary data still not removed from the message.

Issue can be reproduced by this test code
` using (var fileStream = new MemoryStream(File.ReadAllBytes(Path.Combine("SampleFiles", "HtmlSampleEmailWithAttachment.msg"))))`
`            {` 
                `var masterMessage = new Storage.Message(fileStream, FileAccess.ReadWrite);`
                `masterMessage.DeleteAttachment(masterMessage.Attachments[0]);`
               ` masterMessage.Save( `
`Path.Combine("SampleFiles", HtmlSampleEmailWithAttachment_removedAttachments.msg"));`
` }`

Or maybe I need to call some additional method to update message file?

P.S. I tried to open MSG file with removed attachment in Outlook and re-saved from Outlook. Then size of message was updated.

**Comment by Sicos1977** [comment]
I'll try to look into it this evening.

**Comment by Sicos1977** [comment]
Can you please check if this commit (1be1453d70ac683285be2dbbdfd155a8682533c6) fixes your issue?

**Comment by opanjki** [comment]
Hi Kees,
I added test method above to latest code, but size is still the same as before removing attachments...
![image](https://user-images.githubusercontent.com/5277879/56941515-a18b5f00-6b1d-11e9-8ba7-037dc77b55b7.png)

**Comment by Sicos1977** [comment]
See issue #159

**Comment by opanjki** [comment]
In the my comment (Apr 16) you can see my test code example 
var masterMessage = new Storage.Message(fileStream, FileAccess.ReadWrite);

Save method works fine and attachment list is empty if I'm trying to open saved email in Outlook. But email file size remains same as it was with attachments.
