### ISSUE TITLE
Fetching ConversationID from msg file

### ISSUE THREAD

**Issue by DudiZaguri** [Sicos1977/MSGReader#156]
Hi :)
Is there any way to get ConversationID using MSGReader?
I see there are ConversationTopic & ConversationIndex but no ConversationID.
Is there any alternative to ConversationID?
Thanks!

**Comment by Sicos1977** [comment]
At the moment there is no property to read the conversationid. I'll add it on my todo list.

https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/7fdd0560-5e41-4518-bfbb-0c5a6eb6be6c

**Comment by DudiZaguri** [comment]
Update - The reason i needed ConversationID is for identifying an email in an email chain.
But after digging, i realized it's only good for my local machine and not for production, cause it's only available when you have an active outlook explorer, locally.
ConversationIndex is good enough while it's first 44 chars is representing the ConversationId, and every char after is appended for the next email in the same chain.

[https://stackoverflow.com/questions/14823129/how-to-get-universal-outlook-mailitem-conversationid-for-one-email-chain-replied/14840108](url)

**Comment by arisliang** [comment]
A `CoversationId` (or `ConversationIndex`) would be useful for me as well, to be able to group emails by their relations.

Where is the `ConversationIndex`? Don't see it in any property in `MsgReader.Mime.Message` class as well.
