### ISSUE TITLE
.MSG file not parsed correctly

### ISSUE THREAD

**Issue by acdavidh** [Sicos1977/MSGReader#157]
Hello,

We use your library to show a preview of archived msg files in an application, we have hit an issue with a customer where the msg files are not parsed correctly.

They look like this:
![image](https://user-images.githubusercontent.com/40491305/57513060-a2867280-730d-11e9-827a-41e950bfa8c0.png)

Screenshot is from the MSG Viewer application just pulled from master. 

I can send you an example MSG file so you can reproduce it yourself.

**Comment by Sicos1977** [comment]
Yes please do, sent it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
It seems that the HTML part is encoded in UTF-7... something that is almost never used anymore.

**Comment by Sicos1977** [comment]
Fixed with commit 2e085b219ddcd9a265aabda2e2d6453cbd14b802

I released a new nuget package for it. You need version 3.6.2
