### ISSUE TITLE
Cannot commit data in   Read-Only update mode

### ISSUE THREAD

**Issue by clabough** [Sicos1977/MSGReader#159]
With 3.6.2, I started receiving the following error:

> 

Type | OpenMcdf.CFInvalidOperation
-- | --
Message | Cannot commit data in   Read-Only update mode
StackTrace | at   OpenMcdf.CompoundFile.Commit(Boolean releaseMemory)    at MsgReader.Outlook.Storage.Message.Save(Stream stream)    at My.WebAPI.MyController.d__8.MoveNext()   in C:\Users\me\source\repos\MyProject\MyProject.WebAPI\MyProjectController.cs

Rolling back to 3.6.1 fixed the issue

**Comment by Sicos1977** [comment]
Thanks for the bug report, I'll check it this evening and make a fix for it.

**Comment by Sicos1977** [comment]
It's not a bug, please open the file in readwrite mode. Default it is opened in readonly mode.

![image](https://user-images.githubusercontent.com/6692947/58083159-befd9700-7bb8-11e9-8712-8c8c593560fa.png)

**Comment by clabough** [comment]
@Sicos1977 Thanks. Did the default change? I didn't have to set that in 3.6.1.

**Comment by acdavidh** [comment]
Hello,
We get the same error, but we are using the ExtractToFolder method, where it isn't possible to specify the file access.

**Comment by clabough** [comment]
I'm still getting this error using 3.7.0 with `var msg = new Storage.Message(new MemoryStream(logEmail.EmailMsg), FileAccess.ReadWrite);`  I had to roll-back again.

`

Type | OpenMcdf.CFInvalidOperation
-- | --
Message | Cannot commit data in   Read-Only update mode
StackTrace | at   OpenMcdf.CompoundFile.Commit(Boolean releaseMemory)    at MsgReader.Outlook.Storage.Message.Save(Stream stream) 

`

**Comment by clabough** [comment]
Here's the code I'm using that references the object.

`
var msg = new Storage.Message(new MemoryStream(logEmail.EmailMsg), FileAccess.ReadWrite);
var newLogEmail = new LogEmail()
	{
...
		HasAttachments = msg.Attachments.Any()
	};

foreach (var attachment in msg.Attachments.Where(a => a.GetType() != typeof(Storage.Message)))
	{
		var item = (Storage.Attachment)attachment;

var attachmentGuid = FileUtils.AddFile(FileFolders.LogEmailAttachments, item.FileName, item.Data);
		newLogEmail.LogEmailAttachments.Add(new LogEmailAttachment { Filename = item.FileName, AttachmentGuid = attachmentGuid });
	}

foreach (var message in msg.Attachments.Where(a => a is Storage.Message)) 
	{
		var item = (Storage.Message)message;
		var memoryMsg = new MemoryStream();
		item.Save(memoryMsg);

subject = string.IsNullOrEmpty(item.Subject) ? "email" : new string(item.Subject.Where(c => !Path.GetInvalidFileNameChars().Contains(c)).ToArray());

string recipients = string.Join("; ", item.Recipients.Select(r => $"{r.DisplayName} ( {r.Email} )"));

msgGuid = FileUtils.AddFile(FileFolders.LogEmails, subject + ".msg", memoryMsg.ToArray());
docGuid = FileUtils.AddFile(FileFolders.LogEmails, subject + ".doc", Encoding.UTF8.GetBytes(item.BodyRtf));

newLogEmail = new LogEmail { ReceivedDate = item.ReceivedOn, FromAddress = $"{item.Sender.DisplayName} ( {item.Sender.Email} )", ToAddress = recipients, Subject = item.Subject, Body = item.BodyText, MsgGuid = msgGuid, DocGuid = docGuid };

newLog.LogEmails.Add(newLogEmail);

foreach (var attachment in item.Attachments.Where(a => a.GetType() != typeof(Storage.Message)))
{
	var subItem = (Storage.Attachment)attachment;
	var attachmentGuid = FileUtils.AddFile(FileFolders.LogEmailAttachments, subItem.FileName, subItem.Data);
	newLogEmail.LogEmailAttachments.Add(new LogEmailAttachment { Filename = subItem.FileName, AttachmentGuid = attachmentGuid });
}
}
`

**Comment by Sicos1977** [comment]
See release https://github.com/Sicos1977/MSGReader/releases/tag/3.7.1
