### ISSUE TITLE
HTMLBody returns "old Value"

### ISSUE THREAD

**Issue by Gruumshi** [Sicos1977/MSGReader#160]
First of all thanks for the great work and all the help you provide.
Great work, keep it up!

A quick explanation of what I am trying to do. I need to create an interface that automatically sends out mails with a data protection notification. This should happen in different countries with different body languages, texts, sender emails etc.
So my idea was to create the mails with Outlook, save them to a network drive and than access
the .msg-files with the interface to create a mail object which I can send out. Works like a charm except for one issue that is driving me nuts.  When I create a blank new .msg-file, save it and edit it later on with Outlook. The BodyHTML will always return the "first" value and no matter what I do with the .msg-file I am unable to get the latest body from the file that is displayed when I open it.

This is the code I am using to get the body from the .msg-file:

var file = settings.File;

**if (File.Exists(file))
{
        using (var msg = new Storage.Message(file))
	{
		var from = "";
		var bcc = "";
		if (ValidateEmail(msg.SenderRepresenting.Email)) from = sg.SenderRepresenting.Email;
		if (ValidateEmail(msg.Recipients.First().Email)) bcc = msg.Recipients.First().Email;
		var subject = msg.Subject;
		var body = msg.BodyHtml;**

I briefly looked through the reported issues but did not find anything on this, so if this was already discussed I am sorry and a quick reference would be great. Also I am not sure if this
is even an issue with your MSGReader or an issue of the Outlook and the .msg-file itself.

Thanks in advance!

best regards
Gruumshi

**Comment by Sicos1977** [comment]
With the first value you mean the body that you did make when saving the e-mail?

**Comment by Sicos1977** [comment]
And please send me the file that is giving you this issue, also include some screenshots with what is happening and what you would expect to happen.

**Comment by Gruumshi** [comment]
I sent you the info as requested via mail. Thanks for the quick reply.

**Comment by Sicos1977** [comment]
Please check the 3.7.0 version to see if that fixes your issue.

https://github.com/Sicos1977/MSGReader/releases/tag/3.7.0

**Comment by Gruumshi** [comment]
Perfect! That fixed my issue. Thanks a lot.
