### ISSUE TITLE
Message as attachment

### ISSUE THREAD

**Issue by alexkopit** [Sicos1977/MSGReader#161]
Hi,
first of all: thank you very much for this great library!
I have a msg-file, which has an msg-file-attachment. When saving this msg-file-attachment, I get the error "Cannot commit data in Read-Only update mode". I tried to save the attachment the way you described in issue #67 and don't know what else to try to get it running (msgreader v. 3.7.0).
Thanks in advance!
alex

**Comment by Sicos1977** [comment]
See release https://github.com/Sicos1977/MSGReader/releases/tag/3.7.1
