### ISSUE TITLE
exclude translation packs

### ISSUE THREAD

**Issue by Liaorio** [Sicos1977/MSGReader#163]
Hi,

After implementing MSGReader, the "builds" folder will include additional folders in the deploy for each language (de, es, fr, etc.) after building our project.

![image](https://user-images.githubusercontent.com/4003519/59725515-dbaede00-91fb-11e9-8cd2-35e78eccd580.png)

![image](https://user-images.githubusercontent.com/4003519/59725526-e5384600-91fb-11e9-856e-408fb5864ccd.png)

Since we do not need any of these language packs, is there a way to not include them (e.g. add some configuration when using MSGReader to switch this "feature off" )?

Thanks.

**Comment by Sicos1977** [comment]
You can just delete the folders that you don't need. There is no way for me to exclude them from the nuget package.
