### ISSUE TITLE
Encoding and french accents

### ISSUE THREAD

**Issue by Seb9999** [Sicos1977/MSGReader#164]
**Describe the bug**
I want to resend an old email saved as an eml file. The eml contains caracters with accents(é, è, à) within the body but strange caracters are displayed instead like this : �. Is it possible to set the encoding when reading or what can I do to fix it ?
 

**Expected behavior**
Display caracters with accents(é, è, à) correcly.

**Screenshots**
![image](https://user-images.githubusercontent.com/52509298/60622347-1d1fbb80-9dae-11e9-83dd-49ed62d7e4a0.png)

**Additional context**
Version 3.7.3 installed

**Comment by Sicos1977** [comment]
Can you send me the e-mail that is giving you this problem? Please .zip the e-mail before sending it to sicos2002@hotmail.com

**Comment by Seb9999** [comment]
Sadly I can't because it contains confidential information. I noticed yesterday that if I use the default encoding(System.Text.SBCSCodePageEncoding), it works.

Body = Encoding.Default.GetString(eml.HtmlBody.Body), // Accents are OK
Body = Encoding.UTF8.GetString(eml.HtmlBody.Body), // Accents not OK

But it's probably going to cause problems when the application is installed on a different computer
