### ISSUE TITLE
Duplicate file needs improvement

### ISSUE THREAD

**Issue by pernyga** [Sicos1977/MSGReader#166]
If a msg has multiple attachments with the same name, e.g.

foo.txt
foo.txt
foo.txt
foo.txt

Then the method ExtractToFolder will generate strange filenames:

foo.txt
foo_2.txt
foo_2_3.txt
foo_2_3_4.txt

Where the expectations was:

foo.txt
foo_2.txt
foo_3.txt
foo_4.txt

The issue can be solved by two minor corrections:

In method: FileExistsMakeNew

add a new statement:

var **originalTempFileName** = tempFileName;

and change the line

var fileNameWithoutExtension = GetFileNameWithoutExtension(tempFileName);
to
var fileNameWithoutExtension = GetFileNameWithoutExtension(**originalTempFileName**);

**Comment by Sicos1977** [comment]
Fixed in commit 17bc6b8a7e1adc6cb095a4160b7d7bdf643db4c3
