### ISSUE TITLE
email attachment with "Content-Transfer-Encoding: uuencode" not able to extract correctly.

### ISSUE THREAD

**Issue by sarathbabuk** [Sicos1977/MSGReader#168]
we were not able to extract few emails using MsgReader dll, after analysis we found that the attachment "Content-Transfer-Encoding: uuencode" and see the attachment bytes are more than the actuals, due to this the file is not able to open.

**Comment by Sicos1977** [comment]
Can you sent me the file that is giving you this problem? If so then sent it to sicos2002@hotmail.com

**Comment by sarathbabuk** [comment]
sorry, i cannot send email as it has PII information. i had fixed this and released it production. so far its working. i can share the fix details.

**Comment by Sicos1977** [comment]
Please share the fix details with me or clone this repository and make a pull request

**Comment by sarathbabuk** [comment]
[UUEncode.zip](https://github.com/Sicos1977/MSGReader/files/3554612/UUEncode.zip)
not able to create pull request. attaching the files in zip file.

**Comment by Sicos1977** [comment]
Added in commit 2c0496c09e045d13ee4968533b9ae5da3d17207b
