### ISSUE TITLE
BodyText is null

### ISSUE THREAD

**Issue by shaunbteam** [Sicos1977/MSGReader#169]
**Describe the bug**
I am trying to view an msg which was embedded as an attachment in an email, it seems as though when I try to read the BodyText property of an msg file which was an attachment of an msg file the body is null. I can see the html and rtf but not the plain text.

**To Reproduce**
1. Load an email as a Storage.Message which has an .msg file as an attachment
2. Access the attachment item in the array
3. View the body, it is null

**Expected behavior**
The body text to be available.

**Comment by Sicos1977** [comment]
Can you send me the file that is giving you this problem so that I can have a look inside it. Please zip the file before sending it to sicos2002@hotmail.com

**Comment by shaunbteam** [comment]
Hi, It happens with any email file which is being read as an attachment as described.

**Comment by Sicos1977** [comment]
What happens if you first save the attachment to a stream or file and then load it?
