### ISSUE TITLE
Question about Mime Headers with UTF-8

### ISSUE THREAD

**Issue by ygrenier** [Sicos1977/MSGReader#17]
Hi,

I currently work on a french mail extractor, from more sources. I treat .msg and .eml files. 

In France we often use accent on the sender name, and lot of software save this display name in the Mime Headers with UTF-8 encoding but the subject is word encoded in a .eml file. Example :

```
From: "Xx santé xxxxxx" <xxxxx@xxxxx.com>
...
Subject: =?UTF-8?B?RG...
```

So my question : Can I add some methods with encoding different from ASCII although it does not correspond to the RFC? Or should I use another approach to retrieve those emails in UTF-8 ?

Thanks,

Yanos

**Comment by Sicos1977** [comment]
I don't understand what you exactly want to do. The MSGReader should read the UTF-8 encoded subjects without problems

**Comment by ygrenier** [comment]
It's not the subject but the email display name, "From : " in my example. What I said it's the subject is OK but not the emails.

**Comment by Sicos1977** [comment]
Can you send me some example E-mails so that I can look into it. Please send them to sicos2002@hotmail.com. Please zip the msg files before you send them hotmail otherwise corrupts the msg files.

**Comment by ygrenier** [comment]
It's sent from my Hotmail account.

**Comment by Sicos1977** [comment]
I changed the way the header is read. It is now read as UTF-8 instead of ASCII.
