### ISSUE TITLE
Invalid OLE structured storage file

### ISSUE THREAD

**Issue by omisler** [Sicos1977/MSGReader#170]
I wrote an EML file using the EWS API.

I use this code to do that

```
        private void saveAsEML(Stream stream, EmailMessage emEmailMessage)
        {
            stream.Write(emEmailMessage.MimeContent.Content, 0, emEmailMessage.MimeContent.Content.Length);
        }
```

Then I am trying to read that EML generated by the EWS API using msgReader's 

```
FileInfo mailFile
            using (Storage.Message msg = new Storage.Message(mailFile.FullName))
            {

            }
```

However, I get a OpenMcdf.CFFileFormatException exception:
"Invalid OLE structured storage file"

The Stack Trace is

>    en OpenMcdf.Header.CheckSignature()
>    en OpenMcdf.Header.Read(Stream stream)
>    en OpenMcdf.CompoundFile.Load(Stream stream)
>    en OpenMcdf.CompoundFile.LoadFile(String fileName)
>    en OpenMcdf.CompoundFile..ctor(String fileName)
>    en MsgReader.Outlook.Storage..ctor(String storageFilePath, FileAccess fileAccess)
>    en MsgReader.Outlook.Storage.Message..ctor(String msgfile, FileAccess fileAccess)

**Comment by Sicos1977** [comment]
You cant open an EML file with the code that expects a MSG file. Look into the reader class about how to open en EML file.
