### ISSUE TITLE
ExtractToStream an .msg file

### ISSUE THREAD

**Issue by ranielll** [Sicos1977/MSGReader#173]
how to do this? I cant find it. the existing one is using WriteEmlStreamEmail.. I cant find the msg version.

thanks

**Comment by acdavidh** [comment]
Hello,
I'm hitting the same issue, looks like the ExtractToStream method only supports EML messages, not MSG..

**Comment by ranielll** [comment]
any updates?

**Comment by Sicos1977** [comment]
This indeed is only for mime files, I'll put it on my to do list to modify the code so that it also will work for MSG files
