### ISSUE TITLE
How to delete all attachments from an eml file.

### ISSUE THREAD

**Issue by Kulgann** [Sicos1977/MSGReader#174]
Hi there I just want to use this to delete all attachments from a bunch of eml files but cant seem to find a way to do this. I tried extracting the body and headers like in the provided example but since the eml files contain Cyrillic letters the encoding seems to mess up and I cant fix that too. Any help would be appreciated.

**Comment by Sicos1977** [comment]
There is no option in MSGReader to delete attachments in en EML file. Your better of using MimeKit --> https://github.com/jstedfast/MimeKit
