### ISSUE TITLE
Question/Suggestion - Can RTF in Email be converted to HTML?

### ISSUE THREAD

**Issue by m7md7sien** [Sicos1977/MSGReader#176]
I tried couple of rich text .msg files using Nuget version 3.7.5 but I found only BodyRtf property in Message class is populated with the RTF body, but BodyHtml is null.

Does MSGReader supports converting RTF to HTML?

**Comment by Sicos1977** [comment]
Yes it does.

**Comment by ole1986** [comment]
Wow,.. how?!

**Comment by Sicos1977** [comment]
If msgreader only finds an RTF then the HTMLBody is populated with HTML that is converted from RTF. I use RTFPipe for that.

**Comment by Sicos1977** [comment]
https://github.com/erdomke/RtfPipe

**Comment by ole1986** [comment]
Ok but this is not part of MSGReader...

**Comment by ole1986** [comment]
> f msgreader only finds an RTF then the HTMLBody is populated with HTML that is converted from RTF. .

It does not do it automatically

**Comment by Sicos1977** [comment]
I'll will add it in a new version
