### ISSUE TITLE
Does MSGReader working with xamarin ios?

### ISSUE THREAD

**Issue by JeffW2012** [Sicos1977/MSGReader#177]
I'm working on Xamarin forms, it can pass compiling with Andriod platform, but it can't pass compiling with IOS platform, does this components work with Xamarin IOS? Thanks.

It show following information.

Error		Can't resolve the reference 'System.Security.Cryptography.Pkcs.SignedCms', referenced from the method 'System.Void MsgReader.Outlook.Storage/Message::ProcessSignedContent(System.Byte[])' in 'System.Security.Cryptography.Pkcs, Version=4.0.3.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by Sicos1977** [comment]
I have no idea, it is build for .net core so it should work but I never tried it

**Comment by jaspervanmegroot** [comment]
@JeffW2012 did you fix that error? I have the same error when publishing on a real device. On the simulator it works

**Comment by jaspervanmegroot** [comment]
@Sicos1977 of weet jij misschien hoe ik de bovenstaand error kan oplossen?

**Comment by JeffW2012** [comment]
Not solved yet, I didn't use this components since then.
