### ISSUE TITLE
WriteEmlStreamEmail write file to 'email' folder

### ISSUE THREAD

**Issue by acdavidh** [Sicos1977/MSGReader#178]
Hello,

The WriteEmlStreamEmail method in Reader.cs writes the contents of the file to the 'email' folder?

Looks like this was leftover from some debugging?

https://github.com/Sicos1977/MSGReader/blob/95a58abfa97c83f7efe2d724e2e7118fa9f0361a/MsgReaderCore/Reader.cs#L945

**Comment by Sicos1977** [comment]
Fixed in commit e963dd7c93e845a490a4737ee5c78f00977aef67
