### ISSUE TITLE
Nuget Restore Fails

### ISSUE THREAD

**Issue by sergioadh** [Sicos1977/MSGReader#18]
I am experiencing an issue when using Nuget restore with MSGReader package 1.9.3. This issue is documented https://nuget.codeplex.com/workitem/4489.

WARNING: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it.

**Comment by Sicos1977** [comment]
I'll will look into this, this evening and make a new package to see if that fixes the error

**Comment by Sicos1977** [comment]
A new package has been uploaded
