### ISSUE TITLE
Arabic characters turn into ??????????

### ISSUE THREAD

**Issue by TonyValenti** [Sicos1977/MSGReader#180]
**Describe the bug**
Arabic characters turn into question marks

**To Reproduce**
1.  Send yourself an MSG file with this subject:
FW: RE: مكتب العنزي ومشاركوه محامون

2.  Parse the MSG file.

3.  Observe the following
Message.Headers.Subject = "FW: RE: مكتب العنزي ومشاركوه محامون" (Good!)
Message.Subject = "FW: RE: ???? ?????? ???????? ??????" (BAD!!!)

**Expected behavior**
I expect them to be the same.  Why are they different?

**Desktop (please complete the following information):**
 - Windows 10 Pro x64.  .NET 4.6.1

**Additional context**
None

**Comment by Sicos1977** [comment]
Can you send me the msg file that is giving this problem? If so then please send it to sicos2002@hotmail.com

**Comment by TonyValenti** [comment]
Hi @Sicos1977 ,
I sent you the attachment.  Did you get it?

**Comment by Sicos1977** [comment]
No I did not get it.. I also checked the spam folder

**Comment by Sicos1977** [comment]
Seems to be working without any problems

![image](https://user-images.githubusercontent.com/6692947/69946725-7f5f2280-14ec-11ea-976a-3e5a7f5644f4.png)
