### ISSUE TITLE
SentOn datetime not in correct timezone

### ISSUE THREAD

**Issue by 9jigarpatel** [Sicos1977/MSGReader#181]
**Describe the bug**
Export MSG as HTML after changing the timezone in application programmatically or manually, the first time it gives proper date & time but after changing the timezone again, it is not setting date & time properly.

**To Reproduce**

1. Change time zone
2. Export MSG as HTML
3. Repeat steps 1 & 2 without restarting the application

**Expected behaviour**
It should convert SentOn date & time according to newly set timezone.

**Example**
First time exporting
Fri 11/11/2016 12:29 AM (IST)
Changing timezone to International Date Line West (UTC-12:00)
Thu 11/10/2016 6:59 AM
Changing timezone to FIJI (UTC+12:00)
Thu 11/10/2016 6:59 AM (It should be **Fri 11/11/2016 7:59 AM**)

- Reader object is created each time
- This happens when changing timezone multiple time and exporting MSG in a single session. If I restart the application then it will give the correct date & time.

**Desktop**

- Windows 10
- Library-Version: 3.7.8 & 3.7.3

**Comment by Sicos1977** [comment]
This is not a bug in MSGReader but rather the effect of changing the timezone. I just use the standard c# DateTime object
