### ISSUE TITLE
Outlook files can't open after removing attachments

### ISSUE THREAD

**Issue by Identekit** [Sicos1977/MSGReader#182]
**Describe the bug**
Using the following code I am attempting to open and then save an Outlook MSG file from an uploaded file stream.

![code](https://user-images.githubusercontent.com/57924280/69105732-0c9c7480-0a21-11ea-8fa2-57981d1e77d8.png)

When I go to open the saved file I receive the error "We can't open '<File>'.  It's possible the file is already open, or you don't have permission to open it."
If I remove the line "outlook.Save(memoryStream);" the file saves and opens fine.

**To Reproduce**
See above

**Expected behavior**
I should be able to open the outlook file, do something with MSGReader (i.e. remove attachments), save the resulting stream to a file and still be able to open the MSG file.

**Screenshots**
![error](https://user-images.githubusercontent.com/57924280/69105492-4456ec80-0a20-11ea-9f44-756cf49447ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, C# ASP.NET 4.7.2, MVC 5
 - All Browsers

**Smartphone (please complete the following information):**
 - N/A

**Comment by maximelaro** [comment]
I had the same issue when I try to save the result intoba stream. If you save the file on a computer directly it work. In my case I wanted to extract attachments and remove them from the .msg but I ended extracting them and leaving them in the .msg until this bug get fix.

**Comment by Identekit** [comment]
> I had the same issue when I try to save the result into a stream. If you save the file on a computer directly it work. In my case I wanted to extract attachments and remove them from the .msg but I ended extracting them and leaving them in the .msg until this bug get fix.

That's exactly what I'm trying to do, remove all the attachments from the .msg file and then save the .msg without any attachments.  Unfortunately I don't have the option of saving it before the attachments are removed.

This is too bad, this library is simple and I thought it had promise :( I hope they can fix it before my deadline forces me to find a different solution.

**Comment by TonyValenti** [comment]
I've run into this problem and I'm 99% sure it is actually an outlook bug.  When Outlook opens an MSG file and then you close the MSG file, Outlook does not immediately release the file and prevents you from opening it for a period of time.

**Comment by Identekit** [comment]
> 
> 
> I've run into this problem and I'm 99% sure it is actually an outlook bug. When Outlook opens an MSG file and then you close the MSG file, Outlook does not immediately release the file and prevents you from opening it for a period of time.

Not sure I see that.  The .MSG file I am dealing with opens just fine until I try and deal with it in a stream.  Only when saving the "new" stream from MSGReader do I get that error...Outlook shouldn't be involved in that process.  My suspicion is that MSGREader is corrupting the file some how when saving the output back to the stream.  I've encountered similar issues dealing with MS file types before...I think they like to bury stuff in the bits that don't translate.

Either way, looks like @Sicos1977 has marked this as a bug so hopefully we can get a resolution quick.  Thanks @Sicos1977 :)

**Comment by maximelaro** [comment]
@Sicos1977 Any idea how long it would take to get the bug fixed? If you do not expect to correct it soon do you accept help to fix this issue?

**Comment by Sicos1977** [comment]
The problem to fix it is the time that I will have to make free for it :-) ... I always accept pull requests.

**Comment by Sicos1977** [comment]
I just tested this but everything seems to work as expected.

```c#
        [TestMethod]
        public void RemoveAttachments()
        {
            using (var inputStream = File.OpenRead(Path.Combine("SampleFiles", "EmailWith2Attachments.msg")))
            using (var inputMessage = new Storage.Message(inputStream, FileAccess.ReadWrite))
            {
                var attachments = inputMessage.Attachments.ToList();

                foreach (var attachment in attachments)
                    inputMessage.DeleteAttachment(attachment);

                using (var outputStream = new MemoryStream())
                {
                    inputMessage.Save(outputStream);
                    using (var outputMessage = new Storage.Message(outputStream))
                    {
                        var count = outputMessage.Attachments.Count;
                        Assert.IsTrue(count == 0);
                    }
                }
            }
        }
```

**Comment by Identekit** [comment]
@Sicos1977
Sorry it took me so long to get back to this.  This works great!  I guess I was just managing my stream poorly.

Thank you for taking the time.
