### ISSUE TITLE
Access Outbound Headers / Property Accessor Properties 

### ISSUE THREAD

**Issue by TonyValenti** [Sicos1977/MSGReader#183]
Hi @Sicos1977 @Sicos2002 ,
The attached message is a sent message message that had a custom header applied to it.  The custom header is:
x-alphadrive-sender-message-id
and it has a value of:
[ { 0 d 6 e 9 d b 7 - 3 c b 9 - 4 b 4 e - 8 5 f 7 - 8 1 4 3 c 2 a 4 d 4 7 b } - { e c 1 6 6 3 2 e - a 0 4 c - 4 7 6 3 - a 8 9 6 - 2 2 9 6 8 3 0 c 8 d 6 4 } ]
(without all the spaces)

If you look at the raw data of the MSG file you can see it there but I'm not sure how to access this value.  What should I be doing?

[Test Message.msg.zip](https://github.com/Sicos1977/MSGReader/files/3874296/Test.Message.msg.zip)

**Comment by TonyValenti** [comment]
Also, just so you know, this is a high priority item for us.  If we need to compensate you to get this done quickly, we will!

**Comment by Sicos1977** [comment]
I checked the message but that header is not in it. Normally the msg file should have a tag called PR_INTERNET_HEADERS that contains all the headers.... but that is not in the MSG file

**Comment by TonyValenti** [comment]
Hmm.  The value of the header is in there.  Do you ahve any idea how to retrieve this value out?

**Comment by Sicos1977** [comment]
What do you mean with the value is in there? I don't see it anywhere.

**Comment by TonyValenti** [comment]
Here's a screen shot showing the raw contents of that MSG file with the section I'm referencing:

![image](https://user-images.githubusercontent.com/13609558/69349141-e521f380-0c3c-11ea-8676-288e30b0e2b2.png)

**Comment by Sicos1977** [comment]
Are you sure that I have the same msg file?

**Comment by TonyValenti** [comment]
I'm positive!  make sure you're using the MSG file that is attached to the first message of this post.

**Comment by Sicos1977** [comment]
I seem to have found it, its in a property that I never seen before ... __substg1.0_801D001F

**Comment by Sicos1977** [comment]
Is this what you need?

![image](https://user-images.githubusercontent.com/6692947/69351700-03f3aa80-0c7c-11ea-954a-69bd3f03823f.png)

**Comment by Sicos1977** [comment]
I added a property to the message object called

`c# public object GetNamedMapiProperty(string propIdentifier)`

With this one you can get named properties

**Comment by Sicos1977** [comment]
I just uploaded a new package to nuget.

You can get your property like this

```c#
using (var msg = new MsgReader.Outlook.Storage.Message("d:\\testfile.msg"))
{
        var str = msg.GetNamedMapiProperty("801D")
        // Do something with it.
}
```

If you want to make a donation for this project that use the donate button at the end of this page.

https://github.com/Sicos1977/MSGReader

**Comment by TonyValenti** [comment]
Awesome!  How do I get the name of the property?  When I add the property in outlook, I add it with a name like "x-alphadrive..." ?

**Comment by TonyValenti** [comment]
Hi @Sicos1977 - I just made a donation.  Thank you so much for your help!

Related to the above - how do I get the value of that specific header?  When I use OutlookSpy, I see the following:

![image](https://user-images.githubusercontent.com/13609558/69428690-73f34680-0cf7-11ea-8af1-e2e34d3c404b.png)

**Comment by Sicos1977** [comment]
Can you send me that message because it doesnt show up in the test message that I have.

![image](https://user-images.githubusercontent.com/6692947/69439221-c90a7900-0d46-11ea-87a9-15ec088a795c.png)

**Comment by Sicos1977** [comment]
I don't know if I have build something in the MSGReader to read the names of the properties. If not then I will have to build it what will take me some days.

**Comment by TonyValenti** [comment]
Hi @Sicos1977 ,
Using the MSG file that I attached at the beginning of this thread, you can see the name of the header in there:

![image](https://user-images.githubusercontent.com/13609558/69445713-8336bc00-0d18-11ea-920a-c78944fe6d81.png)

**Comment by Sicos1977** [comment]
I think that this is what you want

![image](https://user-images.githubusercontent.com/6692947/69526723-2121c500-0f6b-11ea-86b0-00a0d188dfe7.png)

`var test = message.GetNamedMapiProperty("x-alphadrive-sender-message-id");`

**Comment by Sicos1977** [comment]
Tonight I will build a new nuget package and upload it. In the mean time you just can get the source from GitHub and compile it yourself.

**Comment by Sicos1977** [comment]
Just ignore the last message. I just released a new nuget package 3.7.10

**Comment by TonyValenti** [comment]
This is excellent!  I have one last request:
Can you expose all named properties as a dictionary or some other similar capability?  I'd like to be able to get a list of all of them and then iterate through their values.

**Comment by TonyValenti** [comment]
PS - I made another donation as well.

**Comment by Sicos2002** [comment]
Sure I'll will look into it tomorrow. I already have the list but it's internal so I only have to expose it to the outside world.

Met vriendelijke groet,
Kees van Spelde

________________________________

**Comment by Sicos1977** [comment]
I just released a new nuget package 3.7.11 It has a method called GetNamedProperties() that returns a list with all the named properties

**Comment by TonyValenti** [comment]
Hi @Sicos1977 ,
I just tested it out and it looks like ````GetNamedProperties()```` does return the list, however, calling ````GetNamedMapiProperty```` always returns null.

Can you please take a look?

**Comment by TonyValenti** [comment]
Here's my code:
````

                        {
                            foreach (var item in (Message?.GetNamedProperties()).EmptyIfNull()) {
                                try {
                                    ret.SaveAs_Communication_Headers[item] = Message.GetNamedMapiProperty(item).ToString();
                                } catch { }
                            }

                        }
````

**Comment by Sicos1977** [comment]
I did some modifications in the code this morning so I'll have to check if I did not break something.

**Comment by Sicos1977** [comment]
Yes I did break something this morning. I just uploaded a new package 3.7.12 ... this has the bug fixed and everything should be working fine.

**Comment by Sicos1977** [comment]
This part of your code will not always work (In this case its good that you have a try catch).

`ret.SaveAs_Communication_Headers[item] = Message.GetNamedMapiProperty(item).ToString();
`
The GetNamedMapiProperty will always return an object because it does not know what kind of type the named property is. Sometimes it can be a datetime, a string or something else. You could check it like this

```c#
var obj = Message.GetNamedMapiProperty(item).ToString();
var str = obj as string;
if (str != null) 
{
  // do something)
}

var dt = obj as DateTime;
if (dt != null)
{
  // Do something
}

etc...
```

**Comment by Sicos1977** [comment]
Just for my own curiosity ... for what are you using the MSGReader? A product that you made?

**Comment by TonyValenti** [comment]
@Sicos1977 -
The problem is that ````GetNamedMapiProperty```` is always returning ````null````. Try it on the message at the top of this thread. You'll see!

RE our product, go here:
https://www.fasterlaw.com/

and watch the video.  We're using MSGReader for the Faster Mail and Faster Time features.

**Comment by Sicos1977** [comment]
Did you get the new nuget package (3.7.12) this fixes the GetNamedProperty method.

**Comment by Sicos1977** [comment]
Nice product... always nice to see that MSGReader is put to good use. I originaly developed it to use it to convert MSG (and EML) files to PDF.
