### ISSUE TITLE
Access to not exposed MAPI data

### ISSUE THREAD

**Issue by NickJWilliams** [Sicos1977/MSGReader#187]
Hello,

Is it possible to access other MAPI properties that are not exposed via the Message class. e.g. PR_PROVIDER_SUBMIT_TIME 

Thanks

**Comment by Sicos1977** [comment]
I added 2 new options in the latest release todo what you want.

https://github.com/Sicos1977/MSGReader/commit/a0aa75d464ee30bf3c9c84b788a845b9d1ff997c

**Comment by NickJWilliams** [comment]
Thanks
