### ISSUE TITLE
Exception while loading appointmentrequest

### ISSUE THREAD

**Issue by julianfuerlinger** [Sicos1977/MSGReader#188]
**Describe the bug**
The following error will be thrown if i try to load the attached msg.

Error message:
Destination array is not long enough to copy all the items in the collection. Check array index and length

**To Reproduce**
using(var msg = new Storage.Message(path to msg))
{
       // extract msg here
}

**Desktop (please complete the following information):**
 - OS: OS: Windows 10, C# 4.6.1
- MsgReader 3.7.12

[appointment request.zip](https://github.com/Sicos1977/MSGReader/files/3900528/appointment.request.zip)

**Comment by Sicos1977** [comment]
Fixed in commit fa13b287671e9198aad09567b48053d03b5f3a7c
