### ISSUE TITLE
Rfc822DateTime

### ISSUE THREAD

**Issue by MNBreer** [Sicos1977/MSGReader#19]
Hallo,

I have used the library for an test with EML Mails, generated by Lotus Notes..
In the Header is a time as send date with an EST zone Tag. The regex in the file "Rfc2822DateTime.cs" interpret this tag as *+0500-0600-0700* Hours. 
The Regex interprets E = +0500 S = -0600 T= -0700.
I have changed the regex - in a private branch- from the file "Rfc2822DateTime.cs" from 
private const string RegexOldTimezoneFormats = @"UT|GMT|EST|EDT|CST|CDT|MST|MDT|PST|MSK|PDT|[A-I]|[K-Y]|Z";
into
private const string RegexOldTimezoneFormats = @"\b((UT|GMT|EST|EDT|CST|CDT|MST|MDT|PST|MSK|PDT)|([A-IK-Za-ik-z]))\b";
Now the Time interpreter works fine :-)

Best Regards
MB

**Comment by Sicos1977** [comment]
I included your regex in the 1.9.4 version. Thanks.
