### ISSUE TITLE
How do I know if an attachment is inline or no?

### ISSUE THREAD

**Issue by maximelaro** [Sicos1977/MSGReader#190]
Hello,

How do I know if an attachment is inline or no? I try to check with IsInline but it does not seem to work... It return true for all attachment despite they are not all inline attachment.

Thank you

**Comment by Sicos1977** [comment]
When the Inline property in an attachment is set to true

            /// <summary>
            /// True when the attachment is inline
            /// </summary>
            public bool IsInline { get; }
