### ISSUE TITLE
In .net-core version windows-1252 chars are not translated correctly in BodyText

### ISSUE THREAD

**Issue by stefansolid** [Sicos1977/MSGReader#191]
When running the .net version the BodyText handles Swedish åäö characters correctly, but when we switched over to .net core the text came out with ??? instead of åäö.

The conversion of body-text to raw text seems not to use correct code-pages. If I call BodyHtml the åäö chars are translated correctly. 

BodyText (error): Mera text med ���
BodyText (expected): Mera text med åäö

Have tried to convert BodyText to windows-1252 after receiving BodyText without luck. Installed System.Text.Encoding.CodePages to add support for more code-pages. 

Looking at the code, BodyRtf uses MessageCodePage.GetString(rtfBytes) - should this also be used for getting the string for BodyText to make sure code-page is taken into consideration?

**Comment by stefansolid** [comment]
Just tried a modification that works.

            public string BodyText
            {
                get
                {
                    if (_bodyText != null)
                        return _bodyText;

                    var textBytes = GetMapiPropertyBytes(MapiTags.PR_BODY);
                    _bodyText = MessageCodePage.GetString(textBytes);
                    return _bodyText;
                }
            }

Change for subject:

            public string Subject
            {
                get
                {
                    if (_subject != null)
                        return _subject;

                    _subject = GetMapiPropertyString(MapiTags.PR_SUBJECT);

                    var textBytes = GetMapiPropertyBytes(MapiTags.PR_SUBJECT);
                    _subject = MessageCodePage.GetString(textBytes);

                    if (string.IsNullOrEmpty(_subject))
                        _subject = string.Empty;

                    return _subject;
                }
            }

But that requires change in GetMapiPropertyFromStreamOrStorage:

                case PropertyType.PT_STRING8:
                    //return GetStreamAsString(containerName, Encoding.Default);
                    return GetStreamBytes(containerName);

Probably breaks some other compatibility. However, solves the case where "Encoding.Default" is not proper Decoder.

**Comment by stefansolid** [comment]
Simpler solution in GetMapiPropertyFromStreamOrStorage:

Code can be prettier of course...

                case PropertyType.PT_STRING8:
                    var codePage = GetMapiPropertyInt32(MapiTags.PR_MESSAGE_CODEPAGE);
                    Encoding enc;

                    try
                    {
                        enc = codePage != null ? Encoding.GetEncoding((int)codePage) : Encoding.Default;
                    }
                    catch (NotSupportedException)
                    {
                        enc = Encoding.Default;
                    }
                    return GetStreamAsString(containerName, enc);

**Comment by Sicos1977** [comment]
Can you check if this commit also works in your .net core project? It uses a somewhat different scenario to get the correct codepage.

aae66ae9fc5c6172fb8be5cdc7cba25c6ff66988
