### ISSUE TITLE
Issue with html body

### ISSUE THREAD

**Issue by dariuslf** [Sicos1977/MSGReader#192]
**Description**
I have issues with the Message.BodyHtml property. I've looked at the implementation of this body and sees it prefers converting the BodyRtf property to getting the mapi property.

Unfortunately the rtf conversion loses characters. As far as I can tell, this is due to utf-8 (the encoding of my msg file) being a multibyte encoding rather than a single or double byte encoding. This means that characters can be just one byte long or they can be longer, the encoding knows.

The rtf content is correct and when I fetch the mapi property myself with GetMapiProperty("1013"), this also contains the correct text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an (html) outlook message with the french word "préférence" - see attachment
2. Load the message with new MsgReader.Outlook.Storage.Message(path to saved file);
3. Compare values of BodyRtf, BodyHtml, BodyText and the result of GetMapiProperty("1013")

**Expected behaviour**
I'd expect the BodyHtml property not to lose any characters!

**Attached**
An example msg file to reproduce issue
[test.zip](https://github.com/Sicos1977/MSGReader/files/3931421/test.zip)

**Comment by tobiasroessler** [comment]
I was also able to reproduce this issue by putting the following in a msg file: "règlement d’exécution commun à l’Arrangement"

**Comment by Sicos1977** [comment]
I confirmed it is a bug

**Comment by Sicos1977** [comment]
It seems to go wrong when trying to get the html that is embedded in the rtf body tag

**Comment by Sicos1977** [comment]
Can you check if this commit fixes your issue?

ccbe2a7f57b75a250a62b71e89784242619650b4

It does fix it overhere

**Comment by tobiasroessler** [comment]
Hi,

thank you for your quick response. I will test it tomorrow morning.

Kees <notifications@github.com> schrieb am Mi. 11. Dez. 2019 um 17:09:

**Comment by tobiasroessler** [comment]
Unfortunately I have still the same issue. I checked with your MsgViewer and debugged the code but the new line "goto default;" is not executed in my case. Please find attached my msg file.

[This is a test.zip](https://github.com/Sicos1977/MSGReader/files/3954137/This.is.a.test.zip)

**Comment by Sicos1977** [comment]
What .NET version are you using... core?

**Comment by tobiasroessler** [comment]
Currently .NET Framework 4.7. But as I said I tested it with your MsgViewer and I have the same issue.

**Comment by Sicos1977** [comment]
Are you sure you have the latest version? ... it works fine overhere.

![image](https://user-images.githubusercontent.com/6692947/70690969-35c6c280-1cb8-11ea-975b-a3113a28ed61.png)

**Comment by tobiasroessler** [comment]
But the body should be: règlement **d’e**xécution commun à **l’A**rrangement

**Comment by Sicos1977** [comment]
Ah oke i'll will also check that...

**Comment by dariuslf** [comment]
I haven't been able to test this yet for my use case, but thank you for the quick work on it.
I shall take a look at the start of next week.

**Comment by Sicos1977** [comment]
Hi,

Can you check if this commit 51bf5ce4105463236ddeee7435d701f26aedf247 fixes your isse?

**Comment by tobiasroessler** [comment]
Hi, thank you for the fix. I can confirm that it fixes the issue.

**Comment by Sicos1977** [comment]
I just released version 3.7.14 to nuget.

**Comment by dariuslf** [comment]
Many thanks.
I can also confirm that this fixes my problems.
