### ISSUE TITLE
Is there anyway to get stream of attachment?

### ISSUE THREAD

**Issue by softwareguy74** [Sicos1977/MSGReader#193]
Seems to be no way to get stream of attachment so we can for example save to disk.  Can we get this added please?

**Comment by Sicos1977** [comment]
The attachment is stored in a byte array.

Use a memorystream if you want to have it as a stream.

**Comment by rogatec** [comment]
> The attachment is stored in a byte array.
> 
> Use a memorystream if you want to have it as a stream.

Even if this topic is closed long ago, I just wanted to know if it is possible to get an attachment as a stream, while the attachment is not of type Storage.Attachment rather than another Storage.Message.

For example: having an email msg file, where two other Emails are attached (as msg files)?

**Comment by msab2170** [comment]
"Since this question is from three years ago, you may already be familiar with the solution. In the case of a .msg file, you can use the following code snippet:

```
using var msgFile = new MsgReader.Outlook.Storage.Message(msgFilePath); 
var attachments = msgFile.Attachments; 

foreach (var attachment in attachments){
	if (attachment != null && attachment is Storage.Attachment)  
	{
		var attachmentCast = attachment as Storage.Attachment;
		File.WriteAllBytes({path}, attachmentCast.Data);
	}
	else if (attachment != null && attachment is Storage.Message) 
	{
		var attachmentCast = attachment as Storage.Message;
		attachmentCast.Save({path});
	}
}
```

////////////////////////////////////////////////
and if you want msg file'attachment(msg)' attachment 


```
using var msgFile = new MsgReader.Outlook.Storage.Message(msgFilePath); 
var attachments = msgFile.Attachments; 

foreach (var attachment in attachments){
	if (attachment != null && attachment is Storage.Attachment)  
	{
		var attachmentCast = attachment as Storage.Attachment;
		File.WriteAllBytes({path}, attachmentCast.Data);
	}
	else if (attachment != null && attachment is Storage.Message) 
	{
		var attachmentCast = attachment as Storage.Message;
		var subAttachments = attachmentCast.Attachments;
                foreach (var subAttachment in subAttachmentsObject){
                     var subAttachmentCast = subAttachment as Storage.Attachment;
                    .....
                }
	}
}
```
