### ISSUE TITLE
msgReader.ExtractToFolder in combination with a base href breaks attachment links

### ISSUE THREAD

**Issue by bartkusters-tdi** [Sicos1977/MSGReader#194]
When using msgReader.ExtractToFolder() with an msg file that contains a "base href", attachment links to the base URL instead of using the file:// prefix

**Comment by Sicos1977** [comment]
Can you send me the e-mail that is giving you this bug? If so then please send it to sicos2002@hotmail.com

**Comment by bartkusters-tdi** [comment]
Hi Kees,

I actually cannot share the mail. However I will try to contruct a mail that has the same behavior. For now I worked around the issue, by removing the base url tag from the extracted html.

Regards,
Bart

________________________________
Van: Kees <notifications@github.com>
Verzonden: Thursday, December 26, 2019 4:56:15 PM
Aan: Sicos1977/MSGReader <MSGReader@noreply.github.com>
CC: Bart Kusters <bart.kusters@transformdata.eu>; Author <author@noreply.github.com>
Onderwerp: Re: [Sicos1977/MSGReader] msgReader.ExtractToFolder in combination with a base href breaks attachment links (#194)


Received from external sender

Can you send me the e-mail that is giving you this bug? If so then please send it to sicos2002@hotmail.com<mailto:sicos2002@hotmail.com>

**Comment by Sicos1977** [comment]
No response... closed
