### ISSUE TITLE
The missing RTFPipe error #145 is happening again with the latest version (3.7.13). 

### ISSUE THREAD

**Issue by makingbloke** [Sicos1977/MSGReader#195]
The missing RTFPipe error #145 is happening again with the latest version (3.7.13).  The problem is not in version 3.7.8

**Comment by Sicos1977** [comment]
I'm busy with a new version so I'll fix it in that one

**Comment by tuandunguit** [comment]
BTW, can we upgrade RtfPipe to the latest version? it's 1.0.7246.39337 at the moment.

**Comment by Sicos1977** [comment]
I just released a new 3.7.14 version to nuget. It has the latest RtfPipe included
