### ISSUE TITLE
Stack is empty error msgReader.ExtractToFolder (3.7.13)

### ISSUE THREAD

**Issue by squall9241580** [Sicos1977/MSGReader#196]
I Got an issue "Stack is empty" when using the ExtractToFolder function. I investigated and it is the issue with RtfPipe (https://github.com/erdomke/RtfPipe/issues/26).
It was fixed in the latest version of RtfPipe. Could you please update the latest RtfPipe?

**Comment by Sicos1977** [comment]
I just released version 3.7.14 to nuget. It has the latest RtfPipe included.
