### ISSUE TITLE
Where does a delivery-status report message store the delivery-status details?

### ISSUE THREAD

**Issue by BerendHabekotte** [Sicos1977/MSGReader#197]
I saved a delivery report message from my outlook mailbox as an msg file. I used MsgReader to read this file. Where can I find the message/delivery-status information in the MsgReader.Outlook.Storage.Message class as described in [rfc3464](https://tools.ietf.org/html/rfc3464)

If I use MailKit to read a delivery report from my mailbox and save it to disk, the eml file has a message/delivery-status body part with a specific content.

[DeliveredMessages.zip](https://github.com/Sicos1977/MSGReader/files/4034252/DeliveredMessages.zip)

**Steps to reproduce the behavior:**
1. Unzip DeliveredMessages.zip
2. Open Delivered_Report_AsEml.eml in Notepad
3. Scroll down to 'Content-Type: message/delivery-status'
4. This body part contains the headers Reporting-MTA, Received-From-MTA, Arrival-Date, Final-Recipient, Action, Status, Diagnostic-Code and X-Display-Name. 
5. Use MsgReader to import Delivered_Report.msg as an MsgReader.Outlook.Storage.Message message. 
6. Which property or method of this message reveals the Reporting-MTA and other headers of the delivery-status body part?
 
**Expected behavior**
I expect that the message contains the delivery status information, but I cannot find it.

**Desktop :**
 - OS: Windows 10

**Comment by Sicos1977** [comment]
I did not build in support to copy that body part. I'll add it on my todo list.

**Comment by Sicos1977** [comment]
As far that I can see there is no flag inside the MSG file that is in your first post that I can use the get this information
