### ISSUE TITLE
Outlook Forms with Image 

### ISSUE THREAD

**Issue by yxcvb** [Sicos1977/MSGReader#199]
I tried converting a msg mail with images(within a forms).
Document is created by outlook.

MSGReader don't  puts "<link rel=File-List ...>" meta tag in (wenn missing).

My code:
[Code.txt](https://github.com/Sicos1977/MSGReader/files/4102677/Code.txt)

Test e-mail:
[Test.msg.txt](https://github.com/Sicos1977/MSGReader/files/4102635/Test.msg.txt)

**Comment by Sicos1977** [comment]
At the moment I'm on a skiing holiday. I'll try to look into it next week

**Comment by Sicos1977** [comment]
I dont see anything going wrong. I opened the message in MSGReader and Outlook and it almost look exactly the same

![image](https://user-images.githubusercontent.com/6692947/73868604-0ca25880-4849-11ea-9e03-97274b623163.png)
