### ISSUE TITLE
Library not able to process some of the .msg files

### ISSUE THREAD

**Issue by SonalRana** [Sicos1977/MSGReader#200]
I am using the library to process .msg files. However, there are few files which are not being processed. I get Message = "Unsupported message type". I am attaching one of the problem files in as an example.

1. Provide attached .msg file in the .zip as input
2. string[] files = msgReader.ExtractToFolder(inputFilename, tempFoldername, hyperlink);'
4. Get exception  "Unsupported message type"

**Expected behavior**
Should be able to process the .msg file. 

**Additional context**
Are there any specific property of the file which causes this exception?

**Comment by Sicos1977** [comment]
At the moment I'm on a skiing holiday. I'll try to look in to it next week

**Comment by Sicos1977** [comment]
Support has been added in this commit be01b5e7d44ab2aa6f7342d6cc27b1d0b3d22094 , I'll first have to fix some other issues before bringing out a new nuget package
