### ISSUE TITLE
Library not able to process some of the .msg files

### ISSUE THREAD

**Issue by SonalRana** [Sicos1977/MSGReader#202]
I am using the library to process .msg files. However, there are few files which are not being processed.

**Steps to reproduce the behavior**
Provide attached .msg file in the .zip as input
string[] files = msgReader.ExtractToFolder(inputFilename, tempFoldername, hyperlink);'

**Expected behavior**
Should be able to process the .msg file.

**Additional context**
I have posted similar questions few days back. The example file I posted is processed successfully with new update. Due to security reasons, I am going to share the problem files via email.

**Comment by Sicos1977** [comment]
I checked one of the messages that you sent me but these are corrupt. Those chars should not be there, this is why my code isn't getting all the information you need. At the moment I have no idea how to fix this

![image](https://user-images.githubusercontent.com/6692947/74462664-e4da7280-4e90-11ea-9f34-e2c003d7d347.png)

**Comment by Sicos1977** [comment]
Its the same for the other 2 messages

![image](https://user-images.githubusercontent.com/6692947/74462868-34b93980-4e91-11ea-9044-f8eb4be30786.png)

**Comment by Sicos1977** [comment]
Just ignore my previous 2 messages, can you check if this commit fixes your problems?

474c45ace8fa4a3cb83f1ff2cc526d86175a1ab1

**Comment by SonalRana** [comment]
> Just ignore my previous 2 messages, can you check if this commit fixes your problems?
> 
> [474c45a](https://github.com/Sicos1977/MSGReader/commit/474c45ace8fa4a3cb83f1ff2cc526d86175a1ab1)

**Comment by SonalRana** [comment]
> > Just ignore my previous 2 messages, can you check if this commit fixes your problems?
> > [474c45a](https://github.com/Sicos1977/MSGReader/commit/474c45ace8fa4a3cb83f1ff2cc526d86175a1ab1)

**Comment by Sicos1977** [comment]
?

**Comment by Sicos1977** [comment]
I just published a new nuget packages that should fix the problems with the 3 e-mails that you dind sent me
