### ISSUE TITLE
Extract MSG to Folder issue

### ISSUE THREAD

**Issue by JuanVanWyk** [Sicos1977/MSGReader#203]
Hi. I recently received a couple of emails and would like to extract the contents of the mail but i have run into this error message as described below. I Have updated to the latest version 3.7.15 and I'm still unable to open/extract them

Outlook does seem to open the message without an issue so i don't think the message is that badly corrupted.

If you need the sample message I'm sure I'll be able to send it to you.

Stack trace below:

System.ArgumentOutOfRangeException: Non-negative number required.Parameter name: srcOffset   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)   at OpenMcdf.StreamView.Read(Byte[] buffer, Int32 offset, Int32 count)   at OpenMcdf.CompoundFile.GetMiniSectorChain(Int32 secID)   at OpenMcdf.CompoundFile.GetData(CFStream cFStream)   at MsgReader.Outlook.Storage.Message.<>c__DisplayClass137_0.<Copy>b__0(CFItem action)   at OpenMcdf.CFStorage.<>c__DisplayClass13_1.<VisitEntries>b__0(IRBNode targetNode)   at RedBlackTree.RBTree.DoVisitTreeNodes(Action`1 action, IRBNode walker)   at RedBlackTree.RBTree.DoVisitTreeNodes(Action`1 action, IRBNode walker)   at RedBlackTree.RBTree.DoVisitTreeNodes(Action`1 action, IRBNode walker)   at OpenMcdf.CFStorage.VisitEntries(Action`1 action, Boolean recursive)   at MsgReader.Outlook.Storage.Message.Copy(CFStorage source, CFStorage destination)   at MsgReader.Outlook.Storage.Message.Save(Stream stream)   at MsgReader.Outlook.Storage.Message.Save(String fileName)   at MsgReader.Reader.PreProcessMsgFile(Message message, Boolean hyperlinks, String outputFolder, String& fileName, Boolean& htmlBody, String& body, String& contactPhotoFileName, List`1& attachments, List`1& files)   at MsgReader.Reader.WriteMsgEmail(Message message, String outputFolder, Boolean hyperlinks)   at MsgReader.Reader.ExtractToFolder(String inputFile, String outputFolder, Boolean hyperlinks, Nullable`1 messageType, Stream logStream)

**Comment by Sicos1977** [comment]
Can you please sent the msg files to sicos2002@hotmail.com
