### ISSUE TITLE
MsgReader.Outlook.Storage.Message.Sender empty

### ISSUE THREAD

**Issue by Val3rioC** [Sicos1977/MSGReader#204]
**Describe the bug**
`// Read a email .msg file
                    Message message = new MsgReader.Outlook.Storage.Message(Biz.Attachment.GetCloudAttachmentMS(AttID));

                    // convert string to stream
                    MemoryStream stream = new MemoryStream();
                    StreamWriter writer = new StreamWriter(stream);

                    // Read sender
                    writer.WriteLine("Mittente:" + message.Sender);`

The Message Sender is wrong, it shows `Mittente:MsgReader.Outlook.Storage+Sender`

**To Reproduce**
just call Sender on Console e try read MSG file from Outlook 2013 or 2010

**Expected behavior**
The email address of the Sender

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 79

**Additional context**
Aspnet, C# on VS 2019 Community and netFramework 4.7.1

**Comment by Sicos1977** [comment]
Can you send me the e-mail please? If so then sent it to sicos2002@hotmail.com

**Comment by Val3rioC** [comment]
May I ask way?

**Comment by Sicos1977** [comment]
I cant investigate it when you don't sent me the file that is giving the problem.

**Comment by Val3rioC** [comment]
I have got the point, sorry I thought you were going to ask something by mail, I will send a msg file within one hour. 

Thx

**Comment by Sicos1977** [comment]
Fixed

**Comment by joshuaharder** [comment]
I am experiencing the same issue (with version 3.9.0.0):
Sender is returning "MsgReader.Outlook.Storage+Sender"

**Context**
C# Console Application targeting .NET Framework 4.7.1, using VS Code,  .msg file via Outlook 2016

Please let me know if you prefer I open a new issue, or if I can provide any additional information.

**Comment by Sicos1977** [comment]
Can you send me the file? If so then zip it before sending it to sicos2002@hotmail.com

**Comment by joshuaharder** [comment]
Zipped and sent.  Please let me know if I can provide any other information.

**Comment by joshuaharder** [comment]
I have created a VS solution (2019 Community 16.7.7) that demonstrates the issue with a console app (.Net Framework 4.7.1).
[MsgReaderIssueConsoleApp](https://github.com/joshuaharder/MsgReaderIssueConsoleApp)

**Comment by Sicos1977** [comment]
I'll try to look into it tomorrow (sunday)
