### ISSUE TITLE
No data is available for encoding ...

### ISSUE THREAD

**Issue by JiriOgurek** [Sicos1977/MSGReader#205]
When I call Message.Load() I get this exception: "No data is available for encoding 1250. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method."

BTW, it's raised in GetEncoding() method. Also getting this for other encodings: 1250, 1251, 850.

This particular email file is private, however if you really need it, maybe I can somehow anonymize it, just let me know, please.

Running on Windows 10, **.NET Core v3.1** release.

Thank you for your kind help :-)

**Comment by JiriOgurek** [comment]
Now I've realised this is common .NET Core problem. Solution is simple. Add System.Text.Encoding.CodePages NuGet package to solution and use the following piece of code in application startup class to registester new encodings.

Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

**Comment by Ryanman** [comment]
Thanks for writing out the solution brother, appreciate it!
