### ISSUE TITLE
MessageReader handling segmentation of certain text results in wrong interpretation.

### ISSUE THREAD

**Issue by SonalRana** [Sicos1977/MSGReader#208]
**Describe the bug**
While reading couple of the Japanese .msg files, message reader breaks the text in a way which results in wrong interpretation and incorrect translations.

**To Reproduce**
1. Input test files to messageReader.ExtractToFolder
2. The output sentences have different segmentation as compare to the original .msg

**Expected behavior**
Meaning of the sentences should not get lost.

**Additional context**
I will send the problem files via email

**Comment by Sicos1977** [comment]
Just a small question, did you sent me an msg or eml file? What I now have is an eml file... is this correct?

**Comment by SDSHugh07** [comment]
Hi Sicos1977,

The filename of the email that we sent you is 'RE 【CATW】11月チャージ先について.msg'.

I just sent you an email with it attached, as well as Sonal's preliminary analysis of the issue.

Thanks
-Hugh

**Comment by Sicos1977** [comment]
I'm closing this one for now because I don't think I can do anything about this one. I'll reopen it if there is more info or a possible solution
