### ISSUE TITLE
Getting System.IO.FileLoadException with OpenMcdf

### ISSUE THREAD

**Issue by rusagent** [Sicos1977/MSGReader#209]
I'm getting this exception: 

Could not load file or assembly 'OpenMcdf, Version=2.2.1.2, Culture=neutral, PublicKeyToken=fdbb1629d7c00800' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

I made a c# library and use the dll in another Software Framework called Gupta TeamDeveloper. Everything works fine with the MsgKit but wit hthe MsgReader it doesn't want to work and i always get this error.... Do they use different versions of OpenMcdf and if so how can i solve this? I'm using both, MSGReader and MSGKit...

**Comment by Sicos1977** [comment]
I upgraded the nuget packages in MSGKit to 2.2.1.4. You can get the source from GitHub and compile it.

If you have problems like this then you can always fix it by adding an assembly binding redirect to you app.config

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions
