### ISSUE TITLE
Removing read/write access for Outlook storage

### ISSUE THREAD

**Issue by Pablissimo** [Sicos1977/MSGReader#21]
Hi,

Is the write privilege on the following line required?

https://github.com/Sicos1977/MSGReader/blob/master/MsgReader/Outlook/Storage.cs#L109

Unsure how structured storage works, but it'd be good for a use case I've got (where I can't write to the particular location where the .MSG to parse lives) to be able to parse the message without the filesystem complaining

**Comment by Sicos1977** [comment]
The only reason why that option is added is because someone wanted to have the possibility to remove attachments and then Save the message to a new file. If you can live without this option then you can change it to READ access only

**Comment by Sicos1977** [comment]
I will see if I can add an option to the library to open the file read only.. and then in this case use the READ flag instead of READWRITE

**Comment by Sicos1977** [comment]
The file is now standard opened in read mode, a flag has to be given to the storage constructor to open the file in readwrite/write mode

**Comment by Pablissimo** [comment]
Thanks for this, did the job perfectly!
