### ISSUE TITLE
Wrong charset assignment

### ISSUE THREAD

**Issue by JiriOgurek** [Sicos1977/MSGReader#211]
I've got an email with this TextBody content type:
Content-Type: text/plain; charset="**iso-8859-2**";format="flowed"

After message load it's obviously wrongly assigned to:
ContentType | {text/plain; charset=**us-ascii**}

Thank you for your kind help.

**Comment by Sicos1977** [comment]
Can you sent me the file that is giving the problem? If so then please sent it to sicos2002@hotmail.com

**Comment by JiriOgurek** [comment]
It's been sent two days ago, have you received it and reproduced the bug, please?

**Comment by Sicos1977** [comment]
Yes I have received the message

**Comment by Sicos1977** [comment]
Just to be sure, dit you send me an .eml or .msg file?

**Comment by Sicos1977** [comment]
I did some testing and the reason why it is going wrong is because the eml containts an smime.p7s file. At the moment the eml parser does not support this. I have to build that into msgreader.

**Comment by Sicos1977** [comment]
This commit fixes your issues 186ed7a3d8cb3eccb70a0194f96b9f0fcbed7e05
