### ISSUE TITLE
MSGReader BodyHtml contains a string not present in the email

### ISSUE THREAD

**Issue by glent1** [Sicos1977/MSGReader#213]
BodyHtml for an email loaded from a file in msg format contains a string at the start of the body that is not present when the msg file is viewed in outlook, nor if that email is saved as html.  The string is "16777216fFilled1"

**Comment by glent1** [comment]
Steps to reproduce
1. Download the attached file
2. Rename it as X.msg
2. Open it with  var v=new MsgReader.Outlook.Storage.Message("X.msg")
3. Extract the HTML with v.BodyHtml
4. View the extracted HTML

What should be rendered ...

> Test Message

What is rendered 
 
> 16777215fFilled1
>
>Test Body



[X.MSG.txt](https://github.com/Sicos1977/MSGReader/files/4413140/X.MSG.txt)

**Comment by glent1** [comment]
Problem is present in 3.7.19

**Comment by Sicos1977** [comment]
It has nothing todo with 3.7.19 seems to be a RTF tag that currently is not supported.

{\*\background {\shp{\*\shpinst{\sp{\sn fillColor}{\sv 16777215}}{\sp{\sn fFilled}{\sv 1}}}}}\lang3081 \htmlrtf0

**Comment by Sicos1977** [comment]
Fixed in this commit da3579dfd8be6fea4faa4f4a4df5db9a92d5c6dc
