### ISSUE TITLE
[Question] Embed images in rtf mail body

### ISSUE THREAD

**Issue by Zoidster** [Sicos1977/MSGReader#214]
A msg mail with a body in rtf format can have embedded images.
Is there a way to extract a valid rtf with the images correclty embedded?

Currently I have both the images and the rtf text but no way to insert them because I am missing the correct mapping/functionality.

I do the following:

- Import a msg file with rtf body and embedded images
- Use the `msg.BodyRtf` property to get the rtf content
- Use the `msg.Attachments` and select all `IsInline == true` Attachments
- Somehow combine the two?

The rtf format is an enigma to me, so I don't know how I would insert the images manually, and I think there are already image references in the rtf code.

I'm running version 3.7.19 in a netstandard2.0 library.

**Comment by Sicos1977** [comment]
When an attachment is embedded into the rtf then you need to use the RenderPosition property.
Position 1 is the first attachment and position 2 the second... etc..

```c#
            /// <summary>
            /// Returns the rendering position or -1 when unknown
            /// </summary>
            public int RenderingPosition { get; }
```

**Comment by Zoidster** [comment]
I tried to use the MsgViewer and I put the rtfpipe repo at the correct location but I get an error:
![grafik](https://user-images.githubusercontent.com/924818/78222566-bc9ce680-74c5-11ea-8dbd-ce7a5772ba11.png)

I just executed the build.ps1 script, are there more steps to get it to run?
Tanks!

**Comment by Sicos1977** [comment]
You can get the correct RtfPipe dll from here:

- Clone the repo https://github.com/erdomke/RtfPipe
- Edit the build properties so that the DLL is signed when building
- Copy the build dll the the MSGViewer, reference it

Now the viewer should work.
