### ISSUE TITLE
Attachment considered Inline when have ContentId that don't match on HtmlBody

### ISSUE THREAD

**Issue by NatsuDragonEye** [Sicos1977/MSGReader#215]
When an email has a _non-inline_ attachment and **ContentID is not null somehow** (through PR_ATTACH_CONTENTID MapiTags) the email html body will try match the string _"cid:"_ and the attached attachment is set to _true_ if matched. However, if the email body don't be able to match the string _"cid:"_, internally, the application do not considered the attachment as inline, however, **in the Attachment Object the property IsInline is set to True incorrectly**.

![Attach](https://user-images.githubusercontent.com/23026632/79492230-9889eb00-8017-11ea-8fe0-e764f70c6a54.jpg)

According to my analysis, the issues ocurrs because the IsInline property is only assigned on Attachment constructor if ContentID is/is not null.

![image](https://user-images.githubusercontent.com/23026632/79492308-b35c5f80-8017-11ea-9d45-f3f1a6a138f1.png)

This only happens in emails that for some reason have an ContentId like "5FD1VV1432B61040RR5A4FF7D1BFB3BFA@eurprdXX.prd.exchangelabs.com". When I create an email through Outlook application and insert or drag an attachment to the email the ContentId is null.

**Comment by Sicos1977** [comment]
Can you sent me the file that has this problem (so that I can make a workaround)? If so then please sent it to sicos2002@hotmail.com

**Comment by NatsuDragonEye** [comment]
Already sent the email with the subject _MsgReader Issue #215_

**Comment by NatsuDragonEye** [comment]
Email as an attachment

**Comment by Sicos1977** [comment]
c86b1363772c6c3942fba18ce3ba01aa77fd31d8
