### ISSUE TITLE
Can this package be used to convert an .msg file to .eml?

### ISSUE THREAD

**Issue by MrYossu** [Sicos1977/MSGReader#216]
Not a bug, but a question.

I have a pile of .msg files, and want to be able to open them on a machine that doesn't have Outlook installed. I'd like to convert them to .eml files. Can your package do that?

Thanks

**Comment by Sicos1977** [comment]
No but this person did make it in a fork of my MSGKit project.

https://github.com/BerendHabekotte/MsgKit/commit/e9c63fe37d760f3ff8778cdafd0cf68527ab9ea4
