### ISSUE TITLE
Please expose Contact.MiddleName Property

### ISSUE THREAD

**Issue by rboen** [Sicos1977/MSGReader#217]
Hi there,

I would like to propose a small but useful feature request. The Contact class should expose the missing MiddleName property (MAPI Property 3A44).

like 

 internal Contact(Storage message) : base(message._storage) {
   ....
   this.MiddleName= this.GetMapiPropertyString("3A44");
}

Thanks a lot.

**Comment by Sicos1977** [comment]
Sure I'll add it

**Comment by Sicos1977** [comment]
Added --> https://www.nuget.org/packages/MSGReader/3.7.21

**Comment by rboen** [comment]
Wonderful - thanks for this blazing fast reaction!
