### ISSUE TITLE
Unable to open a .MSG file and delete attachments

### ISSUE THREAD

**Issue by gwong1976** [Sicos1977/MSGReader#22]
Hi Kees,

A very good day to you.

Could I ask how does one open a .MSG file in order to delete the attachments? My attempts to do so have resulted in errors claiming that 'MsgReader.Exceptions.MRCannotRemoveAttachment: Cannot remove attachments when the file is not opened in Write or ReadWrite mode'

I have tried using the following code:

private static void TestMsgReader()
        {
            System.IO.FileStream filetoread = new System.IO.FileStream(@"D:\wph\sources\ReadAnOutlookMsg\bin\Debug\testsomethings.msg", FileMode.Open, FileAccess.ReadWrite);

            Storage.Message mymessage = new Storage.Message(filetoread);            
            
            List<object> mymessageattachments = mymessage.Attachments;

            object currattachment = null;

            for (int x = 0; x < mymessageattachments.Count; x++)
            {
                currattachment = mymessageattachments.IndexOf(x);
                mymessage.DeleteAttachment(currattachment);                
            }

           mymessage.Dispose();
            filetoread.Close();
            filetoread.Dispose();
        }

Many thanks and regards,
Gerald

**Comment by Sicos1977** [comment]
Hi,

Get the latest version 1.9.5 version from Github or Nuget. I introduced a bug in 1.9.4.... forgot to expose some constructors to the message object.

And to delete all attachments you can do something like this.

                var msgfile = new Storage.Message("d:\\example.msg", FileAccess.ReadWrite);

                while (msgfile.Attachments.Count > 0)
                    msgfile.DeleteAttachment(msgfile.Attachments[0]);

                msgfile.Save("d:\\example2.msg");
