### ISSUE TITLE
BodyHtml contains "Microsoft Exchange Server;converted from html;" or  "fillColor14286846fill..."

### ISSUE THREAD

**Issue by Softhies** [Sicos1977/MSGReader#220]
Hello,
i have a problem with some msg's from different Outlook (Win) installations.
Bodyhtml extraction (or load Storage.Message) from a msg starts with 'Microsoft Exchange Server;converted from html;' and some linked images ends with 'fillColor'

![grafik](https://user-images.githubusercontent.com/45853777/86890787-21d42980-c0fe-11ea-891f-55c6de54165b.png)
Only occurs in some installations.
Do you have any ideas to avoid this feature?

**Comment by Sicos1977** [comment]
That seems like some RTF code that is not correctly getting filtered out. Can you send me the msg file that is giving this problem? If so then please sent it to sicos2002@hotmail.com




Met vriendelijke groet,


Kees van Spelde







On Wed, Jul 8, 2020 at 9:53 AM +0200, "Softhies" <notifications@github.com> wrote:















Hello,

i have a problem with some msg's from different Outlook (Win) installations.

Bodyhtml extraction (or load Storage.Message) from a msg starts with 'Microsoft Exchange Server;converted from html;' and some linked images ends with 'fillColor'



Only occurs in some installations.

Do you have any ideas to avoid this feature?

**Comment by Softhies** [comment]
email sended ;)

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/MSGReader/3.7.25 fixes your fillcolor issue. I did not see the other issue.

**Comment by Softhies** [comment]
looks fine, thanks

**Comment by Sicos1977** [comment]
Your welcome
