### ISSUE TITLE
html export: RTF  "HYPERLINK"

### ISSUE THREAD

**Issue by Softhies** [Sicos1977/MSGReader#221]
Hello,
i have a new problem with a msg's from different Outlook (Win) installations.
Bodyhtml extraction (or load Storage.Message) from a msg starts with 'Microsoft Exchange Server;converted from html;' and some linkes starts with "HYPERLINK"

I send you an email.

Can you look at the problem again, please?

**Comment by Sicos1977** [comment]
Sure, I'll try to look into it this weekend




Met vriendelijke groet,


Kees van Spelde







On Fri, Jul 17, 2020 at 4:23 PM +0200, "Softhies" <notifications@github.com> wrote:















Hello,

i have a new problem with a msg's from different Outlook (Win) installations.

Bodyhtml extraction (or load Storage.Message) from a msg starts with 'Microsoft Exchange Server;converted from html;' and some linkes starts with "HYPERLINK"


I send you an email.


Can you look at the problem again, please?

**Comment by Softhies** [comment]
thanks ;)

**Comment by Sicos1977** [comment]
I just released a new nuget package, it should fix both your errors.

https://www.nuget.org/packages/MSGReader/3.7.27
