### ISSUE TITLE
Reading .msg with attachments. .xlsx attachment is corrupt when saving

### ISSUE THREAD

**Issue by XenCloete** [Sicos1977/MSGReader#222]
Hello Kees,
Hoop dit gaan goed met jou ;)

I seem to have an issue when stripping off attachments from the .msg files. The .xlsx file is corrupted. I tested this with your sample .msgs as well. This one in fact. "Installatiehandleiding S&I Agro.xlsx".

Could you please test on your side to see if you are experiencing the same problem?

Groete

Xen Cloete

**Comment by Sicos1977** [comment]
I just tried it overhere but I have no problems opening that XLSX file.

**Comment by XenCloete** [comment]
Thanks for trying.
