### ISSUE TITLE
MSGReader cannot retrieve HTML Body

### ISSUE THREAD

**Issue by SudD3v** [Sicos1977/MSGReader#223]
[Test.zip](https://github.com/Sicos1977/MSGReader/files/5027668/Test.zip)

Hi, I'm having problems retrieving the HTML body from the message reader. It was working fine around a month ago, but i had to code another output info from the email, it was then that I noticed I could not get the htmlbody anymore.

The code i'm using is something like this:

            **using (var msg = new MsgReader.Outlook.Storage.Message(@"C:\Users\P058022\Test.msg"))
            {
                var from = msg.Sender;
                var sentOn = msg.SentOn;
                var recipientsTo = msg.GetEmailRecipients(MsgReader.Outlook.RecipientType.To, false, false);
                var recipientsCc = msg.GetEmailRecipients(MsgReader.Outlook.RecipientType.Cc, false, false);
                var subject = msg.Subject;
                var htmlBody = msg.BodyHtml;
                Console.WriteLine("Body:" + htmlBody);
                // etc...
                Console.ReadLine();
            }**
I could see data on msg.BodyRtf, and msg.BodyText but the debug and my tests show mas.bodyHtml with the value null.

Has anyone found the same issue? If so, how can I fix it?

EDIT: I attatched the .msg file on a zip
Best Regards.

**Comment by Sicos1977** [comment]
Seems to work fine overhere.

![image](https://user-images.githubusercontent.com/6692947/89412538-90210180-d727-11ea-85b9-3e0605ad43bd.png)

**Comment by SudD3v** [comment]
Hi Sicos, thank you for your quick answer, i'm doing a pretty minimalistic test using a cmd line application to minimize problems that may occur with my real solution. (The code is the one i posted on my first post). When i debug i can see several data, attatchments, bodyRtf,bodyText,Subject but not the HTML body as the image bellow shows the value i get is **null**

![image](https://user-images.githubusercontent.com/39554172/89429229-3b848300-d735-11ea-8ffe-894d9b93b04a.png)

If u could share your test code to try and find my problem i would appreciate.

Best Regards

**Comment by Sicos1977** [comment]
Thanks for reporting this issue, I used a return statement somewhere where I should have used a break statement. This is fixed with this commit 615c8a7f5b8eca767e3eadaf0378f98e835a9262

A new nuget packages has been uploaded you need version 3.7.28
