### ISSUE TITLE
Issue with rtfpipe

### ISSUE THREAD

**Issue by omisler** [Sicos1977/MSGReader#224]
In some files I get the following message:

"Could not load file or assembly 'RtfPipe, Version=xxx, Culture=neutral, PublicKeyToken=xxx' or one of its dependencies. The system cannot find the file specified."

I'm using nuget version 3.7.27

**Comment by Sicos1977** [comment]
The rtfpipe assemby is added again (for some reason this sometimes goes wrong when building the nuget package). You need version 3.7.28 from nuget
