### ISSUE TITLE
OpenMcdf

### ISSUE THREAD

**Issue by omisler** [Sicos1977/MSGReader#226]
In some files I get the following message:

"Could not load file or assembly 'OpenMcdf, Version=2.2.1.4, Culture=neutral, PublicKeyToken=fdbb1629d7c00800' or one of its dependencies. The system cannot find the file specified."

I'm using nuget version 3.7.28

**Comment by Sicos1977** [comment]
You are probably using OpenMcdf somewhere else in your project and that version is overwriting the version I'm using. I updated MSGReader to the latest OpenMcdf version. Please use this package --> https://www.nuget.org/packages/MSGReader/3.7.29
