### ISSUE TITLE
MSGReader only retrieves some htmlbody

### ISSUE THREAD

**Issue by SudD3v** [Sicos1977/MSGReader#228]
Hi, i've previously opened the issue https://github.com/Sicos1977/MSGReader/issues/223 after your answer and updating my dependency to the newest version (3.7.31) i was able to read the .msg file I attached and another one. 
Meanwhile i found out that not all the files I'm trying to retrieve the html from are readable.
I'm attaching a zip with 2 files:

- The first file (5 Edição IoT Challenge  Altice Empresas.msg) is readable and i can return the htmlbody as expected
- The second file (A sua zona tem Fibra -MEO-M4-e-Prospects-20200903.msg) is not readble the htmlbody has the value null
![image](https://user-images.githubusercontent.com/39554172/92377875-beb24380-f0fc-11ea-8347-72d2339e0023.png)

Code:
                //var msg = new MsgReader.Outlook.Storage.Message(@"C:\Users\5 Edição IoT Challenge  Altice Empresas.msg");
                var msg = new MsgReader.Outlook.Storage.Message(@"C:\Users\A sua zona tem Fibra -MEO-M4-e-Prospects-20200903.msg");
                var from = msg.Sender;
                var sentOn = msg.SentOn;
                var recipientsTo = msg.GetEmailRecipients(MsgReader.Outlook.RecipientType.To, false, false);
                var recipientsCc = msg.GetEmailRecipients(MsgReader.Outlook.RecipientType.Cc, false, false);
                var subject = msg.Subject;
                var htmlBody = msg.BodyHtml;
                Console.WriteLine("Body:" + htmlBody);
                // etc...
                Console.ReadLine();

Can you help with this issue?

Best Regards
[MSGReaderSample.zip](https://github.com/Sicos1977/MSGReader/files/5182573/MSGReaderSample.zip)

**Comment by Sicos1977** [comment]
Fixed in the latest release

**Comment by SudD3v** [comment]
Hi, i've tested again using the same files and the 3.7.33 version (latest) but the result is the same. 
The file "A sua zona tem Fibra -MEO-M4-e-Prospects-20200903.msg" still returns null.
![image](https://user-images.githubusercontent.com/39554172/93081804-bff8e880-f687-11ea-83ad-7b03f8c51061.png)

Best Regards

**Comment by Sicos1977** [comment]
Fixed in commit https://github.com/Sicos1977/MSGReader/commit/f0251183eaddb4ec52903c86c8ad386d3814f9d2
