### ISSUE TITLE
Gibberish with non unicode msg files

### ISSUE THREAD

**Issue by yosimaurer** [Sicos1977/MSGReader#229]
I tried to parse a msg file with was created using saveas command in outlook .
The save format was "Outlook Message Format" not "Oulook Message Format - Unicode".

The mail contained Hebrew characters in Different fields.
After parsing - properties such as the Sender.displayName and Subject had gibberish characters instead of hebrew characters.
Recipients data however did not have any problem.

Msg files saved as "Oulook Message Format - Unicode" format did not have this problem.

The system locale is "hebrew"
The saved msg file shows everything correctly when displayed in outlook.

Sample of output for Sender DisplayName: éåñé îàååø
Expected result: יוסי מאוור

1. Change system locale to hebrew or any other language with special characters
2. Produce an outlook message with special characters
3. Save the message locally as as msg file with the format  "Outlook Message Format" 
4. Parse using MsgReader
5. See error

**Comment by Sicos1977** [comment]
This is hard for me to test. I can change the language but then I can't read anything anymore. For the moment I'll close this issue, feel free to fix the problem and send me a pull request.
