### ISSUE TITLE
Can you make this pkg compatible with xamarin.ios!!!

### ISSUE THREAD

**Issue by matt2003** [Sicos1977/MSGReader#23]
I was able to get this to run and successfully convert .msg to .eml but cannot compile with xamarin.ios I really would love to use this feature but am stopped by the xamarin.ios issue. It would be great if this could work on xamarin as well thanks in advance.

**Comment by Sicos1977** [comment]
You only want to translate MSG to EML? No attachment extraction?

**Comment by matt2003** [comment]
Hi,It would seem that the attachment would be placed into the eml from the msg?I am not sure if I can store attachments somewhere on a server and call it with some kind of code. It of course would be awesome if the attachments could be appended into the eml but   if it is not possible I understand.Thanks,Matt
Sent from Outlook




On Thu, Sep 3, 2015 at 6:02 AM -0700, "Kees" <notifications@github.com> wrote:












You only want to translate MSG to EML? No attachment extraction?

**Comment by matt2003** [comment]
Hi,
If I remember correctly I believe that this worked on windows and the Mac
with attachments converting from msg with attachments to eml with
attachments. Just xamarin.ios could not compile. As you probably know Mac
does not support .msg so it can't read any of those messages natively.
There is one app that can do it called Klammer but it looks silly opening
up another app with. a totally different design each time for a msg file.
Thanks,
Matt

On Thursday, September 3, 2015, Matt Moitra <mattmoitra@gmail.com> wr:

> Hi,
> It would seem that the attachment would be placed into the eml from the
> msg?
> I am not sure if I can store attachments somewhere on a server and call it
> with some kind of code. It of course would be awesome if the attachments
> could be appended into the eml but   if it is not possible I understand.
> Thanks,
> Matt
>
> Sent from Outlook <http://aka.ms/Ox5hz3>
>
>
>
>
> On Thu, Sep 3, 2015 at 6:02 AM -0700, "Kees" <notifications@github.com

**Comment by Sicos1977** [comment]
Making it compatible with Xamarin is a lot of work, this is because I use native WIN32 methods to read IStorage files. It is on my wishlist but I cant give you an time frame due to the lack of to less private time to look into this.

**Comment by Sicos1977** [comment]
I started developing a new MSG library called MsgKit... my idea is to discontinue MSGReader and add all the features in MsgKit. MsgKit is made to write MSG files but it will be extended with reading to. It is 100% .NET code so it will be much easier to make that one work on Xamarin
