### ISSUE TITLE
Question - outlook .msg files extracting attachments

### ISSUE THREAD

**Issue by ornatwork** [Sicos1977/MSGReader#231]
Is there any known limitation on attachment types that can be extracted from outlook message ?  The code I want to use is below.

Thanks, 
  Orn

var msg = new MsgReader.Outlook.Storage.Message(path, FileAccess.Read)

**Comment by Sicos1977** [comment]
There is no limit, an msg file can have a total of 2048 attachments and it does not matter what kind of attachment it is. You can extract them all.

**Comment by coffeeboosta** [comment]
@Sicos1977 it doesn't seem to work when extracting a .msg attachment from a .msg email

**Comment by ornatwork** [comment]
@coffeeboosta 

Here is a snippet for that, its different than attachments.  Also not that if you rely on headers your email has to be sent somewhere first for the headers to appear in the .msg.  For example, send it to yourself, then save the .msg from your inbox.

      using (var msg = new Storage.Message(path, FileAccess.Read))
      {
        foreach (var thisAttachment in msg.Attachments)
        {
          if (thisAttachment is Storage.Attachment attachment)
          {
            var tempFile = new Controller.Model.TemporaryFileDescriptor(attachment.FileName);
            result.Add(tempFile);
            System.IO.File.WriteAllBytes(tempFile.Path, attachment.Data);
          }
          else if (thisAttachment is Storage.Message message)
          {
            // Create tmp file for saving embedded msg 
            var tempFile = new Controller.Model.TemporaryFileDescriptor(message.FileName);
            // Write embedded msg to disk 
            Storage.Message attachMessage = (Storage.Message)thisAttachment;
            attachMessage.Save(tempFile.Path);
          }
