### ISSUE TITLE
Heap fragmentation issues caused by lots of MemoryStreams being used  

### ISSUE THREAD

**Issue by d-dizhevsky** [Sicos1977/MSGReader#232]
We've faced an issue with lots of OutOfMemory exceptions on production environment and dump analysis showed lots of MemoryStream instances being stuck in Gen2/LOH. This is due to the implementation of the MemoryStream and how it doubles the size of an internal byte[] array to be able to allocate more memory in runtime. We've figured out the call stack and here is the exact line of code which caused the issue (it is being called at high rate in our app):

```
MsgReader.Mime.Message.Load(fs);
```
 I was able to reproduce the issue running the app in 32bit mode (so that total heap size is limited to ~2Gb) and the OOM issue happened at ~3-4 requests per second rate. The fs here is just a FileStream with ~20-30MB *.eml file handle.
So with lots of simultaneous allocations like that, the LOH becomes very fragmented and (I assume) runs out of contiguous memory blocks to allocate new things.

![fa2e5da3-b1cb-4e96-a14e-87db8b841320](https://user-images.githubusercontent.com/25821724/93193758-f13ceb80-f74f-11ea-8275-8c6241d92caa.jpg)

Please consider replacing MemoryStream with something more efficient like RecycableMemoryStream for example.
http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/

**Comment by Sicos1977** [comment]
Added in this commit https://github.com/Sicos1977/MSGReader/commit/c47fba3d8bde58591eade3dbc8c2e97fcca6ac0e
