### ISSUE TITLE
OpenMcdf version

### ISSUE THREAD

**Issue by Markus-Dressel** [Sicos1977/MSGReader#235]
**Describe the bug**
OpenMcdf dependency version 2.2.1.6 had the wrong AssemblyReference (2.2.1.5) which causes some issue when installing MsgReader from Nuget. It has now been fixed in version 2.2.1.9 along with some other bug fixes.

**To Reproduce**
1. Install MsgReader latest version from NuGet
2. OpenMcdf version 2.2.1.6 is installed as a dependency

**Expected behavior**
Rebuilding the projects shows a warning: "OpenMcdf 2.2.1.5 not found". Everything still works and warning can be removed by adding a binding redirect.

**Additional context**
Updating OpenMcdf to the latest version will get rid of this "bug" - it's not really a bug, just something annoying.

**Comment by Sicos1977** [comment]
A new nuget package with the update has been published
