### ISSUE TITLE
Ability to change header styling in the ExtractToFolder output

### ISSUE THREAD

**Issue by EasyPP** [Sicos1977/MSGReader#238]
Hi,

Thank you for the great library.

I notice the header produced is in Times New Roman, whereas it seems that Outlook now uses Arial in the To/From/Subject headers.

Also I think there could be additional padding in the header table between the to/from/subject labels and the data.

I thus suggest the font and padding to be configurable.

This could maybe be done by adding html class and id to the elements, and allow the users to inject / amend the used stylesheet.

**Comment by Sicos1977** [comment]
Feel free to make a pull request

**Comment by EasyPP** [comment]
Let me know if you are happy with the pull-request.

Looking forward to your release on nuget.org

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/MSGReader/3.9.0
