### ISSUE TITLE
Is it possible to see if an e-mail was originally Received or Sent?

### ISSUE THREAD

**Issue by mdocter** [Sicos1977/MSGReader#24]
Hi Kees, thanks for this great and useful library! It came just on time!

I'm importing a large quantity of Outlook *.msg e-mail files into our CRM system. In CRM I can set a property on e-mails to differ between received mails and sent mails. Is there a way to determine this for the *.msg files? I couldn't find a property on the MsgReader.Outlook.Storage.Message Type. My test file also returned filled SentOn and ReceivedOn properties, so those can't be used either.
Any help appreciated.

**Comment by Sicos1977** [comment]
I really don't know... I have to dig into some example emails to see if I can spot any differences between them. Do you maybe have some examples for me?

**Comment by Sicos1977** [comment]
I added an option to retrieve information about the person who has received the MSG file. This property should be null when it is an sent message.

https://github.com/Sicos1977/MSGReader/releases/tag/1.9.7

**Comment by mdocter** [comment]
Thank you Kees! This is great and really helpful. And an extra thanks for adding this so quick! Great service. Keep up the good work!

**Comment by Sicos1977** [comment]
Your welcome :-)

**Comment by mdocter** [comment]
Klopt. Maar GitHub wordt niet alleen maar door Nederlanders bezocht :-), dus vandaar in het brak Engels. Nogmaals dank en succes!

**Comment by mdocter** [comment]
Hoi Kees, er is een kleine typo ingeslopen de nieuwe property heet nu 'RecievedBy' i.p.v. 'ReceivedBy'.

**Comment by Sicos1977** [comment]
Als het goed is deze gefixed in de versie 1.9.8 ... staat ook op NUGET

**Comment by mdocter** [comment]
Thanks. Ik heb de update al binnen.
Veel voorkomende typo. Ik heb er zelf nog eens over [getweet](https://twitter.com/mdocter/status/608357450186686464) :-)

**Comment by Sicos1977** [comment]
De typo overkomt me wel vaker... ik weet goed dat het Received is i.p.v. Recieved maar je leest daar weleens overheen. De classe had wel de goede naam :-) . Maar het is prettig dat je me er op gewezen hebt. Zo maken we samen software beter.

**Comment by mdocter** [comment]
Sorry voor de late reactie. De GitHub e-mail notificaties zijn ingekort/afgekapt, dus ik had je vraag niet gezien. Nu ik in GitHub kijk, zie ik pas de rest :-)
Ik gebruik MSGReader inderdaad voor een conversie/uitfasering van een FileMaker 11 informatiesysteem naar ons CRMatch pakket (wat inderdaad gebaseerd is op Microsoft Dynamics CRM 2015).
Onze klant heeft een grote file share met daarop allerlei type documenten. De doc/docx/pdf/xls etc. gaan naar SharePoint, maar de *.msg bestanden zet ik nu om naar E-mail Activities in Dynamics CRM. Anders moet je in SharePoint eerst de msg downloaden en openen, om te zien wat er ook alweer in staat. Nu zijn ze direct inzichtelijk. Dankzij jouw libary.

BTW. Ik liep net nog wel tegen een issue op, maar die zal ik ff apart als issue aanmelden.
