### ISSUE TITLE
Adding support to require the output of .txt mails to be wrapped in html with html-header

### ISSUE THREAD

**Issue by easyjoh** [Sicos1977/MSGReader#240]
It seems that .msg that do not include a htmlBody are extracted as pure text.

I would suggest support to wrap it up with html and include the header in html.
```

<html>
<body>

<table>
<tr>
<td>HeaderLabel</td><td>HeaderText</td>
</tr>
</table>

<pre>

Message.body as text

</pre>

</body>
</html>
```

**Comment by EasyPP** [comment]
I will work on this, but timing says it wont be until a few weeks.

**Comment by Sicos1977** [comment]
Make it optional, in my case I want to have the text when there is no html. When I want to convert it to PDF then I use https://github.com/Sicos1977/ChromeHtmlToPdf that will automaticly embed it in a pre tag when converting it to PDF
