### ISSUE TITLE
MsgReader.Outlook.Storage.Message -> MessageLocalId return null

### ISSUE THREAD

**Issue by wuliwux** [Sicos1977/MSGReader#242]
Hi,
great Project!

The first time you access the MessageLocalId in it return null.
at the second one it return the correct value.

class: MsgReader.Outlook.Storage.Message
Line: 1181

public RegionInfo MessageLocalId
            {
                get
                {
                    if (_messageLocalId != null)
                        return _messageLocalId;

                    var lcid = GetMapiPropertyInt32(MapiTags.PR_MESSAGE_LOCALE_ID);

                    if (!lcid.HasValue) return null;
                    _messageLocalId = new RegionInfo(lcid.Value);

                   return null; // line 1181: returns null on each first property call

                }
            }

greets

**Comment by Sicos1977** [comment]
Fixed in this commit 0f0acb1066f88f60768e6c370a66f00711137d68

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/MSGReader/3.9.0
