### ISSUE TITLE
When attachment is Storage.Message, it does not show up in the body of the message

### ISSUE THREAD

**Issue by omisler** [Sicos1977/MSGReader#246]
When an email has inside it other emails attached, they do not show up as attachments in the body of the message. Only images and other kind of files do show up.

**Comment by Sicos1977** [comment]
Can you sent me the e-mail and also a screenshot about what is wrong? If so then please send it to sicos2002@hotmail.com . Please zip the msg file before sending it, hotmail otherwise converts to msg to eml format and makes it useless for me.

**Comment by Sicos1977** [comment]
No response... closed
