### ISSUE TITLE
HtmlBody not correct content as Outlook

### ISSUE THREAD

**Issue by johnwc** [Sicos1977/MSGReader#247]
**Describe the bug**
The Message class [always tries to convert RTF to html](https://github.com/Sicos1977/MSGReader/blob/0f0acb1066f88f60768e6c370a66f00711137d68/MsgReaderCore/Outlook/Message.cs#L1129) instead of just reading the html property. We are seeing that the RTF to HTML conversion looks nothing like what we see actually in Outlook. But, the HTML in the html MAPI property looks exactly what Outlook displays.

**To Reproduce**
1. Read any MSG file and view HtmlBody
2. Compare HtmlBody content to MAPI property

**Expected behavior**
HtmlBody to be read from actual MAPI property that contains the Html.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 3.9.0

**Comment by sjmorgan81** [comment]
I think I'm hitting this bug too. The message looks absolutely fine in Outlook, but as soon as I run it through this library:

> Foo bar baz

becomes

> 14286846fillOpacity16384fFilled1wzDescriptionFoo bar baz0100090000032100000000000500000000000400000003010800050000000b0200000000050000000c0202000200030000001e00040000002701ffff030000000000

If anybody more familiar with this stuff thinks it's a different bug, please let me know and I'll file a separate one.

**Comment by sjmorgan81** [comment]
Having dug around in the `Message` object the library creates, it definitely looks like the junk is coming from the RTF.

**Comment by Sicos1977** [comment]
Can you send me the msg file, if so then please ZIP it before sending it to sicos2002@hotmail.com

**Comment by sjmorgan81** [comment]
Sorry, I can't. The messages I'm processing all contain confidential information. Maybe @johnwc has an example you can use.

**Comment by johnwc** [comment]
@sjmorgan81  I'm in the same boat, company does not allow to share such file. Even if it is simple test back and forth email.

@Sicos1977  I will give more info on our setup though, that may help. We are using O365 for our Exchange server. Maybe it is an issue of MAPI email vs SMTP email, as they are diff account types and formats to Outlook.

**Comment by Sicos1977** [comment]
Should be fixed in version 4.0
