### ISSUE TITLE
Saving attached email of an email causes invalid MSG file

### ISSUE THREAD

**Issue by johnwc** [Sicos1977/MSGReader#248]
**Describe the bug**
When saving a attached email(msg) to a file, and then trying to open in outlook, outlook gives a corrupt file error. The odd thing though, is windows explorer shows a preview of the email in the right pane.

**To Reproduce**
1. Create new email in outlook
2. Attach an existing email to this new email.
3. Send to yourself, and save newly received email as msg file.
4. Read msg file with MsgReader, casting the attached email as a Message object and save it as msg file.
5. Double click the msg file to open in Outlook.

**Expected behavior**
Attached email saved as msg to be able to be opened.

**Desktop (please complete the following information):**
 - OS: Windows
 - Outlook: 2016
 - Version 3.9.0

![image](https://user-images.githubusercontent.com/2798441/97525834-c0b6b700-1975-11eb-9df3-a8885745fe30.png)

**Comment by Sicos1977** [comment]
Can you send me your test file.. I'm probably do something wrong but I can't reproduce the error

**Comment by Sicos1977** [comment]
Still can't reproduce.

**Comment by johnwc** [comment]
Are you testing using O365 account(Exchange)? I've noticed the properties and such in the MSG file contains different items between sending via SMTP and MAPI msg files.
