### ISSUE TITLE
'Storage can not be null' exception when creating new Storage.Message by file path.

### ISSUE THREAD

**Issue by mdocter** [Sicos1977/MSGReader#25]
Hi Kees,

I ran into the following issue. When creating a new Storage.Message like this:

```cs
var msgFilePath = @"c:\temp\email.msg";
return new Storage.Message(msgFilePath);
```
I got a 'Storage can not be null' exception from [Storage.cs](https://github.com/Sicos1977/MSGReader/blob/4639f0656293479ccdc5acf76763a42777178d8f/MsgReader/Outlook/Storage.cs#L226).
When using the overloaded Storage.Message constructor which expects a `Stream`, no exception occurs:

```cs
var msgFilePath = @"c:\temp\email.msg";
return new Storage.Message(File.OpenRead(msgFilePath));
```

**Comment by Sicos1977** [comment]
Can you send me the msg file? I tried your code myself and it runs without any problems overhere.

**Comment by Sicos1977** [comment]
I tried the test file and it opened without any problems

![15-10-2015 16-49-37](https://cloud.githubusercontent.com/assets/6692947/10517403/e1b30d42-735c-11e5-9c13-a385eaad8e12.png)

**Comment by mdocter** [comment]
You're right Kees. I isolated the part that failed in a Unit Test and it works. So some other part of my solution was probably causing this. During that time I was messing around with the project .Net target framework versions and reinstalling NuGet packages etc. because of that... Sorry for wasting your precious time.
