### ISSUE TITLE
Bug in RTF Parser results in truncated HTML output.

### ISSUE THREAD

**Issue by cfhirsch** [Sicos1977/MSGReader#250]
**Describe the bug**
We encountered a bug when we tried to parse a MSG file in RTF format to HTML with the Nuget. Output gets truncated, and it looks like it's due to an issue with the RTF parser.

**To Reproduce**
I've sent a sample email to the package author.

**Expected behavior**
We would expect the entire contents of the message to be parsed to HTML, but only the first message footer survives the translation to HTML.

**Comment by Sicos1977** [comment]
I'll try to look into it this weekend.

**Comment by Sicos1977** [comment]
Hi,

I checked your message but it only has an RTF body. To convert RTF to HTML I use RTFPipe (https://github.com/erdomke/RtfPipe)

![image](https://user-images.githubusercontent.com/6692947/101181192-e312b300-364c-11eb-8fca-5b5dcab23f86.png)


The problem with the translation is somewhere in RTFPipe so it is better to raise an issue overthere.

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
When I open the rtf body in an RTF reader then this fails so I guess there is some error in the RTF body that Outlook fixes for you.

![image](https://user-images.githubusercontent.com/6692947/101182377-47824200-364e-11eb-9b2e-2a3b9932b1a3.png)

**Comment by Sicos1977** [comment]
It goes wrong in RTFPipe somewhere over here

![image](https://user-images.githubusercontent.com/6692947/101185147-cd53bc80-3651-11eb-916f-b1ec6cfa3d34.png)

But that is as far as I go, it will take forever for me to figure out how RTFPipe works

**Comment by cfhirsch** [comment]
OK, I'll see if I can engage the authors of RTFPipe. thanks!

**Comment by erdomke** [comment]
This should be resolved in version 2.0.7677.4303 of RtfPipe.

**Comment by Sicos1977** [comment]
I just released a new MSGReader nuget package that has the latest RTFPipe version that fixes your problem.

https://www.nuget.org/packages/MSGReader/3.11.0

**Comment by Sicos1977** [comment]
Also thanks to @erdomke for signing the nuget package, this way I don't have to make a signed version myself anymore 👍
