### ISSUE TITLE
Bug in class EmailAdress ?

### ISSUE THREAD

**Issue by SigiKoh** [Sicos1977/MSGReader#251]
**Describe the bug**
Regex for testing EmailAdress is wrong, e.g. a string like 
John Smith (john.smith@anywhere.com) 
is determined to be correct. But this is the DisplayName

i changed it to 
private static readonly Regex EmailRegex = new Regex(@"^([\w-]+\.)*?[\w-]+@[\w-]+\.([\w-]+\.)*?[\w]+$", RegexOptions.IgnoreCase | RegexOptions.Compiled);

this worked for me ...

**Comment by SigiKoh** [comment]
... but how i can get this correction into my project?
when i moved only the .dll into my projekt-directory, it crashes. :-(

**Comment by Sicos1977** [comment]
Added in commit https://github.com/Sicos1977/MSGReader/commit/381ae7c3f5f23649b7de8280393f2046e101f5a2
