### ISSUE TITLE
msg file with Digital Signature not able to read Email Body

### ISSUE THREAD

**Issue by rajnishdubey3** [Sicos1977/MSGReader#253]
**Email file (*.msg) with Digital signature, failed to read Body as TEXT, HTML** 

While reading the email body as ( text or HTML)  of a *.msg file with Digital signature it returns no text and ZERO Length.

**This needs a fix.**

**Comment by Sicos1977** [comment]
Can you sent me the file that is giving this problem? Please ZIP the MSG file before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
No respone... closed

**Comment by rajnishdubey3** [comment]
Hello Sicos, 
I was busy and not able to send you the file. I send you the file (*.msg) file soon. The problem is that file is from my office with official data and recipient. I will try to create a dummy file and send you. 

Please note:- there is a bug and this needs a fix, which I reported.

**Comment by Sicos1977** [comment]
Yeah but I need an example to reproduce the bug.

**Comment by parweb** [comment]
I'm having problems with this msg

https://files-7nghtbws4.vercel.app/yolo.msg

**Comment by Sicos1977** [comment]
Okey I'll try to look into it this evening

**Comment by rajnishdubey3** [comment]
Dear Sicos,

I have attached the code and email sample (*.msg) file with the Digital Signature. 

Dim mailhtmlBody As String = msg.BodyHtml - This method is working 

The problem is with:

Dim mailTxtBody As String = msg.BodyText

<img width="628" alt="MSGReader Code Sample" src="https://user-images.githubusercontent.com/42049868/104706486-2b8bb900-5741-11eb-8f6b-5713016c21b8.png">


[emailSample.zip](https://github.com/Sicos1977/MSGReader/files/5819567/emailSample.zip)

**Comment by Sicos1977** [comment]
I tried your mail and it opens as expected, the reason why you cant get the BodyText is because there is no body text in the msg file.

**Comment by rajnishdubey3** [comment]
> I tried your mail and it opens as expected, the reason why you cant get the BodyText is because there is no body text in the msg file.

Dear Sicos,

The email ( *.msg) has body text. I have attached here.

![image](https://user-images.githubusercontent.com/42049868/106116818-5c73e100-6178-11eb-8cde-7cf2641e3f41.png)

**Comment by rajnishdubey3** [comment]
Dear Sicos,

I am sending you another example with debug screen. I have used If condition  with "**eml.TextBody.Body**" and "**eml.HtmlBody.GetBodyAsText**" .

Length are as below, for
eml.TextBody.Body   = ZERO
eml.HtmlBody.GetBodyAsText = 5086.

If you would like to have a quick call on skype or anydesk we can discuss on this. 

![image](https://user-images.githubusercontent.com/42049868/106117234-d1dfb180-6178-11eb-9cc6-d723f99ba095.png)

**Comment by Sicos1977** [comment]
Seems to work fine in version 4.0
