### ISSUE TITLE
Conflict with Microsoft.IO.RecyclableMemoryStream package

### ISSUE THREAD

**Issue by patrik-pis** [Sicos1977/MSGReader#255]
There is a conflict with Microsoft.IO.RecyclableMemoryStream package. It is not possible use MsgReader 3.11.0 package and Microsoft.IO.RecyclableMemoryStream package on same project.

Please remove the Microsoft.IO.RecyclableMemoryStream implementation from your library, add a link to the Microsoft.IO.RecyclableMemoryStream package, and add the ability to share RecyclableMemoryStreamManager so that the application can use its own instance of RecyclableMemoryStreamManager in your library.

**Comment by Sicos1977** [comment]
The reason why it is included is because there was no package for both .net standard 2.0 and .net 4.5

**Comment by Sicos1977** [comment]
I forgot to update the namespaces, done that now. This should fix the conflict you have. Just get version 3.12.0 from nuget.

**Comment by patrik-pis** [comment]
I may not understand this, but there is a RecyclableMemoryStream package for .NET Standard 2.0 and .NET 4.5.

https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/

**Comment by Sicos1977** [comment]
I just released a new version, this uses the nuget package instead of adding to code to msgreader base. Thanks for pointing this out to  me, for some weird reason there was a bug in my project file and that was the reason that I could not use the nuget package. This is now fixed
