### ISSUE TITLE
Categories property is always null

### ISSUE THREAD

**Issue by GrahamHaigh** [Sicos1977/MSGReader#256]
**Describe the bug**
Categories being returned as null

**To Reproduce**
1. Create an new outlook msg and assign a category
2. read the msg file in to msgreader and check the categories property

**Expected behavior**
When a non-null category list (when categories is know not to be empty)

**Comment by Sicos1977** [comment]
Fixed in commit https://github.com/Sicos1977/MSGReader/commit/95c1e23ed357d10e118f76af898983d4fa695f45
