### ISSUE TITLE
Question/Suggestion - Adding Outlook-Journalentry Support?

### ISSUE THREAD

**Issue by mhuellwegen** [Sicos1977/MSGReader#261]
Please can you think about also adding outlook journalentry support as well,
since Journalentries are also .msg files when drag&drop them onto the desktop?

In C# i would then expect/look for additionals MessageTypes like

  outlookMessage.Type == MessageType.JournalentryPhonecall;
  outlookMessage.Type == MessageType.JournalentryUnknown;

and some other things necessary to handle journalentries in its best.

Outlook's Journal can be opend by pressing Strg+8 for example.

Btw: You and your team had done great job, many thanx!!

**Comment by Sicos1977** [comment]
Support added in nuget package 4.3.0
