### ISSUE TITLE
Invalid characters in msg body

### ISSUE THREAD

**Issue by pgarbo** [Sicos1977/MSGReader#262]
For some msg files we have invalid (mostly Chinese) characters in HtmlBody/RtfBody/BodyText, where the same file opened in Outlook is fine. We are using latest MsgReader 3.12.2. The older version we used 3.7.3 works fine.

Code snippet:
using var msg = new Storage.Message(filePath);

After reading the file, we are seeing these chinese characters in debug:
![image](https://user-images.githubusercontent.com/16103019/111169191-a4b95800-859a-11eb-91bc-e3b342a59661.png)

 - OS: Win10
 - MsgReader version: 3.12.2 
 - .Net version: Microsoft.NETCore.App 5.0.4

Did you see this issue before? It is not for every .msg file, happens for some of them only.

**Comment by Sicos1977** [comment]
Can you sent me one of the files that is giving this issue? If so then please zip it before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Almost looks like some kind of encoding issue to me

**Comment by pgarbo** [comment]
Sent to  ***@***.***

Pawel

**Comment by Sicos1977** [comment]
Fix in this commit cdade3b027ec1895443945d1041829263901c462 , also released a new nunget package with this fix. Just update to the latest version
