### ISSUE TITLE
MessageType.Appointment ... does not include Appointment data

### ISSUE THREAD

**Issue by mhuellwegen** [Sicos1977/MSGReader#263]
Message.Type == MessageType.Appointment ... does not include Appointment data

"Appointment": {
		"Location": null,
		"Start": null,
		"End": null,
		"AllAttendees": null,
		"ToAttendees": null,
		"CcAttendees": null,
		"NotAllowPropose": null,
		"UnsendableRecipients": null,
		"RecurrenceType": -1,
		"RecurrenceTypeText": "(Keine)",
		"RecurrencePattern": null,
		"ClientIntent": null,
		"ClientIntentText": null,
		"FileAccess": 0,
		...
}

**Comment by Sicos1977** [comment]
Can you post the file that is giving this problem?

**Comment by Mokashaa** [comment]
I have the same problem parsing mails with appointment . I'm trying to parse the following mail
https://drive.google.com/file/d/13FKrIHjQn_nk66kKkxKd5z5NZKH5m1mR/view?usp=sharing
but the output doesn't contain the appointment data

**Comment by Sicos1977** [comment]
I'll try to look in to it comming week, I was to busy with work last week.

**Comment by Sicos1977** [comment]
@Mokashaa : What are you missing. The message seems fine to me

![image](https://user-images.githubusercontent.com/6692947/113186865-75703f80-9258-11eb-855d-b397197db8ed.png)

**Comment by Mokashaa** [comment]
the appointment data is missing , the start time and end time and the appointment location is NULL .
All the following parameters are NULL:

- Message.Appoinment.End 
- Message.appointment.start
- Message.Appoinment.Location

**Comment by Sicos1977** [comment]
Fixed in the latest nuget package

**Comment by mhuellwegen** [comment]
Many thx for the fix and happy easter.

**Comment by Sicos1977** [comment]
Youre welcome and also happy easter.
