### ISSUE TITLE
Linking error Xamarin.iOS

### ISSUE THREAD

**Issue by jaspervanmegroot** [Sicos1977/MSGReader#265]
Hallo Kees,

Ik doe het even in het Nederlands want jij bent ook Nederlands. Ik gebruik deze package voor Xamarin.iOS en ik krijg nu een linking error in een release build. Het heeft altijd wel gewerkt met versie 3.9.4 van de package alleen kan ook niet meer downgraden helaas. Heb jij een idee?

![image](https://user-images.githubusercontent.com/19607572/113823588-1db56500-977f-11eb-9819-c62b77690129.png)

**Comment by Sicos1977** [comment]
Nee ik heb even geen idee en tussen versie 3.9.4 en de huidige versie is eigenlijk niks bijzonders aangepast wat dit zou kunnen veroorzaken.

**Comment by jaspervanmegroot** [comment]
Heb jij misschien nog een dll van de versie 3.9.4?

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/MSGReader/3.9.4

**Comment by Sicos1977** [comment]
Altijd leuk om te zien dat er ook Nederlanders zijn die MSGReader gebruiken :-)

**Comment by jaspervanmegroot** [comment]
Thanks! Haha ja zeker, super handige package! :)

**Comment by jaspervanmegroot** [comment]
Hmm de downgrade was toch niet de oplossing. Dan is het denk ik een combinatie van jou package met een andere alleen heb echt geen idee wat...

**Comment by Sicos1977** [comment]
Dat is soms het lot van de ontwikkelaar :-) ... zoeken naar dat foute puntje :-)

**Comment by Sicos1977** [comment]
Voor wat voor tool is het eigenlijk... natuurlijk iets met mail

**Comment by jaspervanmegroot** [comment]
Haha jaa is lastig idd. Ik denk dat ik dan het omzetten van een msg naar eml moet verplaatsen naar de achterkant. 
Ik heb een app gemaakt waarbij klanten verzonden mails kunnen inzien en jou package vertaalt de EML/MSG in een bruikbare object 👍
