### ISSUE TITLE
problem with rtf emails 

### ISSUE THREAD

**Issue by Mokashaa** [Sicos1977/MSGReader#266]
**Describe the bug**
the bodyHtml and bodyRtf elements are not correct when parsing the following email message , this problem arises in some rtf emails .given a sample mail that produces this problem [https://drive.google.com/file/d/1II9btzZhuzlfVytyMPMMPb3RCjZtGH_L/view?usp=sharing](https://drive.google.com/file/d/1II9btzZhuzlfVytyMPMMPb3RCjZtGH_L/view?usp=sharing)

**To Reproduce**
1. reply on email and then change the text format (if the original mail is in html format , reply to this email and change format to rtf )

**Comment by Sicos1977** [comment]
I use RtfPipe to convert pure RTF to HTML. The conversion goes wrong in this component so you need to make an issue overthere

https://github.com/erdomke/RtfPipe
