### ISSUE TITLE
MAPI property has an unsupported type and can not be retrieved

### ISSUE THREAD

**Issue by tester1a2b** [Sicos1977/MSGReader#267]
Concerning the closed issue #259:

Version 3.12.4:
A lot of contact MSG files are causing the error 'MAPI property has an unsupported type and can not be retrieved' when trying to get a property from the contact.

In version 3.12.3 the problem does not occur: 
There I'm getting all the properties of the contact, except the email address - in this version the email properties are always empty!

I have attached an example msg file, which is causing the issue!
[testcontact.zip](https://github.com/Sicos1977/MSGReader/files/6325117/testcontact.zip)

Please help! Thank you!

**Comment by Sicos1977** [comment]
I've added support for PT_MV_LONG properties in version 4.0

**Comment by tester1a2b** [comment]
Great, thank you very much!
