### ISSUE TITLE
Unsupported IPM.Note (iManage)

### ISSUE THREAD

**Issue by nitrotm** [Sicos1977/MSGReader#268]
**Describe the bug**
We came across some msg containing a message type equal to `IPM.Note.WorkSite.Ems.Filed`, `IPM.Note.WorkSite.Ems.Queued` or `IPM.Note.WorkSite.Ems.Filed.Re` which is an alias for email format used by iManage.

**Expected behavior**
It should be parsed as an email.

**Additional context**
Would it make sense to create aliases such as 'IPM.Note.*' is considered an email convertible to HTML + attachments ? It seems that 3rd party providers are extending the message type to indicate some processing state (such as 'filed' in this case).

**Comment by nitrotm** [comment]
I found the following MS documentation mentioning potential mappings:

https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/183b7080-abbe-4b25-bb5c-160397282de8

It seems in particular that `IPM.Note.Mobile.SMS` or `IPM.Note.Mobile.MMS` will not be typical email format. Do you think it could be possible to implement a fallback logic on `IPM.Note.*` not specifically handled otherwise?

**Comment by Sicos1977** [comment]
I would rather just add it as an enum and change the reader class to support it.

**Comment by Sicos1977** [comment]
Added support for the 3 tags

**Comment by nitrotm** [comment]
@Sicos1977 I see, that's great, thanks. Where did you find the documentation about what each custom type does?

We asked around about all the possible types that we might encounter and I just received this list of possible 'statuses' (checked ones are implemented by your update):

- [ ] IPM.Note.WorkSite.Ems.Error
- [x] IPM.Note.WorkSite.Ems.Filed
- [ ] IPM.Note.WorkSite.Ems.Filed.Fw
- [x] IPM.Note.WorkSite.Ems.Filed.Re
- [ ] IPM.Note.WorkSite.Ems.Fw
- [x] IPM.Note.WorkSite.Ems.Queued
- [ ] IPM.Note.WorkSite.Ems.Re
- [ ] IPM.Note.WorkSite.Ems.Sent
- [ ] IPM.Note.WorkSite.Ems.Sent.Fw
- [ ] IPM.Note.WorkSite.Ems.Sent.Re

**Comment by Sicos1977** [comment]
I just Googled around and assumed most of the MSG files are like e-mails because the types start with IPM.Note.

**Comment by Sicos1977** [comment]
Watch out a little bit with version 4.0 (do some good testing) I refactored the RTF parser that extract the HTML from the RTF and I think I got everything right but since its a major overhaul you never know.

**Comment by nitrotm** [comment]
> I just Googled around and assumed most of the MSG files are like e-mails because the types start with IPM.Note.

Yes, we got confirmation that they can be opened in Outlook without any extra plugins. So basically just type aliases.

We'll give v4 a try and let you know if we detect any issue with RTF parser. Thank you for the notice.
