### ISSUE TITLE
not able to convert sample office 365 emails- it shows them as rtf

### ISSUE THREAD

**Issue by swiftinitdotcom** [Sicos1977/MSGReader#269]
not able to convert sample office 365 emails- it shows them as rtf
[Message Center Major Change Update Notification.zip](https://github.com/Sicos1977/MSGReader/files/6341049/Message.Center.Major.Change.Update.Notification.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sicos1977** [comment]
Works fine in version 4.0.0
