### ISSUE TITLE
ArgumentException in MsgReader.dll for MSG files with voice attachments

### ISSUE THREAD

**Issue by one-eyed-willie** [Sicos1977/MSGReader#27]
An unhandled exception of type 'System.ArgumentException' occurred in MsgReader.dll

Additional information: Unknown parameter in Content-Disposition. Ask developer to fix! Parameter: VOICE

We have a request to read MSG files and store the first x characters from the body into a SQL Server table.  The MSGReader.dll works great except when a MSG file has a voicemail attachment.  Any workarounds?   we were using 1.9.6 but I tried 1.9.10 and received the same error.

**Comment by Sicos1977** [comment]
Can you send me the file that is giving this error?

**Comment by one-eyed-willie** [comment]
[Bryan Cave Logo]

Michael Zerwig
Database Administration Engineer
michael.zerwig@bryancave.com<mailto:michael.zerwig@bryancave.com>    T: +1 314 259 2629

**Comment by one-eyed-willie** [comment]
[cisco voicemail attachement.zip](https://github.com/Sicos1977/MSGReader/files/110899/cisco.voicemail.attachement.zip)

I had to zip the msg file so it would upload.

Hopefully it made it this time.

**Comment by Sicos1977** [comment]
I added support for the "IPM.Note.Custom.Cisco.Unity.Voice" MSG type (never seen these before). You can get the latest version (that supports it) from GitHub or Nuget.

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
Did it work?

**Comment by one-eyed-willie** [comment]
I am testing now and it appears to work great.

Thanks for all your help.

**Comment by Sicos1977** [comment]
Nice to hear
