### ISSUE TITLE
MsgReader.Outlook.Storage.Message.Headers is null

### ISSUE THREAD

**Issue by jedmonsanto** [Sicos1977/MSGReader#270]
i wonder why the Headers property is when reading it from MsgReader.Outlook.Storage.Message, the e-mail saved from outlook with .msg extension

**Comment by Sicos1977** [comment]
Ueh weird sentence... I asume you mean why the headers property is null when saved from Outlook?

The header property is only set when an e-mail is sent outside of the company accross the internet. When the mail stays inside the company (on the Exchange server) then the header is empty.
