### ISSUE TITLE
Strange Charters in extracted htm from outlook message

### ISSUE THREAD

**Issue by DirkMolman** [Sicos1977/MSGReader#271]
**Describe the bug**
After upgrading from an older version to 3.12.3 we are detecting strange and unexpected characters in the htm file
The occur after <LI> in the htm

**To Reproduce**
C# code

Reader reader = new Reader();
reader.SetCulture("nl-NL");
string[] files = reader.ExtractToFolder(fileName, outputfolder);

The msg file we used and the extracted htm file are in the attached zip file (centralmailttest.msg ) 
[centralmailttest.zip](https://github.com/Sicos1977/MSGReader/files/6352111/centralmailttest.zip)

**Expected behavior**
An htm file without strange characters

**Screenshots**
![FunnyChars](https://user-images.githubusercontent.com/56305818/115581141-066e8f80-a2c8-11eb-87fd-3ef0b7a6849f.png)

In the screenshot I converted the characters to HEX

**Desktop (please complete the following information):**
Windows 10
Desktop
Version 3.12.3

**Smartphone (please complete the following information):**
xxx

**Additional context**
It seems that this occurs when mails are converted from a central mailbox

**Comment by Sicos1977** [comment]
See version 4.0 this should fix this issue

**Comment by Maarten-Havinga** [comment]
Thanks a lot! This helped us out

(I am a colleague of Dirk)

**Comment by Sicos1977** [comment]
Oke geen probleem, blij dat het is opgelost :-)
