### ISSUE TITLE
Possible to parse file from HTTp request rather than a file handle?

### ISSUE THREAD

**Issue by marwalsch** [Sicos1977/MSGReader#273]
I am attempting to parse a msg file uploaded to a an ASP.NET Core Web API controller. The documentation only explains how to read the file through `System.IO.FileAccess`:

`using (var msg = new MsgReader.Outlook.Storage.Message("d:\\testfile.msg"))`

However, want to parse the date from the delivered` IFormFile.` Is there any possibility to achieve this? Maybe through an overloaded constructor?

The only option I see at the time is to save the IFormFile to the physical device and then re-open it, which is not desirable.

```
public void PostFile([FromForm] IFormFile file)
{
            System.Diagnostics.Debug.WriteLine("Receiving input...");
            if (Request.ContentType == "application/vnd. ms-outlook") {
            /***/
            }
}
```

**Comment by Sicos1977** [comment]
It will also accept a stream as input

```c#
            /// <summary>
            /// Initializes a new instance of the <see cref="Storage.Message" /> class from a <see cref="Stream" /> containing an IStorage.
            /// </summary>
            /// <param name="storageStream"> The <see cref="Stream" /> containing an IStorage. </param>
            /// <param name="fileAccess">FileAcces mode, default is Read</param>
            public Message(Stream storageStream, FileAccess fileAccess = FileAccess.Read) : base(storageStream, fileAccess) { }
```

**Comment by marwalsch** [comment]
Thanks for the rapid response.

For googlers: this would match the constructor call when receiving as an `IFormFile `as shown in the question:
`
 using (var msg = new MsgReader.Outlook.Storage.Message(file.OpenReadStream()))`
