### ISSUE TITLE
Compiler-Error NU1202: Package MsgReader 4.0.1 is not compatible with uap10.0.16299

### ISSUE THREAD

**Issue by Hurricane31337** [Sicos1977/MSGReader#275]
Since updating the imported MsgReader NuGet-Package to 4.0.1 of my Xamarin project, I can't compile the UWP project target anymore. I suspect that targeting .NET Framework Core 2.1 is the cause of this issue.

According to Microsoft Docs, I can not increase my UWP target to match this requirement, as it is still TBD by Microsoft:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Would it therefore be possible to decrease the .NET Framework Core target to 2.0 or do you have a specific reason for 2.1?

Edit:
The compiler error is as follows (for others googling the error):
Error NU1202	Package MsgReader 4.0.1 is not compatible with uap10.0.16299 (UAP,Version=v10.0.16299) / win10-x64.
Package MsgReader 4.0.1 supports:
  - net462 (.NETFramework,Version=v4.6.2)
  - netstandard2.1 (.NETStandard,Version=v2.1)	LabelMobile.UWP

**Comment by Sicos1977** [comment]
The only reason I increased it was because visual studio 2019 was complaining that. netstandard 2.0 was out of support. I'll decrease it back to 2.0. I'll try to do it this evening.

**Comment by Hurricane31337** [comment]
Very nice, thank you very much!

**Comment by Numpsy** [comment]
> 
> 
> The only reason I increased it was because visual studio 2019 was complaining that. netstandard 2.0 was out of support.

Is that complaining about ```netstandard2.0``` in MsgReader or ```netcoreapp2.0``` in the ```MsgReaderTests``` project? (.NET Core 2.0 is out of support (2.1 is the oldest supported version), but I don't think it should report that for netstandard2.0)

**Comment by Sicos1977** [comment]
I added support again for .netstandard2.0 and released a new nuget package. Can you try to see if the 4.0.2 version fixes your compile error?

![image](https://user-images.githubusercontent.com/6692947/119250794-cb030180-bba2-11eb-9cae-5046bd9b6765.png)

**Comment by Hurricane31337** [comment]
Yes, now it compiles fine again. Thanks!
