### ISSUE TITLE
Ability to share RecyclableMemoryStreamManager 

### ISSUE THREAD

**Issue by patrik-pis** [Sicos1977/MSGReader#276]
Please add the ability to share RecyclableMemoryStreamManager so that the application can use its own instance of RecyclableMemoryStreamManager in your library with application specific settings.

**Comment by Sicos1977** [comment]
Okey I will add it, have to make some time to implement it. Will lett you know when it is done.

**Comment by Sicos1977** [comment]
See https://github.com/Sicos1977/MSGReader/releases/tag/4.1.0

**Comment by Sicos1977** [comment]
I also released a new nuget package
