### ISSUE TITLE
Sender email address is empty

### ISSUE THREAD

**Issue by t-zalewski** [Sicos1977/MSGReader#278]
Hi,

After upgrading your dll from version 3.9 to the newest one and I see that Message.Sender.Email is empty on messages from Outlook 'Sent' folder. I have checked your repository and it seems that the commit which cause my problem is the commit: https://github.com/Sicos1977/MSGReader/commit/381ae7c3f5f23649b7de8280393f2046e101f5a2 . After this change, regex is not identifying my email properly, leaving me with empty Sender Email property. 

I will zip my sample msg file and send it on your email for further investigate. (sicos2002@hotmail.com)

**Comment by Sicos1977** [comment]
I just released a nuget package --> msgreader 4.2 that fixes this issue.
