### ISSUE TITLE
Attachment content type

### ISSUE THREAD

**Issue by IB38** [Sicos1977/MSGReader#289]
Hi there,

Is there any way to get attachment content type?
MsgReader.Outlook.Storage.Attachment class doesn't have any related properties or methods, unless im missing something.

**Comment by Sicos1977** [comment]
ContentType is normally not a property that is present in an Attachment. Mostly the tags in the screenshot below are added in an MSG file.

![image](https://user-images.githubusercontent.com/6692947/153598060-ecbb5028-ca4c-4ab8-870f-452db9278eeb.png)

**Comment by Sicos1977** [comment]
I added a mimetype property to the attachment class --> https://github.com/Sicos1977/MSGReader/releases/tag/4.3.2

Should be available on nuget in a few minutes.

**Comment by IB38** [comment]
Excellent, exactly what i needed, thank you.

**Comment by Sicos1977** [comment]
Just curious, for what are you using MSGReader?

**Comment by IB38** [comment]
For parcing of msg attachments when using mail as input in data processing system.
