### ISSUE TITLE
Can't load message when embedded attachment/attachments are incorect

### ISSUE THREAD

**Issue by orastarter** [Sicos1977/MSGReader#29]
Hello,
If message contains incorrect base64 of embedded attachments it could be loaded without body, but i think it is much better to add option to load message with ignore load bad embedded attachment.
Thank you

**Comment by Sicos1977** [comment]
Can you send me the file that is giving you this problem. 


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: orastarter <notifications@github.com> 
Datum: 16-03-2016  22:04  (GMT+01:00) 
Aan: Sicos1977/MSGReader <MSGReader@noreply.github.com> 
Onderwerp: [MSGReader] Can't load message when embedded attachment/attachments
  are incorect (#29) 

Hello,

If message contains incorrect base64 of embedded attachments it could be loaded without body, but i think it is much better to add option to load message with ignore load bad embedded attachment.

Thank you

**Comment by orastarter** [comment]
Morning:)
Please check this file - https://drive.google.com/file/d/0B1gFe2F9vE6FWV9scmxaRVpyajg/view?usp=sharing
When i try Message.Load - i have error with bad base64, but outlook opens it most of all correctly. If i am trying to use new Message(bytes, false) - i can load this message but without body.
I think it could be helpfull to add option to load this message but ignore problems with embedded attachments.
Thank you

**Comment by Sicos1977** [comment]
I will look into this this weekend.

**Comment by Sicos1977** [comment]
I made a fix for your issues, just download version 1.9.13

**Comment by orastarter** [comment]
Many thanks!
