### ISSUE TITLE
Weird Arabic characters appear

### ISSUE THREAD

**Issue by eitanal** [Sicos1977/MSGReader#291]
Hey, 
When reading a MSG file contains **Arabic characters**, suddenly some weird characters appears in 
strange places in the content.
I have looked for "invisible" characters which might replace, but there are non in the source template.

I updated to latest version, and it reduce the amount of characters that were added, but still not fix entire problem.

Is some one can assist what need to be done to avoid them?
Thanks!

**Comment by Sicos1977** [comment]
Can you sent me the msg file so that I can have a look to see what is going wrong? If so then please ZIP the msg file first before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
No response... closed

**Comment by eitanal** [comment]
Hey Missed the comment. will send you an example. Thanks!!

**Comment by eitanal** [comment]
Hey sorry can't send the msg file because it contains data that can't be
sent...

Tried with different lorem ipsum text but it was different and couldn't
identify the issue although it might appear...
