### ISSUE TITLE
MSG File not readable. But with Outlook

### ISSUE THREAD

**Issue by cGiesen** [Sicos1977/MSGReader#292]
**Describe the bug**
Can't read the body of the attached MSF-File. The rest looks fine.
Outlook have no problem. Normaly, when I save the mail via Outlook again, every think is fine. But not here.

**To Reproduce**
Just read the Mail wit MsgReader and look for teh body propperties.
[Tempo.zip](https://github.com/Sicos1977/MSGReader/files/8339031/Tempo.zip)

I have now idea,

**Comment by Sicos1977** [comment]
Fixed in the latest version
