### ISSUE TITLE
4.4.1 gives errors on 4.8 framework

### ISSUE THREAD

**Issue by clabough** [Sicos1977/MSGReader#293]
warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
warning MSB3277: There was a conflict between "System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Numerics.Vectors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

warning MSB3277: Found conflicts between different versions of "System.Runtime" that could not be resolved.
warning MSB3277: There was a conflict between "System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

Found conflicts between different versions of "System.Xml.ReaderWriter" that could not be resolved.
warning MSB3277: There was a conflict between "System.Xml.ReaderWriter, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Xml.ReaderWriter, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

Found conflicts between different versions of "System.Linq" that could not be resolved.
warning MSB3277: There was a conflict between "System.Linq, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

Found conflicts between different versions of "System.Text.RegularExpressions" that could not be resolved.
warning MSB3277: There was a conflict between "System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

**Comment by Sicos1977** [comment]
This has to do with the Micrsoft MUAI library I'm using. I'll try to fix it this week.

**Comment by Sicos1977** [comment]
Fixed in the latest version. I replaced MUAI with ImageSharp
