### ISSUE TITLE
quoted-printable encoding gets broken 

### ISSUE THREAD

**Issue by TriJoe** [Sicos1977/MSGReader#295]
I don't fully know if this is a bug or not at the moment, but after trying every quoted-printable method I found online and being unable to get any of them to work fully, I realised that something was happening in MSGViewer.

I have an email where the HTML content is using the content transfer encoding of quoted-printable

```
--_000_VE1PR08MB5743BA96566BD5163C527BD9CA129VE1PR08MB5743eurp_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:x=3D"urn:schemas-microsoft-com:office:excel" xmlns:m=3D"http://schema=
s.microsoft.com/office/2004/12/omml" xmlns=3D"http://www.w3.org/TR/REC-html=
40">
```

Every 76th character has a `=` character to signify line continuation.

MSGViewer seems to be doing some reformatting of the HTMLBody which breaks the encoding and it is unable to be decoded. Interestingly all the = signs end up at the start of the lines instead of the end. 

```
=    <tbody>
=        <tr>
=            <td valign="bottom" style="width: 70%; font-family: Arial; =font-size: 10pt; white-space: nowrap; text-align: left;">
```

Is MSGReader doing something to the email body to break the encoding?

**Comment by TriJoe** [comment]
I can't see a way to fix this as it seems to use Outlook components and the issue appears to be there. 

Surprised others haven't hit this same issue, it breaks so many html emails.

**Comment by Sicos1977** [comment]
Can you sent me the email that is giving the problem so that I can have a look? If so then please ZIP the email before sending it to sicos2002@hotmail.com

**Comment by TriJoe** [comment]
I will need to modify to remove a lot of the content as all the examples I have are ones clients have forwarded to me. Bare with me.

**Comment by Sicos1977** [comment]
Are you using MSGViewer as a substitute for the lack of Outlook at your client?

**Comment by Sicos1977** [comment]
No response .... closed

**Comment by TriJoe** [comment]
After spending days on this, it's the EOL type of the EML file that was the problem. Windows (CR LF) worked fine, but files using Unix (LF) had the issue. 

Spent far too long to find this out!
