### ISSUE TITLE
Images inside .eml files are not getting added in html properly

### ISSUE THREAD

**Issue by dhrupdubey** [Sicos1977/MSGReader#296]
**Describe the bug**
Images inside .eml files are not getting added in html properly

**To Reproduce**
1. Create a new mail with image inside it not attached format
2. Create a .eml file from the above email
3. Now try to get the html from above file
4. Now put this html in .html file and check image is loaded properly or not

**Expected behavior**
Image should be shown properly in html 

**Screenshots**
Created a email adding following image
![image](https://user-images.githubusercontent.com/47987935/160422021-0ad276ae-b6cd-4fd0-8d3b-69e89837ca3a.png)

this is the result in html:
![image](https://user-images.githubusercontent.com/47987935/160421950-8634de44-880a-417c-91e0-34324e7f5e9a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TriJoe** [comment]
This is expected. You will need to save the attachments first, then modify the html to point to the local file. 

I'm using this method:

```
if (message.Attachments != null) //if has attachments
{
    foreach (var attachment in message.Attachments)
    {
        if (attachment.IsInline)
        {
            string attachmentPath = Path.GetTempPath() + parentUniqueId + attachment.FileName;
            Debug.WriteLine("Inline Attachment: " + attachment.FileName + ", " + attachmentPath);

            var attachmentFileInfo = new FileInfo(attachmentPath);
            attachment.Save(attachmentFileInfo);
            inlineAttachments.Add(new InlineAttachments(attachment.FileName, attachmentPath, attachment.ContentId));
        }
    }
}
```

And then using this to look for the CID string in HTML and replace it with the new local path

```
foreach (InlineAttachments inline in inlineAttachments)
{
    Debug.WriteLine("Looking for: " + "cid:" + inline.Cid);
    body = body.Replace("cid:" + inline.Cid, inline.Path);
}
```

**Comment by dhrupdubey** [comment]
@TriJoe 
Thanks a lot for the code, it is working now.

Closing this as this is not a bug, @TriJoe has provided solution for it.
