### ISSUE TITLE
.heic attachments in .msg are shown as IsInline=true

### ISSUE THREAD

**Issue by kaljak** [Sicos1977/MSGReader#297]
**Describe the bug**
If you extract a the .heic attachment of a .msg file .IsInline is true.

**To Reproduce**
                    using (var msg = new Storage.Message(memory))
                    {
                        foreach (var attachment in msg.Attachments)
                        {
                            if (attachment.GetType() == typeof(Storage.Attachment) && !((Storage.Attachment)attachment).IsInline) {
                                //code is not hit with .heic attachment
                            }

**Expected behavior**
.heic attachments should be shown as IsInline = false

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 4.1.0

**Additional context**
Sorry, I can't upload the .msg file to reproduce as it is confidential

**Comment by Sicos1977** [comment]
Sorry without an example I can't fix it. I need something to reproduce the error.
