### ISSUE TITLE
DeleteAttachment for eml messages

### ISSUE THREAD

**Issue by fivestrokes** [Sicos1977/MSGReader#299]
**Describe the bug**
Removal of attachments from eml message file not supported?

**To Reproduce**
1. Load eml file using library (`var eml = MsgReader.Mime.Message.Load(fileInfo);`)
2. Currently an `eml.DeleteAttachment(attachment)` is not implemented (available for msg files - `msg.DeleteAttachment(attachment)`)
3. Current approach: iterate MessageParts to remove attachment items (see code below)
4. Save eml to disk (`eml.Save(fileInfo)`). The attachments have not been removed

**Remove attachment code**

```
var attachmentsFoundAndRemoved = false;

foreach (var attachment in eml.MessagePart.MessageParts.ToList())
{
	if (attachment.IsAttachment)
	{
		eml.MessagePart.MessageParts.Remove(attachment);

		attachmentsFoundAndRemoved = true;
	}
}
if (attachmentsRemoved)
{
	eml.Save(fileInfo);
}
```

The reason the attachments are not removed is that the `eml.Attachments` object is implemented as a `ReadOnlyCollection`. Removing the attachments from the `eml.MessagePart.MessageParts` collection does not seem to produce the desired effect.

**Expected behavior**
Ideal would be a similar implementation (add missing method `eml.DeleteAttachment`) that has been implemented for msg files, e.g.:

```
foreach (var attachment in eml.Attachments.ToList())
{
	eml.DeleteAttachment(attachment);

	attachmentsFoundAndRemoved = true;
}
if (attachmentsRemoved)
{
	eml.Save(fileInfo);
}
```
Or to have the `eml.Attachments` collection reflect the changes made to the `eml.MessagePart.MessageParts` collection.

Thank you kindly for this very useful library.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sicos1977** [comment]
At the moment there is no support for removing attachments from EML files. If you need this then use MimeKit --> https://github.com/jstedfast/MimeKit. This library is much better in doing things with EML like removing attachmens.

**Comment by fivestrokes** [comment]
Thanks so much. I’ll try it out.
