### ISSUE TITLE
Can't read Delivery date

### ISSUE THREAD

**Issue by orastarter** [Sicos1977/MSGReader#30]
Hello! When i try load message https://drive.google.com/file/d/0B1gFe2F9vE6FTDhRRXVFbmsyTzQ/view?usp=sharing it returns message with Date delivery = 01.01.0001, but if you check UnknownHeaders you will find Delivery-date. 
Do you know why?
Thank you

**Comment by Sicos1977** [comment]
The reason why it is in the unknown headers is because it is not part of a normal MIME message.

See this --> https://tools.ietf.org/html/rfc4021#section-2.1.48

I clearly says... not for general use.

**Comment by orastarter** [comment]
Sicos1977, i see, i am sorry, but it is realy strange. Some times you read Delivery-date as DateSent but sometimes no. If you will take another email from issue #29 you will see that the same header loaded correctly. 
Thank you

**Comment by Sicos1977** [comment]
It works because in the BadBase64.eml file there is a header called Date that is parsed

Date: Wed, 24 Feb 2016 20:46:03 +0000

**Comment by orastarter** [comment]
Ahh, sorry. I see.

**Comment by Sicos1977** [comment]
I made a fix for your issues, just download version 1.9.13
