### ISSUE TITLE
Memory not clear after reading a mail box (MSG) file

### ISSUE THREAD

**Issue by sudhirsharmat** [Sicos1977/MSGReader#302]
Hi, 

I have tried loading 14 MB MSG file with MSG Reader and once reading the file and setting Message object to null, the memory is not cleared. It's hard to run on multiple objects as after certain number of objects, it will start giving the exception OutOfMemory Exception. You were using MemoryStream class for object iteration and byte[] are continuously copied from function to next, while its reference can be iterated with the positions of Current and End position can be passed directly. I have attached the code for your reference.

 
[StreamUtility.zip](https://github.com/Sicos1977/MSGReader/files/8939749/StreamUtility.zip)

**Comment by Sicos1977** [comment]
Can you show me where and how you used the new methods with the references?

**Comment by Sicos1977** [comment]
No response ... closed
