### ISSUE TITLE
MsgReader.ExtractToFolder cannot open opened files

### ISSUE THREAD

**Issue by khaled-be** [Sicos1977/MSGReader#303]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khaled-be** [comment]
In the MsgReader.cs class(line 399), the file is opened like this : 
  using (var stream = File.Open(inputFile, FileMode.Open, FileAccess.Read))
But that will work only with closed document, is it possible to add the file share option like this : 
using (var stream = File.Open(inputFile, FileMode.Open, FileAccess.Read, FileShare.Read))

**Comment by Sicos1977** [comment]
Both implemented
