### ISSUE TITLE
Unable to parse signed email

### ISSUE THREAD

**Issue by jhan-zaib** [Sicos1977/MSGReader#304]
[signed-messages.zip](https://github.com/Sicos1977/MSGReader/files/9035256/signed-messages.zip)
There are particular emails where MsgReader unable to parse. See attached both sample emails, one is parse-able and second is not. 

Note: Both messages are signed by same sender from Thunderbird and we are parsing inside an Outlook VSTO addin

I have used particular code snippet to parse message

`string emailPath = @"C:\signed-by-ms-admin-valid.msg";
MsgReader.Mime.Message mailMessage = new MsgReader.Mime.Message(File.ReadAllBytes(emailPath), true);`

See attached sample messages

1. **signed-by-ms-admin-valid.msg** is parsing correctly. Above code extracting signer's certificate under `SignedCertificate` attribute
2. **signed-by-ms-admin-tampered.msg** is failed to parse by above code snippet.

**Expected behavior**
Ideally both kind of messages should be parsed.

**Desktop (please complete the following information):**
 - OS: Windows 10, 11
 - Outlook 2019, O365, 2021

**Comment by jhan-zaib** [comment]
@Sicos1977 any update?

**Comment by Sicos1977** [comment]
@jhan-zaib Sorry about the delay but I'm a little bit busy with another problem, I will try to look into your problem when I'm done with my current work.

**Comment by Sicos1977** [comment]
Also you cant use the Mime Message reader for MSG files.. you need to do it like this.

```
using (var msg = new MsgReader.Outlook.Storage.Message("d:\\testfile.msg"))
{
        var from = msg.Sender;
        var sentOn = msg.SentOn;
        var recipientsTo = msg.GetEmailRecipients(MsgReader.Outlook.RecipientType.To, false, false);
        var recipientsCc = msg.GetEmailRecipients(MsgReader.Outlook.RecipientType.Cc, false, false);
        var subject = msg.Subject;
        var htmlBody = msg.BodyHtml;
        // etc...
}
```

**Comment by jhan-zaib** [comment]
Hi @Sicos1977 ,

I have used your mentioned way of reading messages, but this fails to fill SignedCertificate or SignatureIsValid properties. So let me know how we can fetch these properties while reading msg files.

Thanks
Jhan Zaib

**Comment by Sicos1977** [comment]
I tried both you messages but can open them without any problems

**Comment by Sicos1977** [comment]
I changed something in the latest nuget package so that the signed information is also reflected to the message object
