### ISSUE TITLE
DeleteAttachment deletes the wrong attachment when called from a sub message

### ISSUE THREAD

**Issue by Zaldroc** [Sicos1977/MSGReader#308]
**Describe the bug**
I've got a msg file which contains a pdf file and another msg file as attachments. The sub message also contains two attachments.
If i call `DeleteAttachment` for the second attachment in the sub message, save the top level message and then open the file in Outlook, the second attachment of the top level message is gone. 
I think the error is in the following line:
https://github.com/Sicos1977/MSGReader/blob/5d563c0c699fde70218929768f08f4256af98ef3/MsgReaderCore/Outlook/Message.cs#L1807

Here the attachment is always removed from the root storage of the top level message instead of from the current message.
I tried deleting it from the current message and it seems to be working correctly, however i don't know if there are any side effects.

Also shouldn't this flag also be set for the top level message in case the attachment of a sub message is deleted and `Save` is called from the top level message?
https://github.com/Sicos1977/MSGReader/blob/5d563c0c699fde70218929768f08f4256af98ef3/MsgReaderCore/Outlook/Message.cs#L1808
It somehow works without it though, i just don't understand why.

**Comment by Zaldroc** [comment]
Is this being worked on?

**Comment by Sicos1977** [comment]
Sorry forgot this issue and at the moment I'm full with other work.

**Comment by Sicos1977** [comment]
Can you sent me the msg file and some example code about how you are trying to delete the attachment. I tried to make some test code for myself but I can't manage to reproduce the problem so I'm probably doing something else then what you are doing. Please sent to MSG file (zip if before sending) and some example code to sicos2002@hotmail.com

**Comment by kenjiuno** [comment]
Hi. I have same issue, and this is unit test for reproduction.
- Branch: https://github.com/kenjiuno/MSGReader/tree/test-308
- Commit: https://github.com/kenjiuno/MSGReader/commit/81bc68de4745c6f079113dc3cd20b664e1a98f59

The added unit test `RemoveAttachmentTests.RemoveAttachmentsFromInner` will fail in the following part.

```
                        Assert.AreEqual(3, outputMessage.Attachments.Count); // <-- Assert.AreEqual failed. Expected:<3>. Actual:<2>. 
                        Assert.AreEqual("OUTER 1.pdf", ((Storage.Attachment)outputMessage.Attachments[0]).FileName);
                        Assert.AreEqual("OUTER 2.pdf", ((Storage.Attachment)outputMessage.Attachments[1]).FileName);
                        Assert.AreEqual("Inner mail.msg", ((Storage.Message)outputMessage.Attachments[2]).FileName);
```
