### ISSUE TITLE
GDI+ not supported on macOS in .net 6

### ISSUE THREAD

**Issue by lorddev** [Sicos1977/MSGReader#309]
**Describe the bug**

I get this error when trying to get HTML body:

```
14:25:21 [ERR] (:34) Error processing file /Users/aaron/Projects/joinder/preview/data/out/ef1e512f-8d07-4c13-9eb9-e3b8f84fcd6e/ef1e512f-8d07-4c13-9eb9-e3b8f84fcd6e for email preview.  Message:  System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 0x0001): tried: 'liblibgdiplus' (no such file), '/usr/local/lib/liblibgdiplus' (no such file), '/usr/lib/liblibgdiplus' (no such file), '/Users/aaron/Projects/joinder/DASH/Joinder.Preview.Web/liblibgdiplus' (no such file)
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, String systemName)
   at System.Drawing.SystemFonts.get_DefaultFont()
   at MsgReader.Rtf.DocumentFormatInfo..ctor()
   at MsgReader.Rtf.DomDocument.LoadRtfText(String rtfText)
   at MsgReader.Outlook.Storage.Message.get_BodyHtml()
```

**To Reproduce**
create a project in .net 6
consume this library
try to extract html body

**Expected behavior**
Should not throw errors. Note that https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only says that ImageSharp or SkiaSharp should be used

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Monterey
 - Arch: Apple Silicon

**Comment by lorddev** [comment]
I'm on 3.11.0, fyi

**Comment by Sicos1977** [comment]
Just update to the latest version

**Comment by lorddev** [comment]
> Install failed (project: DocumentProcessingNode, package: MsgReader v4.4.8) Package restore failed. Rolling back package changes for 'DocumentProcessingNode'. Detected package downgrade: System.Text.Encoding.CodePages from 6.0.0 to 5.0.0. Reference the package directly from the project to select a different version. DocumentProcessingNode -> MsgReader 4.4.8 -> System.Text.Encoding.CodePages (>= 6.0.0) DocumentProcessingNode -> System.Text.Encoding.CodePages (>= 5.0.0)

**Comment by lorddev** [comment]
Thank you

**Comment by lorddev** [comment]
Do you have any recommended workarounds?

>   AvatarCreator.cs(46, 40): [CA1416] This call site is reachable on all platforms. 'Image.Size' is only supported on: 'windows'.
  AvatarCreator.cs(28, 17): [CA1416] This call site is reachable on all platforms. 'Image.Size' is only supported on: 'windows'.
  AvatarCreator.cs(55, 17): [CA1416] This call site is reachable on all platforms. 'Bitmap' is only supported on: 'windows'.
  AvatarCreator.cs(28, 37): [CA1416] This call site is reachable on all platforms. 'Image.Size' is only supported on: 'windows'.
  AvatarCreator.cs(57, 33): [CA1416] This call site is reachable on all platforms. 'Graphics.FromImage(Image)' is only supported on: 'windows'.
  AvatarCreator.cs(25, 27): [CA1416] This call site is reachable on all platforms. 'Image.FromStream(Stream)' is only supported on: 'windows'.
  AvatarCreator.cs(46, 58): [CA1416] This call site is reachable on all platforms. 'Image.Size' is only supported on: 'windows'.
  AvatarCreator.cs(49, 19): [CA1416] This call site is reachable on all platforms. 'Image.Size' is only supported on: 'windows'.
  AvatarCreator.cs(59, 57): [CA1416] This call site is reachable on all platforms. 'GraphicsUnit.Pixel' is only supported on: 'windows'.
  AvatarCreator.cs(48, 28): [CA1416] This call site is reachable on all platforms. 'Image.Size' is only supported on: 'windows'.
  AvatarCreator.cs(59, 17): [CA1416] This call site is reachable on all platforms. 'Graphics.DrawImage(Image, Rectangle, Rectangle, GraphicsUnit)' is only supported on: 'windows'.
  AvatarCreator.cs(80, 20): [CA1416] This call site is reachable on all platforms. 'Bitmap' is only supported on: 'windows'.
  AvatarCreator.cs(81, 4): [CA1416] This call site is reachable on all platforms. 'Image.Save(Stream, ImageFormat)' is only supported on: 'windows'.
  AvatarCreator.cs(73, 4): [CA1416] This call site is reachable on all platforms. 'Graphics.Clear(Color)' is only supported on: 'windows'.
  AvatarCreator.cs(81, 24): [CA1416] This call site is reachable on all platforms. 'ImageFormat.Png' is only supported on: 'windows'.
  AvatarCreator.cs(77, 5): [CA1416] This call site is reachable on all platforms. 'Graphics.DrawImage(Image, Point)' is only supported on: 'windows'.
  AvatarCreator.cs(75, 33): [CA1416] This call site is reachable on all platforms. 'Bitmap' is only supported on: 'windows'.
  AvatarCreator.cs(72, 24): [CA1416] This call site is reachable on all platforms. 'Graphics.FromImage(Image)' is only supported on: 'windows'.
  AvatarCreator.cs(69, 24): [CA1416] This call site is reachable on all platforms. 'Bitmap' is only supported on: 'windows'.
