### ISSUE TITLE
RTF body with a table conversion issue

### ISSUE THREAD

**Issue by long1000** [Sicos1977/MSGReader#312]
Hi,
I notice that the new version 4.4.11 has an issue with a email msg in RTF format and which has a table inside.
After extracting it to html, the table is distorted.
My old version 3.9.4 (with rtfpipe 1.0.0) does a better job.
Is the problem with msgreader or rtfpipe? Is it possible to use back the old rtfpipe?
A sample msg is attached.
Thanks.

Regards,
Boon
[richtext_with_table.zip](https://github.com/Sicos1977/MSGReader/files/9665435/richtext_with_table.zip)

**Comment by Sicos1977** [comment]
I'll have to check if I did break something while fixing issue #311

**Comment by Sicos1977** [comment]
And if so find out a way to make both work :-) Always nice a fix that breaks something else that was a fix for another problem :-)

**Comment by long1000** [comment]
Thanks in advance

**Comment by Sicos1977** [comment]
I checked your MSG file and it is pure RTF, the table conversion fails in RTFPipe. Since I can't fix this it is better to raise an issue in the RTFPipe repo and get it fixed overthere. Then I can update the RTFPipe assembly to fix it also in MSGReader
