### ISSUE TITLE
Null reference exception in ParseRtfText

### ISSUE THREAD

**Issue by MarcinHanczaruk** [Sicos1977/MSGReader#318]
**Describe the bug**
Accessing BodyHTML returns Null reference exception.

System.NullReferenceException: Object reference not set to an instance of an object.
    at MsgReader.Rtf.Document.ParseRtfText(String rtfText)
    at MsgReader.Outlook.Storage.Message.get_BodyHtml()

It seems to be happening when there is an RTFINLINEOBJECT at the end of the email body. Adding text below the inline attachment stops ParseRtfText from crashing.

Both BodyText and BodyRTF work and can be used to access text and rtf email body.

**To Reproduce**
Test msg file can be provided if required.

**Expected behavior**

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by Sicos1977** [comment]
Can you send me an example file? If so then please ZIP the file before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
This fixes your issue d457023a2e40542d672f15c27b04b42ba218ba4b
