### ISSUE TITLE
Codepage problems

### ISSUE THREAD

**Issue by raznet** [Sicos1977/MSGReader#32]
Hello Kees,

many thanks for your work. 
We are using your project for displaying e-mails exported from outlook in an outlook addin.
Unfortunately we got an e-mail which is not displayed correctly, can you please look at it,
my knowledge goes not far enough to fix it by myself.

Best regards
Dennis

[MSGReader issue.zip](https://github.com/Sicos1977/MSGReader/files/234055/MSGReader.issue.zip)

**Comment by Sicos1977** [comment]
Can you try out the latest code that I did check in? It should work now for Russian chars. But since I can't read that I dont't know if it is correct :-)

**Comment by raznet** [comment]
It's looking good, thank you. But now it seems that some german rtf emails are broken. I have to look more closely at it.

**Comment by Sicos1977** [comment]
Please look into it yourself first and if you can't get it working then let me know. It took me almost a whole day to figure out why the HTML de-capsulation (getting the HTML out of the RTF) was going wrong :-). It is very complex how Microsoft did make that.

**Comment by raznet** [comment]
Yes, it's really confusing :)
As far i discovered the problem now is causing by nested fonts and has nothing to do with encoding.
In ReadHtmlContent method the spanTagWritten cases are failing for nested fonts i think.

In my e-mail here, is a smiley created with windings font. Look at html result:

```
<p class=MsoNormal>
Here is some text
<span style = 'font-family:"Arial";font-size:12pt'>
more text 
<span style='font-family:Wingdings'>
</span>
J
</span>
<o:p>
</o:p>
</p>
<p class=MsoNormal>
even more text
<span style = 'font-family:"Wingdings";font-size:12pt'>
Last text block
<o:p>
</o:p>
</p>
```

![untitled](https://cloud.githubusercontent.com/assets/16225313/14882275/1c3fedd4-0d38-11e6-957e-03297762a62c.png)

Does it make sense for you?

**Comment by Sicos1977** [comment]
Can you send me the original E-mail?

 

Greetings,

Kees

 

Van: raznet [mailto:notifications@github.com] 
Verzonden: donderdag 28 april 2016 11:56
Aan: Sicos1977/MSGReader <MSGReader@noreply.github.com>
CC: Kees <magic-sessions@home.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Sicos1977/MSGReader] Codepage problems (#32)

 

Yes, it's really confusing :)
As far i discovered the problem now is causing by nested fonts and has nothing to do with encoding.
In ReadHtmlContent method the spanTagWritten cases are failing for nested fonts i think.

In my e-mail here, is a smiley created with windings font. Look at html result:

<p class=MsoNormal>
Here is some text
<span style = 'font-family:"Arial";font-size:12pt'>
more text 
<span style='font-family:Wingdings'>
</span>
J
</span>
<o:p>
</o:p>
</p>
<p class=MsoNormal>
even more text
<span style = 'font-family:"Wingdings";font-size:12pt'>
Last text block
<o:p>
</o:p>
</p>

 <https://cloud.githubusercontent.com/assets/16225313/14882275/1c3fedd4-0d38-11e6-957e-03297762a62c.png> 

Does it make sense for you?

**Comment by raznet** [comment]
No, this oneis confidential. But i found another one. Can i send it to you directly over e-mail?

**Comment by Sicos1977** [comment]
Sure.... sicos2002@hotmail.com
