### ISSUE TITLE
Cyrilic (KIO8-R) : .msg to html transformation returns garbled text for latest email

### ISSUE THREAD

**Issue by tariqgitspace** [Sicos1977/MSGReader#323]
**Describe the bug**
https://github.com/Sicos1977/MSGReader/issues/317 partially fixed broken text issue and 4.4.13 still has the issue where **top/Latest** email in the chain is still broken for Cyrilic (KIO8-R)

**To Reproduce**
    1. Perform msg to Html transformation with Cyrilic (KIO8-R).
    2. Latest email in the chain will contain garbled text.

**Expected behavior**
Text should not be garbled in html generated from .msg.

**Screenshots**

**Desktop (please complete the following information):**
OS - Windows 11
Browser - Edge, Chrome, etc
Version- All

**Smartphone (please complete the following information):**
Device: N/A
OS - N/A
Browser- N/A
Version - N/A

Additional context

**Comment by Sicos1977** [comment]
I have some test failes that you did sent my by mail but they all look okey to me.

**Comment by Sicos1977** [comment]
There is a new MSGReader 5.1 version with a lott of encoding issues fixed in it. It has a completely rewritten RTF to HTML de-encapsulator
