### ISSUE TITLE
BodyHtml returns incorrect result

### ISSUE THREAD

**Issue by nannongrousong** [Sicos1977/MSGReader#324]
**Describe the bug**
After reading Outlook MSG files, the result of BodyHtml seems to be a little problem, it has lots of "\r\n".

**To Reproduce**
1. Read the test.msg(Shared over email) 
2. The result of BodyHtml returns:
```
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns="http://www.w3.org/TR/REC-html40"><head>
<meta name=ProgId content=Word1.Document>
<style><!--
p.MsoNormal, div.MsoNormal
	{margin:0cm;}
--></style></head><body><div><p class=MsoNormal>1

</p><p class=MsoNormal></p><p class=MsoNormal>2

</p></div></body></html>
```

**Expected behavior**
It can return 
```
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns="http://www.w3.org/TR/REC-html40"><head>
<meta name=ProgId content=Word1.Document>
<style><!--
p.MsoNormal, div.MsoNormal
	{margin:0cm;}
--></style></head><body><div><p class=MsoNormal>1</p><p class=MsoNormal></p><p class=MsoNormal>2</p></div></body></html>
```

**Screenshots**
Shared over email

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version ALL

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by Sicos1977** [comment]
I really don't see anything that is going wrong when getting the HTML from the RTF that is inside the MSG file.
