### ISSUE TITLE
long attachment name

### ISSUE THREAD

**Issue by cwapenhans** [Sicos1977/MSGReader#326]
We open an mail and get "Unknown parameter in Content-Disposition. Ask developer to fix! Parameter: FILENAME1

In a e-mail:

Content-Disposition: attachment;
    filename*1*=BBBBBBBBBBBBBBBBBBB_2021.pdf;
    filename*0*="utf-8''AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

see RFC 2231

Version 4.4.16

**Comment by Sicos1977** [comment]
Can you please sent me this email? If so then please ZIP it before sending it to sicos2002@hotmail.com

**Comment by cwapenhans** [comment]
I've send a test mail

**Comment by Sicos1977** [comment]
I just released a new nuget package
