### ISSUE TITLE
Inline images seem to not be treated as such

### ISSUE THREAD

**Issue by melchor629** [Sicos1977/MSGReader#327]
**Describe the bug**
Inline images are not treated as inline from version 4.4.6.

**To Reproduce**
1. Generate an `.msg` with an inline image, with HTML inside.

**Expected behavior**
The attachment of the inline image is treated as inline.

**Additional context**
It seems that between [4.4.5 and 4.4.6](https://github.com/Sicos1977/MSGReader/compare/4.4.5...4.4.6) something has changed that now the inline images are not treated as such. If I use 4.4.5, everything works fine. Upgrading to 4.4.6 or newer, it stops working.

In the example I've got, the HTML contains the following image:
![image](https://user-images.githubusercontent.com/1056963/222157515-23288156-a4d0-4d2b-bd28-5710ea7adcee.png)

But then, the attachment has the `IsInline` set to `false`:
![image](https://user-images.githubusercontent.com/1056963/222158631-6136113f-4e35-46fe-8fd0-694c153b4b90.png)

Maybe related PR I've found: https://github.com/Sicos1977/MSGReader/pull/307

**Comment by Cyril12740** [comment]
I have changed companies and I no longer use your package to read emails.

Do you need an email reproducing my error or that of melchor629?

**Comment by Sicos1977** [comment]
I need one from @melchor629

**Comment by melchor629** [comment]
Hello, sorry for the slow response :(

I've built a small email sample and small code to reproduce. Hope it helps:

```c#
using MsgReader.Outlook;

System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
using var stream = File.OpenRead(@"..\..\test.msg");
using Storage.Message msg = new Storage.Message(stream);
foreach (var attachment in msg.Attachments)
{
    if (attachment is Storage.Attachment attachmentCasted)
    {
        Console.WriteLine($"{attachmentCasted.FileName}: IsInline={attachmentCasted.IsInline} Hidden={attachmentCasted.Hidden}");
    }
}
```

[test.msg.zip](https://github.com/Sicos1977/MSGReader/files/10959305/test.zip)

Results with 4.4.5:
![image](https://user-images.githubusercontent.com/1056963/224759458-057cd510-4c7a-4312-910e-6e12f5255e6a.png)

Results with 4.4.6 (same as in 4.4.16):
![image](https://user-images.githubusercontent.com/1056963/224759662-c946fd3c-ec8c-41db-bdef-b148603e28bb.png)

**Comment by Sicos1977** [comment]
Seems to be working fine now

![image](https://user-images.githubusercontent.com/6692947/227772705-d9137d58-5595-44d2-a1be-ebd4b7fcbdc6.png)

**Comment by melchor629** [comment]
Cool, thanks for your work :)

**Comment by M8anu** [comment]
This thread is awesome seal of approval content, bending

**Comment by Sicos1977** [comment]
?

**Comment by zeOxx** [comment]
@Sicos1977 sorry to resurrect this, but it seems like this issue has returned.
this is from 3.4.1 (yes, this is an old version...)
![image](https://github.com/Sicos1977/MSGReader/assets/2211514/2ef53aab-8a90-4523-92f5-562c6e9aff42)
this is from 5.2.2
![image](https://github.com/Sicos1977/MSGReader/assets/2211514/3b5c6fd3-8893-4e71-9a67-e1f8b85dd7ec)

the email i tested with:
[image test.msg.zip](https://github.com/Sicos1977/MSGReader/files/11564084/image.test.msg.zip)
