### ISSUE TITLE
Problem reading an Outlook file saved in ANSI

### ISSUE THREAD

**Issue by happybald** [Sicos1977/MSGReader#328]
**Describe the bug**
Problem reading an Outlook file saved in ANSI

**To Reproduce**
Open any outlook email file with a meeting that will contain special characters such as "öäéàèü".
2. Save it as Outlook Message Format (*.msg) (Not Unicode!)
3. Get it as base64 -> then, Convert.FromBase64String and MemoryStream -> Storage.Message(memoryStream).
4. Have ������ in the name after reading.

**How I get base64 in TypeScript**
```
public toBase64 = (file: File) => new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result!.toString()
      .replace('data:', '')
      .replace(/^.+,/, ''))
    reader.onerror = error => reject(error);
  });
```

**How I read on C# side**
```
var bytes = Convert.FromBase64String(base64);
using var memoryStream = new MemoryStream(bytes);
using var msg = new Storage.Message(memoryStream);
```

**Expected behavior**
Reads from ANSI need to be fixed

**Screenshots**
![image](https://user-images.githubusercontent.com/45720171/222473062-7f60ab73-3ddf-481a-adbb-ad4ef81f0441.png)
![image](https://user-images.githubusercontent.com/45720171/222473141-a3d8bc0d-e7ec-4774-9a5a-79a90e812ebe.png)

**Desktop (please complete the following information):**
Processor AMD Ryzen 7 5800X 8-Core Processor 
Installed RAM	32.0 GB
System type 64-bit operating system, x64-based processor
Windows
Edition Windows 11 Pro N
Version 22H2
OS build 22621.1265
Experience Windows Feature Experience Pack 1000.22638.1000.0
Google Chrome
Version 110.0.5481.178 (Official Build) (64-bit)
Locale: LCID 1033, en-US

**Additional context**
.NET 6, C#10, MsgReqder 4.4.16

Outlook msg file:
[öäéàèü Test chars.zip](https://github.com/Sicos1977/MSGReader/files/10872953/oaeaeu.Test.chars.zip)

**Comment by mastercs999** [comment]
I know this issue since we work together. Base64 encoding during transfer doesn't play any role. The failing code can be simplified to this:
`using var msg = new Storage.Message(@"c:\000-Temp\öäéàèü Test chars.msg");
Console.WriteLine(msg.Subject);`

Prints: `?????? Test chars`

**Comment by Sicos1977** [comment]
Can you sent me this msg file? If so then please ZIP it before sending it to sicos2002@hotmail.com

**Comment by mastercs999** [comment]
The link is in the end of the issue description. But I also sent it to your emails. Thank you :)

**Comment by SeRgI1982** [comment]
Is there any way to workaround it ? I have an email with a pound sign in a Subject and also I experience '?' while convert such .msg file

**Comment by SeRgI1982** [comment]
> Is there any way to workaround it ? I have an email with a pound sign in a Subject and also I experience '?' while convert such .msg file

In my case, probably file was encoded differently.
I have started to play with fork of your repo and I have found that when I change to something like this:

```
case PropertyType.PT_STRING8:
                return GetStreamAsString(containerName, Encoding.UTF7);
```

in my Subject pound sign is visible correctly. 

Of course, it is not a solution - only a hint.

I don't know how to detect it and provide correct encoding always - no matter how .msg file was saved.

**Comment by Sicos1977** [comment]
Normally an MSG file can be encoded in 2 ways; ANSI or UNICODE. If the settings is UNICODE then every string inside the MSG files has to be used as unicode. If for whatever reason somebody makes a MSG files with mixed encodings in it then is is very hard to figure out if the retrieved string is correct.

Can you sent me the MSG file that is having this issue so that I can look into it to see if there is some way in detecting the encoding for the subject? If so then please ZIP the MSG file first before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Never mind I see that an example is attached in the first post.

**Comment by Sicos1977** [comment]
Is this the problem?

![image](https://user-images.githubusercontent.com/6692947/227578578-39b0d777-bdba-4be0-b3d1-6c88e4046e7d.png)

**Comment by kenjiuno** [comment]
> Is this the problem?

Although I'm not OP, it is right.

We are just developers.
This kind of problem will occur when we are going to apply msgreader against client's data through built products or software.

And I agree that detecting ANSI encoding cannot be resolved by reasonable way due to technical difficulty.

The possible way will be to open `System.Text.Encoding` to developers so that they can select their own encoding in their responsibility.

**Comment by mastercs999** [comment]
In our case the client drag and drops a meeting/email from outlook to the web solution. That creates a file in this format. We have no control over it.

**Comment by Sicos1977** [comment]
In an MSG file there is a parameter that says in what format the streams are stored. If that parameters says ansii then you have to read all the streams as 1 byte encoded. There is just no way to fix the encoding issue.

**Comment by Sicos1977** [comment]
I'm closing this issue because there is no propper way to detect the stream encodings if the correct enooding is not set.
