### ISSUE TITLE
[Japanese Text] .msg to html transformation returns broken text

### ISSUE THREAD

**Issue by tariqgitspace** [Sicos1977/MSGReader#329]
Describe the bug
https://github.com/Sicos1977/MSGReader/issues/317 partially fixed broken text issue and 4.4.13 still has the issue where top/Latest email in the chain is still broken sometimes for Japanese text.

To Reproduce

Perform msg to Html transformation with Japanese or Korean text.
Latest email in the chain will contain garbled text.
Test file shared over email.
Expected behavior
Text should not be garbled in html generated from .msg.

Screenshots
Shared over email

Desktop (please complete the following information):
OS - Windows 11
Browser - Edge, Chrome, etc
Version- All

Smartphone (please complete the following information):
Device: N/A
OS - N/A
Browser- N/A
Version - N/A

Additional context

**Comment by Sicos1977** [comment]
Is this issue still about this message... if so ... I don't see anything wrong with it. 

![image](https://user-images.githubusercontent.com/6692947/223794980-fd91f6d6-a57f-49f5-8b84-3c998b5762eb.png)

**Comment by tariqgitspace** [comment]
Hello,

Thanks for looking into it.

Snap above is the first message of the email chain. Issue is seen for the latest email as can be seen below. I have shared original email as well as the erroneous transformed html over email (sent on 03/03). Please let know if any other information required.

![image](https://user-images.githubusercontent.com/6762447/223805883-5320e571-a588-4613-9f37-9fe7a9f606cf.png)

**Comment by Sicos1977** [comment]
I really don't see anything broken in the complete e-mail. Are you using the latest version??

Left is the output of MSGReader and on the right is Outlook.... looks the same to me.

![image](https://user-images.githubusercontent.com/6692947/224103847-d2658561-a8c5-4417-937b-538afe99531d.png)

**Comment by tariqgitspace** [comment]
Hello,
I see that its fixed in latest version 4.4.15 and can be closed. 
This was reported last year when available version was 4.4.13 and 4.4.13 has issue.

Thank you !!
