### ISSUE TITLE
Compressed-RTF CRC32 failed Error

### ISSUE THREAD

**Issue by pmelisi** [Sicos1977/MSGReader#33]
Hello Kees,

We are having issues opening a number of MSG files in our system using your MSGViewer we are getting the "compressed-RTF CRC32 failed" error. The body of the MSG for these files is RTF. The files open normally in Outlook. I have attached 2 sample files and would appreciate any assistance you could provide.

[Example MSGs.zip](https://github.com/Sicos1977/MSGReader/files/258474/Example.MSGs.zip)

**Comment by Sicos1977** [comment]
The CRC check bug should be fixed now. Just get the latest source from Github and try it out. If it works for you then I will later make a new nuget package

**Comment by pmelisi** [comment]
Works great, thank you for your efforts.

**Comment by Sicos1977** [comment]
Your welcome ... and just to satisfy my own curiosity... for what are you using the MSGReader?

**Comment by pmelisi** [comment]
As a base to covert MSG files to HTML to display on iPads.

**Comment by Sicos1977** [comment]
Nice.. so the iPad is talking against a backend server since the code does not work with something like Xamarin and thus only works on Windows :-)
