### ISSUE TITLE
BodyHtml is sometimes broken after update >= 4.4.13

### ISSUE THREAD

**Issue by maxfurioso** [Sicos1977/MSGReader#332]
**Describe the bug**
After moving from version 4.4.13 to 4.4.16 (and above) the returned body HTML text is sometimes missing a character (mostly the char 'f') - but not in all cases. 
Please see the attached image 001.png that shows the email content opened with Outlook. The (later) missing character is highlighted. 
<img width="581" alt="001" src="https://user-images.githubusercontent.com/98384787/228305437-f49bcc1a-9a60-41a3-9442-908ba79fa310.png">
Then, please see also the attached image 002.png that shows the text stripped from the body html. As you can see, the highlighted character is now missing. 
<img width="350" alt="002" src="https://user-images.githubusercontent.com/98384787/228305806-7d6a0a58-3aff-479b-bb68-e9bd94bfdec0.png">
Finally, please see the attached image 003.png that rows the raw body HTML property content. The character is already missing here. 
<img width="560" alt="003" src="https://user-images.githubusercontent.com/98384787/228305963-8f868cfd-d9ab-4d92-9d39-3ab014f91e69.png">

Anyhow, this character is not missing at all places. The same word occurs twice. The first time the word is complete. Only the second time it's incomplete.

This is just one example. I have more samples, if required.
The error also occurs with the latest version 4.5.1. With version 4.4.13 all was fine!

**To Reproduce**
1. Load the attached msg file and access it via API. 
2. Access the body HTML property.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/98384787/228306741-298a2e9c-0093-4a11-a1c1-237c131f89a5.png">

**Expected behavior**
The word is complete at all places.

[WG i morgen_.msg.zip](https://github.com/Sicos1977/MSGReader/files/11092017/WG.i.morgen_.msg.zip)

**Comment by maxfurioso** [comment]
Great to see that this has been fixed so fast! Thanks!
Can you say when there will be a new release?

**Comment by Sicos1977** [comment]
I just released nuget package 4.5.3

**Comment by maxfurioso** [comment]
Thank you for the new release!

Unfortunately, something else is broken now. At lot of regression tests are failing on our side with the new version. 
Please see the attached images for just one example.

Outlook Message:
<img width="299" alt="outlook" src="https://user-images.githubusercontent.com/98384787/231699250-61a19093-4803-4279-b545-6caeeb2ec59b.png">

BodyHtml:
<img width="491" alt="source" src="https://user-images.githubusercontent.com/98384787/231699375-8fe16e44-6d85-47fb-8e43-b3151b22e5f9.png">

**Comment by maxfurioso** [comment]
Shall I open a new issue for that?

**Comment by Sicos1977** [comment]
I merged someone elses pull request that should have fixed the issue but there was another error in there that broke other things so I had to fix that.... reminder for me... first do a good check to see if a pull request does not break something else :-) .... but I was short in time and then it is sometimes to easy to just merge it without doing some checks.

It somestimes is hard to get all the error fixed in MSGReader because now and then you have those weird MSG files with strange bugs in it and then I have to figure out how to fix those things and keep everything else working.

**Comment by Sicos1977** [comment]
Okey I'll look into that this evening.

**Comment by Sicos1977** [comment]
> Thank you. Please let me known, if I can help.
> 
> No, this is Jetbrains Rider. But I can make a screenshot with Visual Studio if you like.

No need for that... I just was curious what editor you were using :-)

**Comment by maxfurioso** [comment]
Can you please release a new package so that we can test it?

**Comment by Sicos1977** [comment]
I'll try to make a new package today or otherwise tomorrow.

**Comment by Sicos1977** [comment]
I just released a new nuget package 4.5.5

**Comment by maxfurioso** [comment]
Thanks for the new package!

I have checked that and found some new errors that came up. It seems that I now get often duplicated characters, especially with '+'. 

Please see this snapshot from outlook. The number starts with "+49".
<img width="230" alt="003" src="https://user-images.githubusercontent.com/98384787/234845602-045b2b0d-2f5a-46f5-aeea-57f40d50f9ad.png">

The body HTML duplicates this as you can see here:
<img width="376" alt="001" src="https://user-images.githubusercontent.com/98384787/234845739-b6da7c38-bfd8-4139-91c9-aae7abec1c25.png">

And in the HTML string I found this:
![002](https://user-images.githubusercontent.com/98384787/234845815-28886966-b1d1-4d8d-9f96-034826f8d05b.png)

Please let me know, if you need more information.

**Comment by Sicos1977** [comment]
Luckely I have some time today to fix this myself, 2 times a merged someones pull request and 2 times it broke other things. So I'll look into it myself.

**Comment by maxfurioso** [comment]
Happy to hear that. Please let me know, if I can help.

**Comment by Sicos1977** [comment]
I just released version 5.0 with a rewritten method that extract HTML from RTF... please try this version and let me know how this one works.

**Comment by maxfurioso** [comment]
And another sample:

Outlook
<img width="62" alt="image" src="https://user-images.githubusercontent.com/98384787/234918217-fdc2e1d3-aba1-4857-8d10-69ea6839ac41.png">

HTML
<img width="35" alt="image" src="https://user-images.githubusercontent.com/98384787/234918498-ad492c20-38f0-42d5-978b-299c2f3b469b.png">

Raw HTML
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98384787/234919042-dfe70fcc-ecaa-484a-b7ba-91c0da067827.png">

The problem here is the ".*" sequence.

**Comment by Sicos1977** [comment]
Should all be fixed now, it was god damn hard to figure out how Outlook is de-encapsulating encoded chars from a RTF file ... but I think I figured it out. Please try version 5.1.0 and if it works correctly then buy me a nice cup of coffee.

**Comment by maxfurioso** [comment]
That's it. Everything works perfekt with the new version. 
Thank you very much. If you can get me a link for donation, coffee will be on its way soon ;-)

**Comment by Sicos1977** [comment]
You can use the sponsor button on top of the main GitHub MSGReader page and fiill in what you see fit. Just curious... in what kind of application are you using MSGReader?

**Comment by maxfurioso** [comment]
Done ;-) 

Nothing special. The app scans archived msg files to provide search support for a user in the context of a DMS.

**Comment by Sicos1977** [comment]
Thank you for the coffee :-)

**Comment by Sicos1977** [comment]
Ah okey... a minor issue to fix :-). I changed a lot lately inside MSGReader to fix those damn decoding issues in RTF so I'm glad it is just a simple bug.

**Comment by maxfurioso** [comment]
The latest version 5.2.1 fixes this. Thanks a lot for the fast update!
