### ISSUE TITLE
PlatformImage.FromStream(stream, formatHint) is not supported on windows

### ISSUE THREAD

**Issue by ShantoLives** [Sicos1977/MSGReader#337]
**Describe the bug**
PlatformImage.FromStream(stream, formatHint) is not supported on windows (per https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/images?view=net-maui-7.0)

This issue (https://github.com/dotnet/maui/issues/6742) suggests calling W2DImage.FromStream(stream, formatHint) instead on Windows

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Sicos1977** [comment]
I eventually solved it like this  because your suggested solution does not work on .net version lower then 7

![image](https://user-images.githubusercontent.com/6692947/232406943-4be26925-046f-4909-8da9-71c46960d54c.png)
