### ISSUE TITLE
other than engish outlook message and images problem

### ISSUE THREAD

**Issue by nwarude** [Sicos1977/MSGReader#34]
when to upload other than English  like Japanese language mail then message shown as question mark ?? means not read correctly

Please provide appropriate solution

**Comment by Sicos1977** [comment]
Please provide me the file that is giving you this issue.

**Comment by nwarude** [comment]
sorry but i cant provide outlook mails.
 examle is as follow
數百萬家網站，輕鬆快速結帳
eBay 網羅數百萬計個品牌的產品，你更可以使用 PayPal 輕鬆結帳，讓你購物更方便。無論是全新或二手商品，還是絕版限量精品，你都可以在 eBay 全部找到。使用 PayPal 付款，可以一次過完成購物與結帳流程。

this words converted into question mark not into html format
Please provide appropriate solution

**Comment by Sicos1977** [comment]
I can't solve your problem without the file that is giving you the issue. So I'll close this as wont fix.
