### ISSUE TITLE
Running into HRESULT: 0x80131044 (A strongly-named assembly is required.)

### ISSUE THREAD

**Issue by codewerfer** [Sicos1977/MSGReader#343]
Creating a fresh new net47 Winforms App and add `MsgReader` as a Nuget from Nuget.org results in an Exception at Runtime.
Assembly "Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" ... not found. **A strongly-named assembly is required.** (HRESULT: 0x80131044)

![image](https://user-images.githubusercontent.com/29753931/233332308-66df3c6c-6b20-44a5-b083-9b3f14a6e5a3.png)
_(edit: replaced with correct screenshot)_

Using `Microsoft.Maui.Graphics` inside this App (for the same context used by `MsgReader` like `PlatformImage.FromStream(fs).Save(fs_out)`) works fine.
![image](https://user-images.githubusercontent.com/29753931/233303860-a4e3b43f-d4cc-4c15-a1c2-fd26b564a96c.png)
(Therefore, the `Microsoft.Maui.Graphics` Assembly is there and can be accessed.)

Build `MsgReader` (thx for your work) from source without signin and use this unsigned, not strongly named Assembly also works.

It seems the use `Microsoft.Maui.Graphics` - which has no strong name - leads to problems when it is used as reference by a strongly named Assembly.

**Comment by Sicos1977** [comment]
Dropped support for signing
