### ISSUE TITLE
Email to Html transformation : Gibberish Greek text

### ISSUE THREAD

**Issue by tariqgitspace** [Sicos1977/MSGReader#344]
**Describe the bug**
Html preview generated from email with Greek text is garbled. Issue is seen with old as well as latest version : 5.1.0

**To Reproduce**
1. Perform msg to Html transformation of email with Greek text

**Expected behavior**
Text should not be gibberish in html generated from .msg.

**Screenshots**

**Desktop (please complete the following information):**
OS - Windows 11
Browser - Edge, Chrome, etc
Version- All

**Smartphone (please complete the following information):**
Device: N/A
OS - N/A
Browser- N/A
Version - N/A

**Additional context**

**Comment by Sicos1977** [comment]
At the moment I'm busy with some more improvements so that the MSGReader also possibly can read files that have set the encoding wrong. Can you sent me this file please? Please ZIP it before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Nevermind I see that you already sent it and it seems also to work correctly in the code base I have on this moment om my development system.

![image](https://user-images.githubusercontent.com/6692947/235992663-15efc137-b718-4121-a16f-2c5f8e32ff60.png)
