### ISSUE TITLE
Large memory allocated when handling relatively small MSG file

### ISSUE THREAD

**Issue by mathy-plutoflume** [Sicos1977/MSGReader#349]
**Describe the bug**
I was trying to extract `BodyText` and `BodyHtml` from MSG file and noticed that the memory usage was very high. 

**To Reproduce**
I used the [EmailWith2Attachments.msg](https://github.com/Sicos1977/MSGReader/blob/master/MsgReaderTests/SampleFiles/EmailWith2Attachments.msg) from the sample test files for my analysis

Code i used to benchmark
``` csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using MsgReader.Outlook;
using System.Text;

public class Program
{
    public static void Main(string[] args)
    {
        BenchmarkRunner.Run<ExtractMsg>();
    }
}

[MemoryDiagnoser]
public class ExtractMsg
{
    [Params(@"C:\EmailWith2Attachments.msg")]
    public string FileName { get; set; }

    public ExtractMsg() => Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

    [Benchmark]
    public void Extract()
    {
        using (var msg = new Storage.Message(FileName))
        {
            //var txtBody = msg.BodyText;
            var htmlBody = msg.BodyHtml;
        }
    }
}
```

**Expected behavior**
- Lesser memory allocated for such a small file

**Actual behavior**
Input `msg` file size is `267 KB` and memory allocated for that is around `55 MB`

|     Method |              FileName |        Mean |     Error |    StdDev |      Gen0 |     Gen1 |     Gen2 |   Allocated |
|----------- |---------------------- |------------:|----------:|----------:|----------:|---------:|---------:|------------:|
| ExtractMsg | C:\\EmailWith2Attachments.msg [74] |  9,315.1 us | 184.83 us | 417.19 us | 6078.1250 |  15.6250 |        - | 55879.93 KB |

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 (10.0.22621.1702/22H2/2022Update/SunValley2)
 - Browser: NA
 - Version: 5.2.2
 - 12th Gen Intel Core i7-1260P, 1 CPU, 16 logical and 12 physical cores
- .NET SDK=7.0.203
    [Host]    : .NET 6.0.16 (6.0.1623.17311), X64 RyuJIT AVX2
    .NET 6.0 : .NET 6.0.16 (6.0.1623.17311), X64 RyuJIT AVX2
- BenchmarkDotNet=v0.13.5

**Additional context**
- I tried loading other test `msg` files with large text in body (400,000 words). The `msg` file size was `548 KB` whereas the Memory allocated for that was around `43 MB`. Benchmark report below,

|  Method |               FileName |     Mean |     Error |    StdDev |      Gen0 |     Gen1 |     Gen2 | Allocated |
|-------- |----------------------- |---------:|----------:|----------:|----------:|---------:|---------:|----------:|
| Extract | C:\\LargeHtmlbody.msg [22] | 6.161 ms | 0.1224 ms | 0.2581 ms | 4781.2500 | 250.0000 | 234.3750 |   43.8 MB |

**Comment by Sicos1977** [comment]
Did you find out what part is consuming the memory?

**Comment by dhilmathy** [comment]
> Did you find out what part is consuming the memory?

@Sicos1977 Not exactly. I tried removing some of the parts (specially the Attachment part) inside `LoadStorage` to see whether that may be cause. But could find the exact place.
