### ISSUE TITLE
Email to Html transformation : Gibberish Greek text

### ISSUE THREAD

**Issue by tariqgitspace** [Sicos1977/MSGReader#351]
**Describe the bug**
Html preview generated from email with Greek text is garbled **for all emails othan than first email**. 
Version checked: **5.1.0, 5.2.2**
***Issue files shared over email**

**To Reproduce**
1. Perform msg to Html transformation of email with Greek text
2. First email is correctly encoded. But others are garbled

**Expected behavior**
Text should not be gibberish in html generated from .msg.

**Screenshots**

**Desktop (please complete the following information):**
OS - Windows 11
Browser - Edge, Chrome, etc
Version- All

**Smartphone (please complete the following information):**
Device: N/A
OS - N/A
Browser- N/A
Version - N/A

**Additional context**

**Comment by Sicos1977** [comment]
See release 5.2.4

**Comment by PiotrekKrakowiak** [comment]
The customer reported that this is mostly fixed indeed, expect for a few characters "η" "ή" "ο" "οι". See the example below:

![image](https://github.com/Sicos1977/MSGReader/assets/17331407/98db0233-f2ba-4fc2-9d61-43185168721f)

Could you take another look at this?
