### ISSUE TITLE
New release not available 

### ISSUE THREAD

**Issue by sarang3105** [Sicos1977/MSGReader#352]
A PR for issue https://github.com/Sicos1977/MSGReader/issues/347 was raised by @kenjiuno and merged sometime back. 
Is there a possibility to get a new release with the fix ? TIA

**Comment by Sicos1977** [comment]
At the moment I'm not in the neighbourhood of my development PC... I'll try to do it tomorrow.

**Comment by sarang3105** [comment]
@Sicos1977 Any update on this ?

**Comment by Sicos1977** [comment]
I just released a new nuget package... so you should be able to get it in half an hour when it is indexed by nuget.
