### ISSUE TITLE
Getting byte array from Attachment of type EMBEDDED_MSG

### ISSUE THREAD

**Issue by mathy-plutoflume** [Sicos1977/MSGReader#353]
I am trying to processes a `MSG` file which has three attachments inside it. Something like,
```
test_message.msg
    ├── Attachment1.msg
    ├── Attachment2.eml
    ├── Attachment3.pdf
```
When i am trying to extract the attachments using `Message.Attachments` i am getting `Attachment1.msg` & `Attachment2.eml` of type `Message` and `Attachment3.pdf` as `Attachment` type. 
For `Attachment3.pdf` i can access the `Bytes[]` from `Attachment.Data`. Is there any way where i can get the `Bytes[]` for the `Attachment1.msg` and `Attachment2.eml` attachments?

**Comment by Sicos1977** [comment]
/// <summary>
        ///     Returns the data
        /// </summary>
        public byte[] Data => _data ?? GetMapiPropertyBytes(MapiTags.PR_ATTACH_DATA_BIN);
