### ISSUE TITLE
Gibberish when reading email with Hebrew letters - started since latest version

### ISSUE THREAD

**Issue by Nir1812** [Sicos1977/MSGReader#356]
When getting the email text, some Hebrew words are extracted as gibberish. 
When moving back to version 5.2.3 it works fine.

**Comment by Sicos1977** [comment]
Are you extracting the HTML or the pure text body? 

And if possible please sent an example msg file (ZIP it before sending) and some screenshots to sicos2002@hotmail.com

**Comment by Nir1812** [comment]
I'm using BodyHTML property to get the HTML.
I will send an example to the email you asked.

**Comment by Nir1812** [comment]
Any updates on this?

**Comment by Sicos1977** [comment]
I'm trying to fix this next week.

**Comment by Nir1812** [comment]
I have sent it to the email address you specified.  
Anyway, use this link to download the msg file:

https://odcoil-my.sharepoint.com/:u:/g/personal/nir_od_co_il2/ESFL9UVPjdJAsR4C00gdnkEBwQLfNJoEstv1Z29BhEbCHw?e=K6JG1N

**Comment by Sicos1977** [comment]
Please check the latest source that is now on github and see if that fixes the problem. If so then I'll make a new nuget package.

There are spaces between the encoded chars (that should not be there) and that is confusing the decoder that tries to guess the encoding.

**Comment by Sicos1977** [comment]
I just published a new nuget package that should fix the issue. It also has a new property to control the charset detection confidence level.

**Comment by Nir1812** [comment]
Can you elaborate on the charset detection confidence level thing?
I have another email that only some of the letters are displayed gibberish...
Maybe the new setting will solve it?

**Comment by Nir1812** [comment]
Here is the files for testing:
https://odcoil-my.sharepoint.com/:u:/g/personal/nir_od_co_il2/EQ7_E2LXSfZLhgeo4MhvcC8BQosl6pYLx7QUkTCDtIZR0w?e=2IM8QA

**Comment by Sicos1977** [comment]
I explained it in the readme. If you lower the confidence level you could be in luck and get a match but the higher the better.

**Comment by Nir1812** [comment]
> I explained it in the readme. If you lower the confidence level you could be in luck and get a match but the higher the better.

I’m just wondering if this is the correct approach, since Outlook”knows” how to display the message (you can see the file in my second upload url above) without any beed to specify confidence level…

**Comment by Sicos1977** [comment]
As long as I don't know how outlook figures it out I don't know how to solve some mails with mixed encodings. I tried a dozen different solutions to make something that can decode all the different e-mails with all the different mixed encodings but was not lucky so far. 

If I do it with solution a then e-mail a works but e-mail c fails.
If I then try to figure it out so that also e-mail c is decoded correctly then e-mail b fails..

etc...

**Comment by Sicos1977** [comment]
I don't know if you only shared you sharepoint document with me but it looks like there are health documents  in the PDF that you included.... just saying it so that you know. 

I can't read Jewish language but saw some words from the Health department.

**Comment by Nir1812** [comment]
> As long as I don't know how outlook figures it out I don't know how to solve some mails with mixed encodings. I tried a dozen different solutions to make something that can decode all the different e-mails with all the different mixed encodings but was not lucky so far.
> 
> If I do it with solution a then e-mail a works but e-mail c fails. If I then try to figure it out so that also e-mail c is decoded correctly then e-mail b fails..
> 
> etc...

So, just to make sure I understand the new property, if I set it to a higher value, say 0.97 it will detect more characters as unicode text? Is there a property for the 'fallback' code-page ?

**Comment by Sicos1977** [comment]
> > As long as I don't know how outlook figures it out I don't know how to solve some mails with mixed encodings. I tried a dozen different solutions to make something that can decode all the different e-mails with all the different mixed encodings but was not lucky so far.
> > If I do it with solution a then e-mail a works but e-mail c fails. If I then try to figure it out so that also e-mail c is decoded correctly then e-mail b fails..
> > etc...
> 
> So, just to make sure I understand the new property, if I set it to a higher value, say 0.97 it will detect more characters as unicode text? Is there a property for the 'fallback' code-page ?

No... if you set it higher the detection tool must me more sure that it is the correct encoding so it probably detects less.

If you set it lower it is quicker satisfied that it has detected the correct encoding but that is more error prone

**Comment by Sicos1977** [comment]
MSGReader uses this to try to detect the encoding --> https://github.com/CharsetDetector/UTF-unknown

**Comment by Nir1812** [comment]
The issue has returned... I've tried to set different confidence levels but nothing helps.
