### ISSUE TITLE
Unable to install using the new Microsoft.Powershell.PSResourceGet module

### ISSUE THREAD

**Issue by dy-nz** [Sicos1977/MSGReader#358]
I love MSGReader. Thanks for developing it and maintaining it.

**Bug:
I can install MSGReader ok using the soon-to-be-legacy command
   Install-Package MSGreader -ProviderName nuget -SkipDependencies
I cannot install MSGReader using the PSResourceGet module (Beta 24), in Powershell Core (v7.3.6).
PSResourceGet will be released in Powershell 7.4 LTS in November 2023 and is intended to replace Powershell's two existing PowershellGet and PackageManagement modules.

**Error messages:
  Install-PSResource: Response does not contain 'items' element for package with name 'MSGreader' from repository 'nuget'.
  Install-PSResource: Package(s) 'MSGreader' could not be installed from registered repositories 'nuget, PSGallery'.

I can install OpenMcdf and RtfPipe no problem.

**To Reproduce (and note that version 3 of the nuget API is used):
Install Powershell 7.2 or later
start Powershell 7.2 or later
Install-Module -Name Microsoft.Powershell.PSResourceGet -Repository PSGallery -AllowPrerelease -Force
exit Powershell
start Powershell 7.2 or later
Register-PSResourceRepository -Name nuget -Uri 'https://api.nuget.org/v3/index.json' -Trusted -Force
Install-PSResource -Name MSGReader -Repository nuget

**Expected behavior:
Successful install. 
Visible by the existence of the directory "C:\Program Files\Powershell\Modules\MSGReader".
Warning messages are ok:
  WARNING: Installing dependencies is not currently supported for V3 server protocol repositories. The package will be installed 
  without installing dependencies.
  WARNING: Installing dependencies is not currently supported for V3 server protocol repositories. The package will be installed 
  without installing dependencies.

**Environment:
Edition:	Windows Server 2022 Datacenter Azure Edition
Version:	21H2
Installed on: ‎15/‎08/‎2022
OS build:	     20348.1906
Powershell:
  PSVersion        7.3.6
  PSEdition         Core
  GitCommitId   7.3.6
  OS                   Microsoft Windows 10.0.20348
  Platform          Win32NT
  PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
  PSRemotingProtocolVersion  2.3

Thanks.

**Comment by Sicos1977** [comment]
I have no idea how I can help you with this. I never have done anything with PowerShell.
