### ISSUE TITLE
Question : Deleting Attachement from eml file

### ISSUE THREAD

**Issue by sven-peeters-stitchd-be** [Sicos1977/MSGReader#360]
Hi,

Your tool is exactly what we need, we need to extract attachements from both msg and eml files.
However, we also want to delete them from the original msg/eml file to avoid having double storage costs.
While deleting an attachement in an msg file is supported, I can't see this for the eml files.
Any reason why this was not implemented, is it technically to hard to implement?

Regards,
Sven

**Comment by Sicos1977** [comment]
There was never a requirement on my side to implement a feature to delete attachments from EML files so that is the only reason why it is not implemented. Also I think it should not be to hard to implement it (but I could be wrong :-))

**Comment by Sicos1977** [comment]
Support to delete an attachment from an EML file is added in version 5.4.1
