### ISSUE TITLE
EML File Parsing Fails due to ALT tag in Content-Disposition section

### ISSUE THREAD

**Issue by DisIsAbhi** [Sicos1977/MSGReader#362]
EML file with attachment contains Content-Disposition section with File name and ALT tags. 
if there is no ALT tag i am able to read the EML using Message.Load(fileinfo)
but if there is an ALT tag then the reader throws an error that unexpected ALT, reach out to Developer for fix!

Current workaround is that i am reading the eml file, removing the ALT tag and saving it back so i can read it without errors.
Thanks

**Comment by Sicos1977** [comment]
Can you show me how this  Content-Disposition looks like?

**Comment by DisIsAbhi** [comment]
I cant provide the actual file itself but it looks like this
Content-Disposition: attachment; filename="Z\" alt="Filename.png". 
It is in the Line 4 or 5 of the EML when  opened in a notepad++

**Comment by Sicos1977** [comment]
Can you show me the stack trace about where this exception is thrown? I can't find where I throw that message.

**Comment by Sicos1977** [comment]
Support for the ALT tag is added in version 5.4.1
