### ISSUE TITLE
Removing an attachement from EML and then saving the messages, still includes deleted attachement

### ISSUE THREAD

**Issue by sven-peeters-stitchd-be** [Sicos1977/MSGReader#363]
I have an eml file with 3 attachements which I open, then delete the middle attachement (pos 1) and finally save the EML with a different filename. Unfortunately the result EML still contains all attachements.

var msg = MsgReader.Mime.Message.Load(new FileInfo("C:\\Users\\XXXX\\Downloads\\test.eml"));
msg.Attachments.RemoveAt(1);
msg.Save(new FileInfo("C:\\Users\\XXXX\\Downloads\\test_clean2.eml"));

Guessing the issue is in the Save method on the Message class where you either save it as raw (I think that's the original message) when changes are detected on attachements or reconstruct the message when no changes are detected on the attachement. I think this condition should be inverted.

**Comment by Sicos1977** [comment]
Yeah you are right, the if statement should be inverted :-) ... that is what you get if you dont test it :-)

**Comment by Sicos1977** [comment]
Should be fixed now
