### ISSUE TITLE
 Error: Unsupported message type for .msg and eml files

### ISSUE THREAD

**Issue by SonalRana** [Sicos1977/MSGReader#365]
**Describe the bug**
Some of the .msg and .eml files shows unsupported message type error.

**To Reproduce**
1. Attaching 2 msg files
2. Using MsgReader version 5.2.4.0 - Process these files
3. See error: Unsupported message type for .msg and eml files

**Expected behavior**
Should process these files without any error.
[Sample.zip](https://github.com/Sicos1977/MSGReader/files/12600696/Sample.zip)

Notes: I tried version MsgReader  5.2.4.0 and the latest on 5.4.3.0 and both had **Unsupported message type error**.

**Comment by Sicos1977** [comment]
I'll have to look into the file to figure out what kind of type it is. I'll try to make a fix this weekend.

**Comment by Sicos1977** [comment]
Okey seems to be a IPM.SkypeTeams.Message type.

**Comment by SonalRana** [comment]
@Sicos1977 - Hello Kees, can I expect a fix by this week on this issue? Thanks again for your attention.

**Comment by Sicos1977** [comment]
Sorry I totally forgot about this issue because I was busy with placing solar panels on my roof this weekend. There should be a new nuget package 5.4.4 that has support for your message type.
