### ISSUE TITLE
MsgReader version 5.4.4.0 unable to process some of .msg and .eml

### ISSUE THREAD

**Issue by SonalRana** [Sicos1977/MSGReader#366]
**Describe the bug**
MsgReader version 5.4.4.0 unable to process some of .msg and .eml which were processed by older versions of the library.

**To Reproduce**
1. Use attached files
2. MsgReader 'ExtractToFolder' failes with  error
3. Error Message - System.NullReferenceException: 'Object reference not set to an instance of an object.'
4. Detail Error Message
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MsgReader
  StackTrace:
   at MsgReader.Rtf.Document.DeEncapsulateHtmlFromRtf(String rtf)
   at MsgReader.Outlook.Storage.Message.get_BodyHtml()
   at MsgReader.Reader.PreProcessMsgFile(Message message, ReaderHyperLinks hyperlinks, String outputFolder, String& fileName, Boolean& htmlBody, String& body, String& contactPhotoFileName, List`1& attachments, List`1& files)
   at MsgReader.Reader.WriteMsgEmail(Message message, String outputFolder, ReaderHyperLinks hyperlinks)
   at MsgReader.Reader.ExtractToFolder(String inputFile, String outputFolder, ReaderHyperLinks hyperlinks, Nullable`1 messageType, Stream logStream)

**Expected behavior**
The library should process these files like the earlier versions did.

[sample.zip](https://github.com/Sicos1977/MSGReader/files/12703201/sample.zip)

**Comment by Sicos1977** [comment]
Works fine overhere

**Comment by SonalRana** [comment]
> Works fine overhere
> 
> ![image](https://user-images.githubusercontent.com/6692947/271842001-09df3d0d-386e-4a89-840d-9026c7e2f14a.png)

**Comment by SonalRana** [comment]
Thanks Kees,

I had seen another issue opened which had similar problem like mine, which showed System.NullReferenceException. I don't see that in the list anymore. Is that fixed? If yes, that fix could have made this work

**Comment by SonalRana** [comment]
![image](https://github.com/Sicos1977/MSGReader/assets/6777597/486facaa-83cc-4272-88fb-4fd297e56426)

I am still getting the same error
[Attachment #1 E-mail.zip](https://github.com/Sicos1977/MSGReader/files/12777775/Attachment.1.E-mail.zip)

**Comment by SonalRana** [comment]
Hello Kees,

Do you have an estimate on when you are going to release the next package? I have been following this issue and I am hopeful that this will resolve issue I am facing as well - https://github.com/Sicos1977/MSGReader/issues/368https://github.com/Sicos1977/MSGReader/issues/368.

**Comment by Sicos1977** [comment]
I just released version 5.4.5 ... try this one.

I don't get any errors when opening your test e-mail with it.

![image](https://github.com/Sicos1977/MSGReader/assets/6692947/dc8de965-50fa-481a-b9b1-d2cfda0a0b4e)

**Comment by SonalRana** [comment]
> I just released version 5.4.5 ... try this one.
> 
> I don't get any errors when opening your test e-mail with it.
> 
> ![image](https://user-images.githubusercontent.com/6692947/273787949-dc8de965-50fa-481a-b9b1-d2cfda0a0b4e.png)

Thanks a lot. It worked!!!

**Comment by Sicos1977** [comment]
Good to hear
