### ISSUE TITLE
[Time Sync Issue]

### ISSUE THREAD

**Issue by tariqgitspace** [Sicos1977/MSGReader#367]
**Describe the bug**
Latest/top email is not time synchronized with other messages in the email chain. When doing email to Html transformation, time in Top/Latest email is processed as per timezone of the machine. However, time in other messages in the email chain is processed as plain string. This leads to time sync issue when transformation is done in a differnet time zone

**To Reproduce**
Take a sample email chain
Setting your machine to a differnet timezone, perform email to Html transformation.

Expected behavior
Time should be synchronized.

**Screenshots**

**Desktop (please complete the following information):**
OS - Windows 11
Browser - Edge, Chrome, etc
Version- All

**Smartphone (please complete the following information):**
Device: N/A
OS - N/A
Browser- N/A
Version - N/A

**Additional context**

**Comment by Sicos1977** [comment]
I don't understand the problem. MSGReader just gives you access to the e-mail and just returns the date/time values. It does not recalculate it.

**Comment by tariqgitspace** [comment]
@Sicos1977 Please see example below and notice timestamp between latest and other messages. Thanks

From **Email File**
![image](https://github.com/Sicos1977/MSGReader/assets/6762447/b913e9bf-3abb-4b66-a330-5771b6c14cd6)


**Html generated from Above:**
![image](https://github.com/Sicos1977/MSGReader/assets/6762447/14994478-46f9-4e68-a251-e15f085cc103)

**Comment by Sicos1977** [comment]
That probably has to do with that the e-mail is sent across different time zones. When converting the e-mail to HTML it uses the time-zone that the computer is using where the code is run.

I need one of those e-mails to see if there is something in the e-mail that I can use to calculate the correct date.

Please ZIP the MSG file before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Where are u located... the USA? ... so is the timestamp in the outlook screen the current time?

**Comment by Sicos1977** [comment]
I don't see any problems with the MSG file you sent me.

Outlook and MSGViewer both show the same date and time

![image](https://github.com/Sicos1977/MSGReader/assets/6692947/26b26329-e8f3-43e3-9da5-c65d509cdd76)

**Comment by Sicos1977** [comment]
No reply ... closed
