### ISSUE TITLE
Some message files (.msg) fail to load.

### ISSUE THREAD

**Issue by bluefish1254** [Sicos1977/MSGReader#368]
**Describe the bug**
Some message files (.msg) fail to load.

**To Reproduce**
MSGReader v5.4.4

1. Open MSG Viewer
2. [File] > [Open] > Select the problematic .msg file

Result:
System.NullReferenceException error occurs and the contents of the message file cannot be opened.

![image](https://github.com/Sicos1977/MSGReader/assets/145929608/239ec078-a5a7-4ec6-9610-46a49ad88db9)

**Expected behavior**
When reading an email message file that contains multiple languages, there appear to be cases where CharsetDetector.DetectFromBytes returns Null.
The message creation procedure is unknown, but this problem occurs many times with email contains 2-byte charactor sets(DBCS) created using Outlook clients.

The .msg file contains the string "～" 0x8160 defined by code page 932 (Shift_JIS)
![image](https://github.com/Sicos1977/MSGReader/assets/145929608/cdd33142-8513-4ccc-842a-967d9bb0ca8c)

As a possible improvement, I suggest changing the implementation to skip logging (or output other explanatory text to the log) the Detected encoding if the result of CharsetDetector.DetectFromBytes returns Null.

e.g.)

https://github.com/Sicos1977/MSGReader/blob/7ff37b3643b237c2a08d8826bf91f4ec645cb036/MsgReaderCore/Rtf/Document.cs#L146C30-L146C30

                    var detectionResult = UtfUnknown.CharsetDetector.DetectFromBytes(byteBuffer.ToArray());
                    if(detectionResult.Detected != null)
                    {
                        Logger.WriteToLog($"Detected encoding '{detectionResult.Detected.EncodingName}' with a confidence of {detectionResult.Detected.Confidence}");

                        if (detectionResult.Detected.Confidence > CharsetDetectionEncodingConfidenceLevel)
                            stringBuilder.Append(byteBuffer.GetString(detectionResult.Detected.Encoding));
                        else
                        {
                            Logger.WriteToLog($"Ignored detected encoding because it was not above the threshold of '{CharsetDetectionEncodingConfidenceLevel} using encoding '{_defaultEncoding.EncodingName}' instead");
                            stringBuilder.Append(byteBuffer.GetString(_defaultEncoding));
                        }
                    }

**Comment by Sicos1977** [comment]
Good point, I expected that the UtfUnknown would always return something... It does also not give a warning that it can return null

**Comment by bluefish1254** [comment]
Thank you. I hope it will be fixed in the next version

**Comment by bluefish1254** [comment]
In addition, according to the thread below, the UtfUnknown library may return Detected as Null in a rare case.

https://github.com/CharsetDetector/UTF-unknown/issues/125

If it is difficult to handle all cases, you may be able to avoid application crashes by adding null handling.

**Comment by Sicos1977** [comment]
That is what I'm going to do.

**Comment by Sicos1977** [comment]
Fixed. I need todo some other thing before releasing a new nuget package
