### ISSUE TITLE
.msg to Html transformation issue 

### ISSUE THREAD

**Issue by forhad111** [Sicos1977/MSGReader#369]
**Describe the bug**
When an email has the following head content, it could not read the email and transform email to Html properly.
\<head\>} {\\\*\htmltag \<meta http-equiv="Content-Type" content="text/html; charset=utf-8"\>} {\\\*\htmltag \</head\>} {\\*\htmltag

However, if we change header to \<meta charset="utf-8"\>, then it works properly.

**To Reproduce**
1. Use [Aspose Library](https://docs.aspose.com/email/python-net/creating-and-saving-msg-files/) to create the .msg files.  From the MAPI property PR_RTF_COMPRESSED , if we look at the HTML tags where the content type is defined, we see the following:  
\<head\>} {\\\*\htmltag \<meta http-equiv="Content-Type" content="text/html; charset=utf-8"\>} {\\\*\htmltag \</head\>} {\\\*\htmltag

2. Now try to convert the file from .msg to Html

**Expected behavior**
Should be able to transform .msg to Html.

**Screenshots**

**Desktop (please complete the following information):**
OS - Windows 11
Browser - Edge, Chrome, etc
Version- All

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by Sicos1977** [comment]
Can you sent me an example MSG file? Please ZIP it before sending it to sicos2002@hotmail.com

**Comment by forhad111** [comment]
Hi,

Thanks for reaching out to me. I asked our clients share a file with us.
When I get the file, I’ll send it to you.

Thanks,
Forhad

**Comment by Sicos1977** [comment]
No response anymore .... closed
