### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by brenopgarcia** [Sicos1977/MSGReader#370]
Hello,

I tried to use the method GetEmailRecipients and I got an exception. The email file has more than 40 people emailing the recipient "To".
![image](https://github.com/Sicos1977/MSGReader/assets/28199524/b660c2bd-be63-40ca-a0dd-b463d5aa6719)
![image](https://github.com/Sicos1977/MSGReader/assets/28199524/ab717b0f-d23b-46ea-8cd8-d136fee13792)

Is it possible to change the range via a parameter?

Thank you.

**Comment by Sicos1977** [comment]
No that is not possible. Please sent me the MSG file so that I can investigate what is going wrong.

Please ZIP te file before sending it to sicos2002@hotmail.com

**Comment by brenopgarcia** [comment]
Unfortunately, I can't send the email file, it is private.

By the way, thank you for answering.

**Comment by Sicos1977** [comment]
The error indicates that something is going wrong when decoding the recipient row from the MSG file. But if you can't sent me the file I can't check what is going wrong. You could try to debug it yourself and sent me a pull request if you can get it fixed. Without an MSG file I can't fix it because I don't know what is going wrong.

**Comment by Sicos1977** [comment]
My first guess would be by adding a breakpoint overhere and see what is happening --> https://github.com/Sicos1977/MSGReader/blob/7ff37b3643b237c2a08d8826bf91f4ec645cb036/MsgReaderCore/Outlook/UnsendableRecipients.cs#L489

**Comment by brenopgarcia** [comment]
Sorry,

On line 534 where it has a switch statement for type, it receives the type
4095, then throws an exception on line 665.

[image: image.png]

I am not sure about this issue, but this .msg file has required and
optional recipients.

[image: image.png]

Does it could be the reason?!

BR

Breno Garcia

**Comment by brenopgarcia** [comment]
Actually, it has a lot of types that are not on the Enumerable PropertyType.
