### ISSUE TITLE
Accessing properties that don't have consistent proptag

### ISSUE THREAD

**Issue by matt1liu** [Sicos1977/MSGReader#372]
Hello, I would like to use MSGReader to add reactions data to the body when an .msg is extracted to html. I am trying to add code to retrieve the MAPI property that reactions depends on, but this property does not have a consistent proptag, and may change per-mailbox. Here's an example I've retrieved from MFCMapi.
![image](https://github.com/Sicos1977/MSGReader/assets/147664409/62dd13bd-991c-43ea-8296-5b0e92968456)
I see there is similar code to retrieve Keywords/Categories, but I did not have luck following the same pattern. Are these MAPI properties able to be retrieved by Storage.GetMapiProperty? Is there way of getting these properties from name and namedPropertyGuid? Thanks!

**Comment by Sicos1977** [comment]
This are so called named properties. They always have an address that is above 0x8000. Everything below is static. But named properties should always have the same name no matter wat address they get. So you can use the name to get them.

**Comment by matt1liu** [comment]
I see that GetMapiPropertyFromPropertyStream and GetMapiPropertyFromPropertyStreamOrStorage compare the propertyIdentifer the caller passes (ReactionsSummary in my case) to MAPI properties from the stream, but I only see comparison of property address (x8xxx), and no comparison of property name. I set up a test and can verify from a break point that the property does exist in the stream, but in the end, the property identifier ReactionsSummary is not "found".

![image](https://github.com/Sicos1977/MSGReader/assets/147664409/93d25a59-0992-4252-8847-dafb771a036d)
![image](https://github.com/Sicos1977/MSGReader/assets/147664409/4eec0ab6-bbf9-432c-84c4-e573ffb65fcf)

Please let me know if im missing something or can provide extra information. thanks so much!
