### ISSUE TITLE
MSGReader version 5.4.5 not signed by SN

### ISSUE THREAD

**Issue by nareddykrishna** [Sicos1977/MSGReader#376]
MSGReader version 5.4.5 not signed by SN

<img width="220" alt="2023-10-20_15-11-32" src="https://github.com/Sicos1977/MSGReader/assets/146452871/c25c6fbd-fe13-417e-a3ab-53550f310955">

**Comment by Sicos1977** [comment]
Yes that is correct, I dropped signing a few version ago because almost nobody uses strong names anymore and when using strong names yourself that gives trouble with finding nuget packages to do.

**Comment by nareddykrishna** [comment]
By any chance can I get signed copy of it?

Or what is last version which was signed?

Thanks
Krishna Mohan Reddy Nareddy
________________________________

**Comment by Sicos1977** [comment]
There are tools to sign an assembly when it is not signed but you then probably get issues with other packages that are referenced in MSGReader that are also not signed. The best is just to drop support in your app for signing.

If you ever are going to move away from the .net framework then there isn't a thing any more like strong naming an assembly
