### ISSUE TITLE
Image does not appear on html while extracting the msg file to particular folder.

### ISSUE THREAD

**Issue by karmegams02** [Sicos1977/MSGReader#378]
Hi Team,

While extracting the msg file, dummy image files are extracted. In html file having the dummy image path. So the original image is not shown in HTML view. Please check and share the details.

Regards,
Karmegam

**Comment by Sicos1977** [comment]
Use the issue template. Filing an issue like this is just useless. You think that I can figure out what is wrong if you do it like this?

**Comment by karmegams02** [comment]
Currently we are facing issue with converting msg file to html for particular file. We have attached the sample with msg file to reproduce the reported issue on your end. Please find the input and output screenshots below,

Input:
![image](https://github.com/Sicos1977/MSGReader/assets/103259299/ee604218-cb2d-46bb-aff6-fc40159623ea)
Output:
![image](https://github.com/Sicos1977/MSGReader/assets/103259299/10a80e5c-af57-4730-8a78-be51ec805829)

Sample:https://www.syncfusion.com/downloads/support/directtrac/general/ze/MSG_to_HTML_Conversion977308970

Kindly check and share the solution.
