### ISSUE TITLE
Optional Recipients for Appointment not being extracted

### ISSUE THREAD

**Issue by AdamE87** [Sicos1977/MSGReader#38]
Hey Kees,

I'm currently having an issue where an msg appointment has optional attendees but are not being extracted by the program

**Comment by Sicos1977** [comment]
Can you send me the file that is giving you this issue?

**Comment by AdamE87** [comment]
Sure thing,

Please destroy after.

**Comment by Sicos1977** [comment]
I think you didn't add anything... if you want you can send the msg file to sicos2002@hotmail.com Please zip the msg file before sending it... otherwise hotmail converts it to eml and renders is useless for me.

**Comment by AdamE87** [comment]
Sent!

**Comment by Sicos1977** [comment]
Hi Adam,

It took some time to figure out where the missing recipients are located. It seems that they are in a named property called "AppointmentUnsendableRecipients". I never did anything with that property so I have to figure out how to read that. It will take some time and at the moment I'm a little bit short in that... I'll try to make this work this weekend.

Greetings,
Kees van Spelde

**Comment by AdamE87** [comment]
Awesome,

Thanks Kees, it's much appreciated!

Greetings from the UK.

Adam

**Comment by Sicos1977** [comment]
Hi Adam, to give you an update... I'm about half way implementing this feature. I thought it would be easy to do but it is a lot of work. The UnsendableRecipients property is a complex structure to implement.

If you want to read something more about it then see here ---> https://msdn.microsoft.com/en-us/library/ee158253(v=exchg.80).aspx

**Comment by AdamE87** [comment]
Hey Kees,

Thanks so very much for the hard work you've put into this I hope someone
else will get the benefits from it too! I've had a read through the
articles you've sent over and found them very interesting and very
complicated!!
I've found a few interesting email examples through working with your
library that I'd be happy to show you (once you've recovered from fixing
this one ;) )

Best,

Adam

**Comment by Sicos1977** [comment]
Just for my own curiosity ... for what are you using the MSGReader?

**Comment by AdamE87** [comment]
I'm not actually using entire program, just the reader.dll for ETL of email
files, extracting all the info into an audit and analysis tool.

**Comment by Sicos1977** [comment]
I just released version 2.0.0, this fixes your issue by adding support for this property. This was a lot of work.. so if you want to buy me a cup of coffee then see the donate button on the main page ;-)

**Comment by Sicos1977** [comment]
Thanks for the cup of coffee :-) ... everything working ok with the new enhancement?

**Comment by AdamE87** [comment]
Not a problem at all :)

Not had a proper chance to test yet.... going to have a go this afternoon!

**Comment by AdamE87** [comment]
Yep, no issues! Thanks so much for the time and effort!
