### ISSUE TITLE
Image does not appear on html while extracting the msg file to particular folder.

### ISSUE THREAD

**Issue by karmegams02** [Sicos1977/MSGReader#380]
Hi @Sicos1977 ,
Currently we are facing issue with converting msg file to html for particular file. We have attached the sample with msg file to reproduce the reported issue on your end. the Please find the input and output screenshots below,

Reproduce steps:
1.Please download the sample by using below link.
2. extract the downloaded zip folder.
3. Run the sample 
4. You can find the extracted files 
5. Open and view the output html file

Input screenshot:
![image](https://github.com/Sicos1977/MSGReader/assets/103259299/c197935d-a5d9-40d2-bc08-4df179e416b4)
Output screenshot:
![image](https://github.com/Sicos1977/MSGReader/assets/103259299/882c2b5d-802f-4fcb-b5b2-281054d2b6c4)

Sample:https://www.syncfusion.com/downloads/support/directtrac/general/ze/MSG_to_HTML_Conversion977308970

Kindly check and share the solution.

Note: The output html file having wrong image path.

**Comment by Sicos1977** [comment]
I does not work because this is a MSG file with a pure RTF content. MSGReader only supports either HTML or HTML encapsulated into RTF

**Comment by Sicos1977** [comment]
Nevermind... seemed a bug anyway... fixed in the latest release

**Comment by karmegams02** [comment]
> Nevermind... seemed a bug anyway... fixed in the latest release

Hi @Sicos1977 ,
Can you please share the details of the above-reported issue and when it will be available in your library?
