### ISSUE TITLE
Is it possible to get the Outlook conversation id from a message?

### ISSUE THREAD

**Issue by AlexPeek01** [Sicos1977/MSGReader#382]
Hi Sicos,

For a project I'm working on I need to obtain the ConversationId from Outlook messages to group them by e-mail chain.
Ideally we don't want to use Microsoft Graph or something similar to obtain these since we want users to be able to upload .msg and .eml files even after deleting the original e-mails from their mailbox.

I saw that the ConversationTopic and ConversationIndex were available, but couldn't find the Id. I tried obtaining these through the GetMapiProperty and GetNamedMapiProperty methods, but this kept returning null.
The values that I tried for these methods were: 0x0071, 0x0071001E,  0x0070, 0x0070001E, 0x3013001E, PidTagConversationId and PR_CONVERSATION_INDEX.
Could you provide any guidance or insights on if this can be done and if so how? If this is not possible do you happen to know of any alternative properties that could provide the same functionality.

Thanks in advance!

Kind regards,
Alex

**Comment by Sicos1977** [comment]
I added a property to get the conversation id but that is doing almost the same as what you did. So there probably isn't an id inside the msg file to get. If you want you can sent me the file (zip it before sending) so that I can look inside it to see if the id is even in there.

You can sent the file to sicos2002@hotmail.com (ZIP the file before sending !!)

**Comment by AlexPeek01** [comment]
First off, thanks for the quick and detailed responses it has helped us a lot.
I was under the impression that the Conversation Index was the same as the Conversation Index which Microsoft Graph returns, but these appear to be different. 
It looks like as you mentioned that we can simply use the ConversationIndex/ThreadIndex for our problem.

Thanks again!
Alex

**Comment by Sicos1977** [comment]
Prima en succes met de rest :-)

**Comment by AlexPeek01** [comment]
Bedankt :D
