### ISSUE TITLE
File Nameless.txt as an attachment for digital signed emails

### ISSUE THREAD

**Issue by HartiRei** [Sicos1977/MSGReader#384]
I have a question about processing digital signed messages from Outlook:

When I save an email with an attachment (e.g. a pdf file) from Outlook (msg file) and open it with the MSGViewer, the pdf file is displayed as an attachment in the preview window.

If  the message is digital signed in Outlook, stored to the filesystem and opened with the MSGViewer, a file Nameless.txt is also displayed as an attachment.

Is this an expected behavior?

Thank you for your feedback on my question!

**Comment by Sicos1977** [comment]
Do you have a screenshot?

**Comment by HartiRei** [comment]
![MsgReader_Nameless_txt_Issue](https://github.com/Sicos1977/MSGReader/assets/48408509/ab6d3f61-1cca-40e0-b6ac-967fe00cac0e)

We created a digital signed message in Outlook without any content and without attachments.

**Comment by Sicos1977** [comment]
Is it possible to sent me that MSG file? Normally MSGReader only adds a file like that when it finds an attachment in the MSG file that has no file information. So for some reason an attachment like that is present.

Please ZIP the MSG file before sending it to sicos2002@hotmail.com

**Comment by HartiRei** [comment]
I have sent you an email with the msg file.

**Comment by Sicos1977** [comment]
I recieved you e-mail. I'll try to look into it this evening or otherwise tomorrow.

**Comment by Sicos1977** [comment]
Should be fixed in the latest nuget packages

**Comment by HartiRei** [comment]
Thanks for the fix, the message is now displayed as expected!

**Comment by Matti-Koopa** [comment]
Please reopen. Now signed messaged have no attachments at all. Revert to NuGet package version 5.5.1 fixed it.

**Comment by Sicos1977** [comment]
Can you also sent me that file so that I can test. I also flagged the package on nuget als one with critical bugs in it so people know they need to revert to the previous version.

**Comment by Matti-Koopa** [comment]
I sent you an e-mail

**Comment by Sicos1977** [comment]
Should be fixed in the latest version
