### ISSUE TITLE
[Request] Update Microsoft.IO.RecyclableMemoryStream dependency to 3.0

### ISSUE THREAD

**Issue by bokmadsen** [Sicos1977/MSGReader#389]
**Describe the bug**
MsgReader depends on Microsoft.IO.RecyclableMemoryStream, but in version 3 they removed .GetStream methods, causing MsgReader to fail

**To Reproduce**
- Update Microsoft.IO.RecyclableMemoryStream to version 3.0.0
- Instantiate Message with a MemoryStream: new Message(ms)
- Observe that MsgReader throws: System.MissingMethodException: 'Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'

**Expected behavior**
No exception should be thrown

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 120.0.6099.217

**Additional context**
Using .NET Framework 4.7.2

**Comment by Sicos1977** [comment]
Please update to the latest version, this one should have this fixed.
