### ISSUE TITLE
Issue with forwarding a forwarded email

### ISSUE THREAD

**Issue by jameslivsey** [Sicos1977/MSGReader#39]
When forwarding an email which has been forwarded I see this error message returned: 

ExceptionMessage":"The provided stream is not a valid IStorage\r\nParameter name: storageStream","ExceptionType":"System.ArgumentException","StackTrace":"   at MsgReader.Outlook.Storage..ctor(Stream storageStream, FileAccess fileAccess) in C:\\Users\\Kees\\Documents\\GitHub\\MsgReader\\MsgReader\\Outlook\\Storage.cs:line 196\r\n

and the thread from the previous email is not attached. 

Thanks!

James

**Comment by Sicos1977** [comment]
Can you send me the E-mail that is causing this problem? Send it to sicos2002@hotmail.com
Please zip the msg file before sending it.

Greetings,
Kees van Spelde
