### ISSUE TITLE
Strong Naming needed

### ISSUE THREAD

**Issue by Christian-Fenzl** [Sicos1977/MSGReader#392]
I'm using MSGReader within a MS Office AddIn which requires that the referenced assemblies all are using strong naming. Since version 4.5.5 of MSGReader this has been dropped.

Are there any chances to support strong naming again and why has it been dropped?

**Comment by Sicos1977** [comment]
I'm not adding back strong naming. It told other people that also raised an issue for this what the reason is not doing it.

More and more nuget packages don't support strong names anymore. If you support strong names then you also need packages from nuget that support it.
