### ISSUE TITLE
Determining inline attachments - 2

### ISSUE THREAD

**Issue by s-KaiNet** [Sicos1977/MSGReader#399]
**Describe the bug**
Basically, I experience exactly the same problem as described here - #319, but in the latest version - `5.5.5`. Seems some recent changes made to be reproducible again. I'm on .NET 8.

**To Reproduce**
See the linked issue.

**Expected behavior**
Correct property set is embedded attachment or not - `IsInline` on Attachment.

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/MsgReader/5.5.6
