### ISSUE TITLE
There is a typo on the dutch translation

### ISSUE THREAD

**Issue by Sicos1977** [Sicos1977/MSGReader#40]
Note to myself:

Opvolginsmarkering should be Opvolgingsmarkering

**Comment by MarcelMCT** [comment]
Sorry, ik schrijf het even in het Nederlands.

Class DomDocument.cs
"private void ReadHtmlContent(Reader reader)"

Onderstaande vetgedrukte code heb ik moeten toevoegen omdat anders bij bepaalde rtf documenten de eerste alinea met het lettertype symbol werd weergegeven.
De <span> werd geopend maar niet meer afgesloten.

                    case Consts.HtmlTag:
                        if (reader.InnerReader.Peek() == ' ')
                            reader.InnerReader.Read();

                        var text = ReadInnerText(reader, null, true, false, true);

                        _**//##CODE MT
                        if (spanTagWritten && text.StartsWith("<span")) {
                            stringBuilder.Append("</span>");
                            spanTagWritten = false;
                            fontIndex = null;
                            fontSize = null;
                            encoding = _defaultEncoding;
                        }**_

                        if (!string.IsNullOrEmpty(text))
                            stringBuilder.AppendLine(text);
                        break;

                    default:

**Comment by Sicos1977** [comment]
Ok, ik zal het opnemen in de code base en bedankt :+1:
