### ISSUE TITLE
System.TypeInitializationException: 'The type initializer for 'MsgReader.Rtf.Font' threw an exception.'

### ISSUE THREAD

**Issue by proskilly** [Sicos1977/MSGReader#401]
When I try to create a new Message object on a msg file that is based on a HTML email I get this error:

System.TypeInitializationException: 'The type initializer for 'MsgReader.Rtf.Font' threw an exception.'

ArgumentException: 'Windows-1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. Arg_ParamName_Name

Do you have any suggestions what I can do about it?

**Comment by Sicos1977** [comment]
Are you using .net core?

**Comment by proskilly** [comment]
.
