### ISSUE TITLE
Inline Attachments embedded in RTF Mails are corrupted

### ISSUE THREAD

**Issue by dominik1996** [Sicos1977/MSGReader#402]
**Describe the bug**
Inline Attachment embedded into RTF Mails seem to be corrupted when exporting them.
Attached is one of our [Files (Beispiel-E-Mail RTF.zip)](https://github.com/Sicos1977/MSGReader/files/15308882/Beispiel-E-Mail.RTF.zip) (as MSG in Zip).

**To Reproduce**
1. Using the sample Code below we extract the content of the Attachment.
2. We then convert this to base64 or export it as file
3. Neither the base64 string nor the exported file is valid (exported file won't open (on Windows) since it is corrupted)

```
var message = new Storage.Message(fileStream);
var attachmentsToExport = message.Attachments.OfType<Storage.Attachment>().ToList();

var attachment = attachmentsToExport.First();

// We then use attachment.Data to convert to base64 or to export as file
// File.WriteAllBytes(..)
// Convert.ToBase64String(..)
```

**Expected behavior**
As in Version 5.2.5 the images should be extracted correctly. 5.2.5 is the last Version that is working for us.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.5.7

**Additional context**
As described we receive an error while trying to open the file after export:
![image](https://github.com/Sicos1977/MSGReader/assets/62150176/37365cc9-46a8-42be-93da-9a06888eff93)

**Comment by Sicos1977** [comment]
I tried your example file but that one is working fine for me... the attachment is also extracted correctly.

**Comment by Sicos1977** [comment]
No response... closed
