### ISSUE TITLE
InitializeFromCultureId ends in exception (MsgReader.Outlook.Storage.Message.get_MessageLocalId())

### ISSUE THREAD

**Issue by mhuellwegen** [Sicos1977/MSGReader#410]
Dear Kees,

sometimes i got an exception when loading an Outlook Message caused by an invalid Culture.
In my case i try a mail send to me with CultureID 4096 (0x1000).

This is my original traced exception:

_Error: Die Kultur wird nicht unterstützt.
Parametername: culture
4096 (0x1000) ist ein ungültiger Kulturbezeichner.
   bei System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)
   bei MsgReader.Outlook.Storage.Message.get_MessageLocalId()
   bei GetMessageLocalId(Object )
   bei Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)_

If you like i can send you an original mail (directly to you for privacy reasons) causing this problem for easy debugging.

Regards,

Martin

**Comment by Sicos1977** [comment]
Hi Martin,

Please ZIP the file before sending it to sicos2002@hotrmail.com

Greetings,
Kees

**Comment by Sicos1977** [comment]
I probably will add a fallback scenario where it will just fall back to the culture on the system if the culture in the MSG file is invalid.

**Comment by mhuellwegen** [comment]
Hi Kees,

_> I probably will add a fallback scenario_
That's fine for me.

Did you receive my mail with the problematic e-mail?

**Comment by Sicos1977** [comment]
Yes, I did, try to look into it this weekend

**Comment by Sicos1977** [comment]
Should be fixed
