### ISSUE TITLE
Allow invalid separator value in SENT header

### ISSUE THREAD

**Issue by bokdamgaard** [Sicos1977/MSGReader#413]
**Describe the bug**
If the time in SENT header uses `.` instead of `:` in time part of the value, the conversion fails, returning DateTime.Min to .Headers.SentDate

**To Reproduce**
Call `Rfc2822DateTime.StringToDate("Sun, 19 May 2024 15.59.09 +0200")`

**Expected behavior**
A DateTime object with value <> DateTime.Min

**Desktop (please complete the following information):**
- OS: Windows 11 23H2
- Net Standard 2.0

**Additional context**
It would propably require a replacement of `.` to `:` as DateTime parsing will fail with `.`

**Comment by Sicos1977** [comment]
Do you have an example e-mail?

**Comment by bokdamgaard** [comment]
Not really, as it contains customer informations.
I can give you the header: `Date: Sun, 19 May 2024 15.59.09 +0200`

**Comment by Sicos1977** [comment]
Fixed
