### ISSUE TITLE
How to read/have access to Sent On Behalf details

### ISSUE THREAD

**Issue by azerios** [Sicos1977/MSGReader#418]
Dear,

I'm wondering the best method to get all sent on behalf details from an MsgEmail object.

Which headers should I look for, I want to have all ResentEmail details like in MimeKit library for Eml files ?

Regards

**Comment by Sicos1977** [comment]
If you want to process EML files it is better to just use MimeKit... or is your question about MSG files?

**Comment by azerios** [comment]
My question is about MSG files

**Comment by Sicos1977** [comment]
You can query the

```c#
/// <summary>
///     Returns the representing sender of the Message, null when not available
/// </summary>
// ReSharper disable once CSharpWarnings::CS0109
public new SenderRepresenting SenderRepresenting { get; private set; }
```

or you can just get the original e-mail headers through

```c#
/// <summary>
///     Returns the available E-mail headers. These are only filled when the message
///     has been sent accross the internet. Returns null when there aren't any message headers
/// </summary>
public MessageHeader Headers { get; private set; }
```
