### ISSUE TITLE
infinite Loop in FileExistsMakeNew

### ISSUE THREAD

**Issue by MatthiasKausW** [Sicos1977/MSGReader#42]
Hi,

the file name is derived from the mails subject.
If the length of file name and path equals or exceeds MaxPath (248 characters) the first ExtractToFolder runs as expected. 
The second call to ExtractToFolder with the same mail file loops infinitely in FileManager.FileExistsMakeNew because the shortened

I'd like to suggest to replace 

            while (File.Exists(tempFileName))
            {
                tempFileName = path + fileNameWithoutExtension + "_" + i + extension;
                tempFileName = validateLongFileName ? ValidateLongFileName(tempFileName, extraTruncateSize) : tempFileName;
                i += 1;
            }

by 

            while (File.Exists(tempFileName))
            {
                tempFileName = validateLongFileName ? ValidateLongFileName(tempFileName, extraTruncateSize) : tempFileName;
                fileNameWithoutExtension = GetFileNameWithoutExtension(tempFileName);
                tempFileName = path + fileNameWithoutExtension + "_" + i + extension;
                i += 1;
            }

Thanks!
Sincerely
Matthias

**Comment by Sicos1977** [comment]
Fixed
