### ISSUE TITLE
Question regarding SenderRepresenting object

### ISSUE THREAD

**Issue by azerios** [Sicos1977/MSGReader#420]
Dear,

Inside the SenderRepresenting object, the email address is an OU path like '/O=EX/OU=GROUP (XXXX)/CN=RECIPIENTS/CN='.

I use MSGraph client to download these email and sometimes convert them to eml files.

This value is the same in Headers list, so I'm wondering if it's possible to fix this behavior or I'll only display the name of that representing person.

Regards

**Comment by Sicos1977** [comment]
If you have a format like this than it is an e-mail address that is in active directory query format. The only thing that you can do is to query the active directory of your company to resolve the real e-mail address. If the e-mail came from an external party than you are out of luck and you can do nothing about it.

**Comment by Sicos1977** [comment]
https://stackoverflow.com/questions/456523/how-can-i-retrieve-active-directory-users-by-common-name-more-quickly
