### ISSUE TITLE
Hide nameless attachments in the header

### ISSUE THREAD

**Issue by brunohunziker** [Sicos1977/MSGReader#423]
Is it possible to hide the nameless attachments in the header?:
![image](https://github.com/user-attachments/assets/f6983bbe-ad77-4334-bf11-76efd9c261a0)

**Comment by Sicos1977** [comment]
Are you processing an MSG of EML file because it almost looks like those files are the HTML and TEXT body of an e-mail?

**Comment by brunohunziker** [comment]
Yes, it seams to be the HTML and TEXT body. 
Those technical attachments could confuse the user, because he/she is not aware of any "user level" attachments.

**Comment by Sicos1977** [comment]
Is it an eml file that you are viewing because normally you should not see the text and html body add attachments. 

Can you sent me the file so that I can have a look? Please zip the file before sending it to sicos2002@hotmail.com

**Comment by brunohunziker** [comment]
I mailed you the msg-file (zipped). If you don't have time to analyse the issue I could try to dig into the code myself.

Thanks!

**Comment by Sicos1977** [comment]
I have the msg file and also know where it goes wrong but still have to make some time to write a good solution for it. At the moment I'm trying to make a solution for this issues --> https://github.com/Sicos1977/MSGReader/issues/414

It is longer in the issue list so it has a higher priority.

**Comment by Sicos1977** [comment]
I think I fixed the other issue and will look into yours tommorrow or this weekend.

**Comment by brunohunziker** [comment]
Thanks! But take your time…

**Comment by Sicos1977** [comment]
Fixed in latest release
