### ISSUE TITLE
Unneeded span tag generated for first escaped character

### ISSUE THREAD

**Issue by henninggj** [Sicos1977/MSGReader#43]
Hi,

The first time the `DocDocument.ReadHtmlContent` method encounters an escaped character (e.g., `\'c6`) it generates a span tag with font styling which is not required (and also wrong, style-wise).

This RTF snippet (generated by Outlook 2013):
```
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {\htmlrtf0 X
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}\htmlrtf0

{\*\htmltag72 </p>}
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {\htmlrtf0 \'c6
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}\htmlrtf0

{\*\htmltag72 </p>}
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {\htmlrtf0 \'d8
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}\htmlrtf0
```

becomes:
```
<p class=MsoNormal>
X<o:p>
</o:p>
</p>
<p class=MsoNormal>
<span style = 'font-family:"Arial";font-size:12pt'>Æ<o:p>
</o:p>
</p>
<p class=MsoNormal>
Ø<o:p>
</o:p>
</p>
```
Complete RTF from msg file: [body.rtf.txt](https://github.com/Sicos1977/MSGReader/files/563833/body.rtf.txt) and HTML generated by MSGReader: [body.html.txt](https://github.com/Sicos1977/MSGReader/files/563834/body.html.txt).

The problem can be solved by removing the following code from `DocDocument.ReadHtmlContent`:
```
if (FontTable != null && fontIndex.HasValue && fontIndex <= FontTable.Count)
{
	// <span style = 'font-size:12.0pt;font-family:"Arial",sans-serif' >
	var font = FontTable[fontIndex.Value];
	if (!spanTagWritten)
	{
		stringBuilder.Append("<span style = 'font-family:\"" + font.Name + "\";");
		if (fontSize.HasValue)
			stringBuilder.Append("font-size:" + fontSize + "pt");
		stringBuilder.Append("'>");
		spanTagWritten = true;
		encoding = font.Encoding ?? _defaultEncoding;
	}
}
```
This have worked for my use cases so far and there does not seem to be any reason to treat escaped characters differently, at least for files generated by Outlook 2013.

Thanks!
Henning

**Comment by Sicos1977** [comment]
I will look into in this weekend.

**Comment by Sicos1977** [comment]
I tried to remove the code but that breaks some other test cases I have... so I'm going to leave the way as it is working now. I also don't see any differences in your examples.

![capture](https://cloud.githubusercontent.com/assets/6692947/20069250/1ef9fa7a-a51c-11e6-86c6-251805dc01df.PNG)

**Comment by henninggj** [comment]
Hi,

Thanks for checking this issue and sorry for the late reply (been sick).

The problem in my example is actually apparent in your screenshots: The letter "Æ" is bigger (12pt) on the browser because of the inserted span, whereas the other letters are 11pt as defined by the class MsoNormal.
I notice that only the first non-ascii letter has span applied to it. The following letters are correct because the variable `spanTagWritten` is then `true`.

In any case, the suggested change fixes my problem, so I will make a fork for that.

Best regards,
Henning
