### ISSUE TITLE
Encodings with Umlauts generate FormatException in DomDocument

### ISSUE THREAD

**Issue by reberinformatik** [Sicos1977/MSGReader#46]
Hi and thanks for this great library. I'm currently having problems with german msg-files. There seems to be an issue in https://github.com/Sicos1977/MSGReader/blob/master/MsgReader/Rtf/DomDocument.cs#L3345

(Rtf/DomDocuments.cs, line 3345). The hexBuffer is empty at this point, and therefore byte.Parse throws an exception. `reader.CurrentToken.Hex` however contains `0xFC` (a german Umlaut in 1252 encoding: 'ü'). If I add 
`if (hexBuffer == string.Empty)   
  hexBuffer = reader.CurrentToken.Hex;`
The code works, but the font-size changes at the Umlauts position.

Please see this testmail: link removed

**Comment by Sicos1977** [comment]
Please send me the msg file by e-mail and not through file-upload.net because that service is trying to install an trojan horse om my laptop. Please zip the file first and then send the file to sicos2002@hotmail.com.

**Comment by reberinformatik** [comment]
Sure thing! I sent you the mail to the given address. I’m also not a fan of such upload services, but github doesn’t seem to provide attachments…

Greetings,
Florian

Von: Kees [mailto:notifications@github.com]
Gesendet: Mittwoch, 18. Januar 2017 11:44
An: Sicos1977/MSGReader <MSGReader@noreply.github.com>
Cc: Reber Informatik GmbH <info@reberinformatik.ch>; Author <author@noreply.github.com>
Betreff: Re: [Sicos1977/MSGReader] Encodings with Umlauts generate FormatException in DomDocument (#46)


Please send me the msg file by e-mail and not through file-upload.net because that service is trying to install an trojan horse om my laptop. Please zip the file first and then send the file to sicos2002@hotmail.com<mailto:sicos2002@hotmail.com>.

**Comment by Sicos1977** [comment]
I fixed the issue and drafted a new release here on GitHub. I also published a new version to NuGet but that can take some time before you can download it.

Just for my own curiosity... for what are you using the msgreader?

Greetings,
Kees van Spelde

**Comment by reberinformatik** [comment]
Thanks for fixing the issue! I'm trying to use the MailViewer in a Citrix environment where no Outlook is installed. There are mail-messages stored in a DMS which are retrieved by my application. A double click should start the MailViewer component and display a preview of the mail.

Just wondering: Are there any known limitations/issues or format-problems?

**Comment by Sicos1977** [comment]
Not that I know... but since I don't have a complete testing farm like Microsoft has, there could be a bug here or there. But you can always file a bug report here on GitHub so that I can try to fix it :-)
