### ISSUE TITLE
Retrieve recipient/sender of the .msg 

### ISSUE THREAD

**Issue by sebailfico** [Sicos1977/MSGReader#47]
Hello,i've just installed your library via Nuget. First, thank you for your work.
I've successfully extracted the content of several `.msg` files and put them in separate folders.
I would like to access to the metadata of each message (i.e. recipient and sender addresses, mail subject, timestamps etc.) but I can't understand how to do it.
Thanks in advantage,
Sebastiano

**Comment by Sicos1977** [comment]
using (var msg = new MsgReader.Outlook.Storage.Message("d:\\testfile.msg"))
            {
                var from = msg.Sender;
                var sentOn = msg.SentOn;
                var recipientsTo = msg.GetEmailRecipients(Storage.Recipient.RecipientType.To, false, false);
                var recipientsCc = msg.GetEmailRecipients(Storage.Recipient.RecipientType.Cc, false, false);
                var htmlBody = msg.BodyHtml;
                // etc...
            }

**Comment by sebailfico** [comment]
Great, i think that should definitely be shown in examples!

Thanks a lot.
Regards
