### ISSUE TITLE
Include Localization files in nuget-package

### ISSUE THREAD

**Issue by reberinformatik** [Sicos1977/MSGReader#48]
I noticed, that the `MsgReader.resources.dll`s are missing in the nuget-package. Could you please provide the `de/MsgReader.resources.dll, fr/MsgReader.resources.dll` and so on in the nuget-package (or provide a way to localize the strings)?
Thanks a lot!

**Comment by Sicos1977** [comment]
I included them and published it on NuGet just a minute ago, you need version 2.0.5

**Comment by reberinformatik** [comment]
Thanks for this. Now it's working.
FYI: I submitted a pull request for an additional parameter: withHeaderTable (defaults to true), as I need to exclude the header tables from the mails in my program.
