### ISSUE TITLE
Array out of bound [MapiTagMapper]. rel. library 2.0.8.0

### ISSUE THREAD

**Issue by Nicosiajl** [Sicos1977/MSGReader#50]
Hi and thanks for this # great library.
I'm currently having problems with any msg-files. 
There seems to be an issue in https://github.com/Sicos1977/MSGReader/blob/master/MsgReader/Outlook/MapiTagMapper.cs#L95

I do not understand exactly which properties of the email throws an exception, 
but it seems that the array entryStreamBytes[] is not allocated correclty and is not big enough.

The exception returned in "Index was outside the bounds of the array."
could you help me?

Tnx Jljch 
best reguards

**Comment by Sicos1977** [comment]
Hi,

Can you send me one of the files that is giving you problems. Please zip this msg file first before sending it to sicos2002@hotmail.com

Greetings,
Kees van Spelde

**Comment by Nicosiajl** [comment]
Thanks so much.
I sent you a mail with file that throw the exception.
I tried with a bigger array and work fine; but I disabled the calculation of the property bytes and it's not good.

Greetings
Jljch

**Comment by Sicos1977** [comment]
I added an extra check to see if the calculated offset exists in the entryStream. This fixes your issue. It seems that your MSG files have invalid properties that reference an offset in the entryStream that does not exist.

**Comment by Nicosiajl** [comment]
Now Worked Fine.
Thank you very much, you are great
I will check my email downloader.

**Comment by Sicos1977** [comment]
+1:
