### ISSUE TITLE
msg attachments are broken from commit 77b81b5

### ISSUE THREAD

**Issue by mlsad3** [Sicos1977/MSGReader#51]
In commit 77b81b5 there is some refactoring done that removes a large block of code from Reader.cs. In this block of code, there is a check for attachments, and then attachments are added into the header. Now instead this block was removed and replaced with a very simplified version, ExtractMsgEmailHeader(message, hyperlinks), which does nothing with attachmentList. This change needs to be reverted or fixed.

**Comment by Sicos1977** [comment]
Fixed... see version 2.0.9
