### ISSUE TITLE
ArgumentException: Unrecognized structure in data format 'Rich Text Format'.

### ISSUE THREAD

**Issue by michaelcsikos** [Sicos1977/MSGReader#52]
Hi Kees

I have an e-mail which is throwing the above exception. The `CleanUpCharacters` method is not helping. As a .eml file the `Convert` method succeeds, but as a .msg it throws. I have attached both files:

[eml-and-msg.zip](https://github.com/Sicos1977/MSGReader/files/759412/eml-and-msg.zip)

Any help would be appreciated.

Kind regards
Michael

**Comment by michaelcsikos** [comment]
Also, for some reason when the second `ArgumentException` is thrown, it can't be caught by the calling application:

```
string[] fileNames;

try
{
    fileNames = reader.ExtractToFolder(fileName, TempFolder);
}
catch (Exception ex)
{
    // Entire app crashes before here
}
```

I think another `try catch` is needed when `textRange.Load(rtfMemoryStream, DataFormats.Rtf)` is attempted the second time.

**Comment by Sicos1977** [comment]
I will look into it this evening

**Comment by Sicos1977** [comment]
This is going to take some more time to figure out. For some reason the RTF is malformed somewhere so that the MSGReader can not parse out the HTML that is embedded into the RTF. If I look to the RTF is seems okay but still it fails. I will let you know when I find something.

**Comment by michaelcsikos** [comment]
I set up a loop and found that the first line which caused it to fail was:

`{\*\htmltag156 </span>}\htmlrtf }\htmlrtf0 \htmlrtf \par}\htmlrtf0`

I'm not at all familiar with RTF, though, so that's when I gave up and asked for help.

**Comment by Sicos1977** [comment]
Your issue is fixed, you need version 2.0.10

**Comment by michaelcsikos** [comment]
Thanks, Kees. It works.

**Comment by Sicos1977** [comment]
Your welcome
