### ISSUE TITLE
MSG made by Outlook has empty Attachment, throwing exception

### ISSUE THREAD

**Issue by mlsad3** [Sicos1977/MSGReader#53]
I have a Msg file (trying to see if I am allowed to upload) that was created by outlook (reproducible). This file causes PreProcessMsgFile to die at the following code:

    fileInfo = new FileInfo(FileManager.FileExistsMakeNew(outputFolder + attachmentFileName));
    File.WriteAllBytes(fileInfo.FullName, attach.Data);

The issue is `attach.Data` is `null`.
The file *does* have an attachment, and actually `message.Attachments.length==2`. The first attachment is good (pdf), but second attachment has filename of `Nameless`.

I've added the following `if() continue;`:

    if (attachment is Storage.Attachment)
    {
       var attach = (Storage.Attachment)attachment;
       if ( attach.Data == null )
          continue;
       attachmentFileName = attach.FileName;

**Comment by mlsad3** [comment]
Sorry, this is in Reader.cs

**Comment by Sicos1977** [comment]
Can you send me the file that is giving you this problem. Please zip it first before sending it to sicos2002@hotmail.com

**Comment by mlsad3** [comment]
You should have received msg.zip. Also of note, the other attachment is a bmp (ATT74780.bmp), which originally is Inline, but becomes Inline=false due to ContentId==null.

It's a bmp that is normally below user's signature (you can see it in Body as `<<Picture (Device Independent Bitmap)>>`, but in the rendered html, there is no attachment for this, and the html body does not have a link to the bmp. 

I'm not sure what the behavior is supposed to be for this

**Comment by mlsad3** [comment]
Actually, the html text shows it as:

   <IMG SRC="ATT-0-ATT74780" alt="Picture (Device Independent Bitmap)">

which looks pretty tough to match/replace when you iterate over each inlineAttachment

**Comment by mlsad3** [comment]
I've modified PreProcessMsgFile to be the following:

            if (htmlBody)
                foreach (var inlineAttachment in inlineAttachments.OrderBy(m => m.RenderingPosition))
                {
                    bool foundMatch;
                    string replacement;
                    if ( inlineAttachment.IconFileName != null )
                    {
                        replacement =
                            "<table style=\"width: 70px; display: inline; text-align: center; font-family: Times New Roman; font-size: 12pt;\"><tr><td>" +
                            ( hyperlinks ? "<a href=\"" + inlineAttachment.FullName + "\">" : string.Empty ) + "<img alt=\"\" src=\"" +
                            inlineAttachment.IconFileName + "\">" + ( hyperlinks ? "</a>" : string.Empty ) + "</td></tr><tr><td>" +
                            WebUtility.HtmlEncode( inlineAttachment.AttachmentFileName ) +
                            "</td></tr></table>";
                        body = ReplaceFirstOccurence( body, rtfInlineObject, replacement, out foundMatch );
                    }
                    else
                    {
                        replacement = "<img alt=\"\" src=\"" + inlineAttachment.FullName + "\">";
                        body = ReplaceFirstOccurence( body, rtfInlineObject, replacement, out foundMatch );
                    }
                    if ( !foundMatch )
                    {
                        replacement = "<img alt=\"\" src=\"" + inlineAttachment.FullName + "\">";
                        // Look for <IMG SRC="ATT-0-ATT74780" alt="Picture (Device Independent Bitmap)">
                        // Note, I've seen this without matching </IMG>, and need to check case-insensitive
                        var name = Path.GetFileNameWithoutExtension( inlineAttachment.AttachmentFileName );
                        Regex rx = new Regex(
                            "<IMG [^>]*SRC=\"ATT.*" + name + "\"[^>]*>(\\s*</IMG>)?",
                            RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase | RegexOptions.Singleline );
                        body = rx.Replace( body, replacement, 1 );
                    }
                }

Which required the following update to ReplaceFirstOccurence:

        private static string ReplaceFirstOccurence(string text, string search, string replace, out bool foundMatch)
        {
            var index = text.IndexOf(search, StringComparison.Ordinal);
            foundMatch = index >= 0;
            if ( !foundMatch )
            {
                return text;
            }
            return text.Substring(0, index) + replace + text.Substring(index + search.Length);
        }
