### ISSUE TITLE
Invalid Media Type On HeaderParser

### ISSUE THREAD

**Issue by AdamE87** [Sicos1977/MSGReader#55]
Hi Kees, 

Noticed a small issue on the HeaderParser for Mime Types.

When parsing the content-type in the `public static ContentType ParseContentType(string headerValue)` method i've had to add in the following line `  
// Check for illegal content-type
	                    var v = value.ToUpperInvariant();
	                    if (v.Equals("TEXT") || v.Equals("TEXT/"))
	                        value = "text/plain";
                        if (v.EndsWith("\0"))
                            value = v.Replace("\0", String.Empty);` << As some Content types are coming through with a "\0" suffix eg "IMAGE/GIF\0" which is causing an assignment error, removing the "\0" resolves the issue.

**Comment by Sicos1977** [comment]
I changed your code to this and updated the source on GitHub
```

                        // Check for illegal content-type 
                        var v = value.ToUpperInvariant().Trim('\0');
                        if (v.Equals("TEXT") || v.Equals("TEXT/"))
                            value = "text/plain";
```

**Comment by AdamE87** [comment]
Brilliant, thanks!
