### ISSUE TITLE
Storage.Attachment.DataStream?

### ISSUE THREAD

**Issue by Memphizzz** [Sicos1977/MSGReader#56]
Is it possible to expose the underlying Stream of Storage.Attachment.Data?
For checking the dimensions of an image for example this would be useful as you don't need to load the whole attachment into memory...

**Comment by Sicos1977** [comment]
What do you exactly mean ... because the Data property is public.

```
            /// <summary>
            /// Returns the data
            /// </summary>
            public byte[] Data
            {
                get { return _data ?? GetMapiPropertyBytes(MapiTags.PR_ATTACH_DATA_BIN); }
            }
```
