### ISSUE TITLE
Text translation sometimes translates from Dutch to (i think) Greece language

### ISSUE THREAD

**Issue by CCjoukevrossum** [Sicos1977/MSGReader#57]
Hi Kees,

The conversion of the e-mail is not always going well. Sometimes it converts Dutch written text to (what I think is) Greece.

Any clue what that might be?

Thanks!

Jouke van Rossum

**Comment by Sicos1977** [comment]
Can you send me the e-mail that is giving you this problem? Please zip the mail before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Can you please give me a reaction... otherwise I close this issue.

**Comment by CCjoukevrossum** [comment]
I’m waiting on a response with the e-mail which is having the issue since I can’t reproduce it. I’ll have one today.

**Comment by Sicos1977** [comment]
Okey that fine... I'll wait for that e-mail (ik zie hem wel verschijnen :-) )
