### ISSUE TITLE
Unable to load msg file

### ISSUE THREAD

**Issue by Spiralis** [Sicos1977/MSGReader#59]
Hi, I just tried to use this project to open some msg-files I was handed. 
But, somehow this does not work as it should. 

I am using the same code as in the readme:
```
using (var msg = new MsgReader.Outlook.Storage.Message("c:\\test.msg"))
{
        var from = msg.Sender;
        var sentOn = msg.SentOn;
        var recipientsTo = msg.GetEmailRecipients(Storage.Recipient.RecipientType.To, false, false);
        var recipientsCc = msg.GetEmailRecipients(Storage.Recipient.RecipientType.Cc, false, false);
        var subject = msg.Subject
        var htmlBody = msg.BodyHtml;
        // etc...
}
```
It fails when trying to read with the following exception:
`<System.ArgumentException: Object must be of type Int32.
   at System.Int32.CompareTo(Object value)`

I am attaching the zipped msg-file for you here. It was created with Outlook 2016: [Test.zip](https://github.com/Sicos1977/MSGReader/files/1011301/Test.zip)

Is there something I am doing wrong? Is Outlook 2016 supported? Are there anything special with the file I uploaded (encoding, language etc) that makes it hard/impossible to read? As far as I know it was created by saving/dragging it from Outlook onto the desktop, where Outlook suggested the msg extension.

**Comment by Sicos1977** [comment]
I tried your file over here but I do not have any problems opening your test file.

![image](https://cloud.githubusercontent.com/assets/6692947/26213006/af7bdc7c-3bf7-11e7-8e12-0238e9377b19.png)

**Comment by Spiralis** [comment]
Oh dear. My fault I was testing this via unit testing, and the method I tested is yielding and responding quite different results that my test expected.
 
Yes, I can indeed read the message as expected. Sorry for the extra trouble and thank you very much for your time on testing this.
