### ISSUE TITLE
MSGReader no longer shows attachments after converting to HTML

### ISSUE THREAD

**Issue by fuzemeister** [Sicos1977/MSGReader#60]
In previous versions of the MSGReader the HTML output showed the attachments of the e-mail. This no longer occurs.

I'm using version 2.0.0.0 of the MSGReader.

**Comment by Sicos1977** [comment]
I'll look into it this evening... it should work...

**Comment by Sicos1977** [comment]
Can you please try the latest version 2.0.11 (https://github.com/Sicos1977/MSGReader/releases/tag/2.0.11). Everything seems to work fine over here.
