### ISSUE TITLE
Inline Images

### ISSUE THREAD

**Issue by AdamE87** [Sicos1977/MSGReader#62]
Hi Kees,

Quick question on a particular line:

```
if (_data != null)
                        {
                            var length = _data.Length; //- 40; <------- HERE
                            var bytes = new byte[length];
                            Buffer.BlockCopy(_data, 0, bytes, 0, length); //<---Second parameter here too
                            using (MemoryStream inputStream = new MemoryStream(bytes))
                            using (var image = Image.FromStream(inputStream, true, true))
                            using (var outputStream = new MemoryStream())
                            {
                                image.Save(outputStream, ImageFormat.Png);
                                outputStream.Position = 0;
                                _data = outputStream.ToByteArray();
                                FileName = "ole0.bmp";
                            }
                        }
                        else
                            throw new MRUnknownAttachmentFormat("Can not read the attachment");
```
How come the default is 40? I've been getting ArgumentErrors on the `Image.FromStream` method and when i change the 40 to 0 (effectively) it works... but I guess there must be reason to your decision?

Thanks, Adam

**Comment by AdamE87** [comment]
This is from the `Attachment.cs` class Within `MsgReader.Outlook`

**Comment by Sicos1977** [comment]
I really don't know why I did that. I have to reread the u0002OlePres000 or CONTENTS specifications to see why I did make it like that. I'll try to look that up this weekend.

**Comment by AdamE87** [comment]
Kees,

Interestingly enough I'm now getting errors on other files where the offset of 40 seems to work!!

I've refactored the section of `Attachment.cs` to now try one, catch the try the other, can I put a pull request in?

**Comment by Sicos1977** [comment]
Is it possible to send me the images? I then try to find out if there is a way to detect if the offset is needed or not. You can send them to sicos2002@hotmail.com

**Comment by AdamE87** [comment]
Hi Kees,

Still having issues after all of that... I'd love to send you the emails (and/or images) but unfortunately they're confidential to my client so I can't. I can't pin it down to any particular sort of image...some have inline powerpoint slides, others standard images...I'm a bit lost! In the meantime i've just got a default catch which silently ignores and continues as I don't actually need it to write the image out! Not a long term solution though!

Thanks again, Adam.

**Comment by Sicos1977** [comment]
Hi Adam,

This is probably the way to read the OlePress000 type, but since I don't have an e-mail with this structure inside it I can't test it. I hope you can try to build a class that can read the data the correct way.

http://www.devsuperpage.com/search/Articles.aspx?G=10&ArtID=142729

Greetings,
Kees

**Comment by AdamE87** [comment]
Fantastic, I'll have a look at this when I get back Monday!

**Comment by Sicos1977** [comment]
Thanks and have a nice weekend.

**Comment by Sicos1977** [comment]
Any luck?

**Comment by AdamE87** [comment]
Hi Kees,

Sorry to keep you waiting, I've still not yet had a chance to look at this, I'll hopefully get some time Friday afternoon. I've currently had to concentrate efforts on another project. Apologies if you've been waiting on this!
