### ISSUE TITLE
Text/Plain output

### ISSUE THREAD

**Issue by fdncred** [Sicos1977/MSGReader#65]
This code seems to only produce HTML output. Is there a way to get only US-ASCII output?
```cs
    using (var streamReader = new StreamReader(fullFileName))
    {
        string _body = msgReader.ExtractMsgEmailBody(streamReader.BaseStream, hyperlinks: false, contentType: "text/plain; charset=us-ascii", withHeaderTable: true);
        File.WriteAllText(msOutputFileName, _body);
    }
```

**Comment by Sicos1977** [comment]
You mean you only want TEXT instead of HTML?

**Comment by fdncred** [comment]
Yes. I want to know everything, including headers, about the msg/eml file but I only want it in text. I see the BodyText property on MsgReader.Outlook.Storage.Message but I want *everything* in text.

**Comment by Sicos1977** [comment]
Why do you want to have it in text format, is it because you want to index things?

**Comment by fdncred** [comment]
The project requirements are to convert msg/eml to text. We then take the text and manipulate it for our needs. It has nothing to do with indexing.

**Comment by Sicos1977** [comment]
There is a class called `HtmlToText.cs` in the MSGViewer example programm on GitHub. I think this does do exactly what you want. You can use this class to convert HTML to TEXT

**Comment by fdncred** [comment]
I've seen this and it's a good start but it just converts HTML to TEXT. I'll play with it and see if it does part of what I need. Below are a couple of feature requests.
1. It would be nice to just have it in text without conversion. I figured setting my contentType to "text/plain; charset=us-ascii" would do the trick but no luck.
2. I also wish there were some helper method that would just dump the raw text contents of the msg/eml file instead of having to parse through a zillion properties and collections. 
Thanks for your help.

**Comment by Sicos1977** [comment]
Now a days most of the e-mails are send in HTML format so most of the time there is no text body available. In the MSGReader I focused on getting the HTML body instead of the text body. The MSGReader only tries to get the text body if there isn't an HTML body. You can change the code to always try to get the TEXT body first. It is not that hard to do.
