### ISSUE TITLE
Message as attachment -> crash

### ISSUE THREAD

**Issue by Chieleman** [Sicos1977/MSGReader#67]
When i try to serialize a message which has another message as attachment the serialization crashes with the error "Cannot convert 'Message' to 'Attachment'"

**Comment by Chieleman** [comment]
OK, got some mutated code, not the original from this github. closing the issue, sorry for the inconenience

**Comment by Sicos1977** [comment]
No problems, glad that you found it :-)

**Comment by Chieleman** [comment]
is there any way to save an instance of Storage.Message to file?

**Comment by Sicos1977** [comment]
How do you mean? Did you remove an attachment?

**Comment by Chieleman** [comment]
i have a Message which has another Message as attachment. I want to save this message to a .msg file

**Comment by Sicos1977** [comment]
`                if (attachment is Storage.Attachment)
                {
                    var attach = (Storage.Attachment)attachment;
                    if (attach.Data == null) continue;
                    attachmentFileName = attach.FileName;
                    renderingPosition = attach.RenderingPosition;
                    fileInfo = new FileInfo(FileManager.FileExistsMakeNew(outputFolder + attachmentFileName));
                    File.WriteAllBytes(fileInfo.FullName, attach.Data);
                    isInline = attach.IsInline;
....`

**Comment by Chieleman** [comment]
the point is that the attachment is not of type Storage.Attachment but of Storage.Message

**Comment by Sicos1977** [comment]
Sorry about that.... then you need this

```
                if (attachment is Storage.Message)
                // ReSharper restore CanBeReplacedWithTryCastAndCheckForNull
                {
                    var msg = (Storage.Message)attachment;
                    attachmentFileName = msg.FileName;
                    renderingPosition = msg.RenderingPosition;

                    fileInfo = new FileInfo(FileManager.FileExistsMakeNew(outputFolder + attachmentFileName));
                    msg.Save(fileInfo.FullName);
                }
```
