### ISSUE TITLE
Message.Appointment always null

### ISSUE THREAD

**Issue by Memphizzz** [Sicos1977/MSGReader#69]
Hi, 

I've tried checking a MeetingRequest, a MeetingResponse and a Appointment (saved from outlook calendar as msg), but every time I read the msg file, the Appointment object is null.

Am I doing something wrong or is this a known issue?

**Comment by Sicos1977** [comment]
I don't know. Can you send me the files so that I can check them. Please zip them before sending them to sicos2002@hotmail.com

Greetings,
Kees van Spelde

**Comment by Memphizzz** [comment]
@Sicos1977  Mail is on its way!

**Comment by Memphizzz** [comment]
Nevermind it works! I just realized that nuget did not update to the latest version. Was having this Issue when running version 2.0.10. Works fine in Version 2.0.14!

**Comment by Sicos1977** [comment]
👍
