### ISSUE TITLE
Security exception attempting to access registry

### ISSUE THREAD

**Issue by FuchsiaSoft** [Sicos1977/MSGReader#70]
When using MsgReader to get the content of a .msg file I sometimes get a security exception around access to the registry.

It only happens if the MsgReader lib is called when using Win32 impersonation with a user account that has no admin rights to the host machine (using the SimpleImpersonation wrapper), and from the stack traces it looked to only occur when the .msg was RTF, as the final method in the stack trace was a call to a Rtf to HTML converter.

The errors don't come up very often and I don't have a full log to hand, but wanted to raise it in case it's a known thing so I don't waste my time trying to dig it out.

If the stack traces etc. would be helpful I can get it all together, but if it's just some quirk of impersonation and not being able to use MsgReader in that scenario then no problem.

**Comment by Sicos1977** [comment]
My guess is that it probably happens somewhere in these code lines. I use a Windows control to convert RTF to XAML and then XAML to HTML. The user probably has no access to the component.

```
        #region Convert
        /// <summary>
        /// Do the actual conversion by using a RichTextBox
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times")]
        private void Convert()
        {
            var richTextBox = new RichTextBox();
            if (string.IsNullOrEmpty(_rtf))
            {
                _convertedRtf = string.Empty;
                return;
            }

            var textRange = new TextRange(richTextBox.Document.ContentStart, richTextBox.Document.ContentEnd);

            // Create a MemoryStream of the Rtf content
            try
            {
                using (var rtfMemoryStream = new MemoryStream())
                using (var rtfStreamWriter = new StreamWriter(rtfMemoryStream))
                {
                    rtfStreamWriter.Write(_rtf);
                    rtfStreamWriter.Flush();
                    rtfMemoryStream.Seek(0, SeekOrigin.Begin);

                    // Load the MemoryStream into TextRange ranging from start to end of RichTextBox.
                    textRange.Load(rtfMemoryStream, DataFormats.Rtf);
                }
            }
            catch (ArgumentException)
            {
                // Sometimes we have malformed RTF, in this case we try to clean it and convert it again
                using (var rtfMemoryStream = new MemoryStream())
                using (var rtfStreamWriter = new StreamWriter(rtfMemoryStream))
                {
                    var rtfCharArray = _rtf.ToCharArray();
                    CleanUpCharacters(rtfCharArray.Length, rtfCharArray);
                    _rtf = new string(rtfCharArray);
                    rtfStreamWriter.Write(_rtf);
                    rtfStreamWriter.Flush();
                    rtfMemoryStream.Seek(0, SeekOrigin.Begin);
                    // Load the MemoryStream into TextRange ranging from start to end of RichTextBox.
                    textRange.Load(rtfMemoryStream, DataFormats.Rtf);
                }
            }

            using (var rtfMemoryStream = new MemoryStream())
            {
                textRange = new TextRange(richTextBox.Document.ContentStart, richTextBox.Document.ContentEnd);
                textRange.Save(rtfMemoryStream, DataFormats.Xaml);
                rtfMemoryStream.Seek(0, SeekOrigin.Begin);
                using (var rtfStreamReader = new StreamReader(rtfMemoryStream))
                    _convertedRtf = ConvertXamlToHtml(rtfStreamReader.ReadToEnd());
            }
        }
        #endregion
```

**Comment by FuchsiaSoft** [comment]
Ok that explains it.

I'll set some time aside to do a fork and implement a full C# converter without the need for the control (probably based on this https://www.codeproject.com/Articles/27431/Writing-Your-Own-RTF-Converter)

Would you like a pull request back when I'm done or do you want to keep this using the control?

**Comment by Sicos1977** [comment]
I will gladly accept a pull request, the sooner the better that we get rid of this control :-). I just used that solution as a quick fix due to the lack of spare time.

**Comment by FuchsiaSoft** [comment]
Ok... so I've just had a look this morning at that code project article's source code.

There's a lot in there that we wouldn't need, but just taking the code needed to go from RTF to HTML it's quite a substantial amount of code.

I don't object to doing it, just want to check you want that embedding within MsgReader as it's a good few thousand lines of code.

I've attached the VS 2015 code map so you can see the level of complexity we'd be adding to the library.

Alternative would be to just make a standalone .dll and reference it, but it's quite nice that MsgReader doesn't have dependencies on NuGet.

![rtf_to_html_code_map](https://user-images.githubusercontent.com/6933750/30583521-331be526-9d1f-11e7-947d-2596204a3955.png)

**Comment by Sicos1977** [comment]
I'm okay with including it into MSGReader

**Comment by FuchsiaSoft** [comment]
Just want to say I've not forgotten about this... been pulled into something pressing at work so will pick this back up when I'm free :)

**Comment by Sicos1977** [comment]
No worries... I also forgot it :-)

**Comment by FuchsiaSoft** [comment]
I've got most of this done now, with some unit tests to make sure it's working properly after replacing the richtextbox.

But the rtf conversion source is using a class from System.Web which is unavailable to .Net 4 client profile and requires the full framework.

I can refactor it to remove that dependency (it's used to avoid having lookups for HTML tags) but if there's no reason it must be client profile then would be easier to change to full .net 4

So, do you want this keeping as client profile or is it OK to change?

**Comment by Sicos1977** [comment]
Well if I remember correctly I changed to client profile because someone requested it so that he/she could use it in his/her project. But I also want to upgrade the code to a newer .NET version since 4 is already very old and not supported anymore.... with other words... get rid of the clientprofile :-)

**Comment by FuchsiaSoft** [comment]
Cool you have a pull request now.

I opened one by mistake before I merged back to master of my fork... so closed that and opened a fresh one.

Merges cleanly, appveyor passes and there are unit tests for you to verify

**Comment by Sicos1977** [comment]
I merged it, ran some test and it looks fine to me. I also update the Nuget package to version 2.1
