### ISSUE TITLE
Sender.Email attribute not populated

### ISSUE THREAD

**Issue by mjefim** [Sicos1977/MSGReader#71]
We are using your solution for extracting data from Outlook messages. We ran into an issue while users are using an Exchange server, where the msg.Sender.Email attribute is empty, on the other hand, the msg.Sender.DisplayName is populated correctly.

To be more precise, the issue only happens when trying to parse a message that was sent internally, within the Exchange server (to a coworker) and only when taking it from the Sent folder. In case the same message is let's say transferred to the Inbox folder the issue does not appear.

We have also tried some other available solutions for overcoming this issue but none have been successful thus far, hence our belief that the problem lies within the Exchange.

We are interested if you have met this issue before and whether there is any solution for it? Furthermore, we did notice in this scenario that the attribute LastModifierName is populated with the correct information - can you please provide some information regarding this attribute and if it is valid for us to use it in this scenario as a solution?

Your help is much appreciated.

Kind Regards

**Comment by Sicos1977** [comment]
Can you send me the msg (email) file that is giving this problem? Please zip it before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
Can you give me some response otherwise I will close this issue

**Comment by mjefim** [comment]
I have sent the sample email one more time to the provided address, did so yesterday already it seems there is some issue. Please let me know if you do not receive it.

**Comment by Sicos1977** [comment]
I still didn't get an E-mail. I also checked the spam folder but also nothing there.

**Comment by mjefim** [comment]
Can you recheck for the mail, I sent it yet again?

**Comment by Sicos1977** [comment]
Yeah now I got it

**Comment by Sicos1977** [comment]
Hi,

I checked the message and my first assumption is the correct one. The PR_SENDER_EMAIL_ADDRESS_W field contains the active directory part to lookup the E-mail address. The best thing you can do in this case is query the e-mail address from the active directory, but remember that this only works when you do it inside the company where the e-mail is made. So if it got send across the internet then it won't work. Another thing what you could do is read the InternetAccountName field but this is no guarantee to get the correct e-mail address.

Greetings,
Kees van Spelde

**Comment by FuchsiaSoft** [comment]
I've actually come across this too and was planning on adding an extension or overload to attempt resolving against AD.

Not sure if we need it yet for our projects but if I do make it I'll share.

**Comment by Memphizzz** [comment]
I already did this, feel free to use these classes: https://gist.github.com/Memphizzz/6b490ca8e2477704a30f56ca0d489575 

I use them in a foreach loop of my Recipients like this:
```
 _recipients = new List<ActiveDirectoryInfo>();
                    foreach (var recipient in base.Recipients) //MSGReader Recipients
                    {
                        if (recipient.AddressType == "EX" && !recipient.Email.IsValidEmail())
                            _recipients.Add(ADHelper.GetActiveDirectoryInfo(recipient));
                        else
                            _recipients.Add(new ActiveDirectoryInfo(recipient));
                    }
```
where IsValidEmail is just this simple extension:
 ```
public static bool IsValidEmail(this string s)
        {
            try
            {
                if (String.IsNullOrWhiteSpace(s))
                    return false;

                new MailAddress(s);
                return true;
            }
            catch (FormatException)
            {
                return false;
            }
        }
```
HTH MemphiZ

**Comment by zaryk** [comment]
If you save a draft (or Click Reply, then save), both the DisplayName and Email Address look to be missing.  The LastModifierName is also populated with correct email address, myself being the one who last modified it.

**Comment by letdowncrush** [comment]
@Sicos1977 I'm having a similar issue.

I've noticed that in some scenarios, such as saving an email from the sent folder in Outlook, the sender mail is either null or populated with some FQDN, e.g. /o=Exchange/ou=Exchange Group /cn=etc.

I don't know a whole lot about .MSG file format but when I unzipped the file, I found what looks like the sender email in the __substg1.0_5D0A001F file. 

If I modify the Message.SetEmailSenderAndRepresentingSender method to look up the sender using 5D0A it seems to come through.

Thoughts?

**Comment by Sicos1977** [comment]
I don't know everything about the MSG format... the specs pdf is more then 1000 pages. So if you found out that it is stored in that stream then I'm happy to receive a pull request to incorporate that into the MSGReader.

**Comment by mjefim** [comment]
I've taken a look into the LastModifierName and it seems to offer correct information in our particular case. I am worried though that it may not work correctly in other possible situations - can you please provide or point me in direction of more information regarding this property. Is it safe to use it as a fallback when Email.Sender is not available? Can you see any scenarios where it could cause issues?

**Comment by Sicos1977** [comment]
The last modifier is the last person who modified the msg file, it doesn't have to be the original sender..... most of the time it probably is but I would not bet on it.
