### ISSUE TITLE
NuGet package 2.1 not working

### ISSUE THREAD

**Issue by FuchsiaSoft** [Sicos1977/MSGReader#74]
Release 2.1 (https://github.com/Sicos1977/MSGReader/releases/tag/2.1)

The nuget package is not working now following the changes made to resolve issue #70 

I've tested it by adding the compiled .dll manually as a reference and it works fine, so something with the nuget packaging specifically.

Attached a sample project with the nuget added.
[MsgReaderNugetTest.zip](https://github.com/Sicos1977/MSGReader/files/1409924/MsgReaderNugetTest.zip)

**Comment by XplittR** [comment]
When upgrading from 2.0.14 to 2.1.0.0, the following happened to my solution:

packages.config:
Changed from:
`<package id="MSGReader" version="2.0.14" targetFramework="net46" />`
to:
`<package id="MSGReader" version="2.1.0.0" targetFramework="net46" />`

(Ok change)


But project.csproj:
Changed from:
`<Reference Include="MsgReader, Version=2.0.15.0, Culture=neutral, PublicKeyToken=47f99f3a9a2648df, processorArchitecture=MSIL">
      <HintPath>..\packages\MSGReader.2.0.14\lib\MsgReader.dll</HintPath>
    </Reference>`
to:
Nothing. It just got removed...

**Comment by Memphizzz** [comment]
I just noticed this as well, thas would be great @Sicos1977. Thanks in advance!

**Comment by Sicos1977** [comment]
This is fixed with the 2.1.1 release https://www.nuget.org/packages/MSGReader/
