### ISSUE TITLE
Converting msg to mime (eml) format?

### ISSUE THREAD

**Issue by dannylindquist** [Sicos1977/MSGReader#78]
Hey just found this library and it looks awesome! I realize this might be outside the purpose of the library, but I was wondering if it supports the conversion of msg files to eml files? Or if you know of a way to map one to the other?

Thanks in advance.

**Comment by Sicos1977** [comment]
Well I never wrote code to convert msg to eml but I did write code to convert eml to msg. So it should not be to hard for you to add this kind of functionality to the msgreader. I'm happy in getting a pull request for this :-)

See this code over here about how to convert an eml to msg.
https://github.com/Sicos1977/MsgKit/blob/master/MsgKit/Converter.cs

**Comment by dannylindquist** [comment]
Thank you so much for your response. This is now on my list of things to do.
