### ISSUE TITLE
"The provided stream is not a valid IStorage" exception on eml files

### ISSUE THREAD

**Issue by surrendert** [Sicos1977/MSGReader#82]
I am getting the "The provided stream is not a valid IStorage" exception in the Storage constructor when I try to open an eml file. 

I have used the unit test of the sample project:

using (Stream fileStream = File.OpenRead("SampleFiles\\RtfSampleEmail.msg"))            
{
                Reader msgReader = new Reader();
                string content = msgReader.ExtractMsgEmailBody(fileStream, true, null);              
               content = _htmlSimpleCleanup.Replace(content, string.Empty);
                Assert.IsTrue(content.Contains(_sampleText));           
}

When I open the eml file on Outlook and save it to an msg file the processing works fine. Does someone know what went wrong? Also other people on Google seems to have this issue and so far no one know a solution.

**Comment by Sicos1977** [comment]
You cannot extract data from an eml file with ExtractMsgEmailBody. You need the method WriteEmlStreamEmail for that
