### ISSUE TITLE
ExchangeID from Recipient and Sender

### ISSUE THREAD

**Issue by Memphizzz** [Sicos1977/MSGReader#83]
Hi,

would it be possible to get the ExchangeID/ADString for Recipients and Sender?
We did find the SenderRepresenting property, is this the correct way of getting the Sender ExchangeID?

Thanks in advance!

**Comment by Sicos1977** [comment]
Yes this is possible, if it is in the MSG file then it is possible to get it. Can you send me some example mails so that I can peek inside to see where the data is.

Sorry for the long delay on this message but I was on a holiday :-)

**Comment by Sicos1977** [comment]
Due to no response I closed this issue. Please reopen it when needed.
