### ISSUE TITLE
Read a MemoryStream containing a msg

### ISSUE THREAD

**Issue by androidrafbran** [Sicos1977/MSGReader#85]
Hi,
is it possible to parse a MemoryStream or the only way is to save it locally then parse the msg file?
If I try to parse a MemoryStream using the Storage.Message(stream) constructor it says "_The provided file is not a valid IStorage_".
Thanks

**Comment by Sicos1977** [comment]
Better late then never, yes you can.

```csharp
using (var stream = File.Open(inputFile, FileMode.Open, FileAccess.Read))
using (var message = new Storage.Message(stream))
....
```
