### ISSUE TITLE
Use of STGM_SHARE_EXCLUSIVE creates a problem for current usage

### ISSUE THREAD

**Issue by codingbloke** [Sicos1977/MSGReader#86]
In MsgReader.Outlook.Storage the constructor uses this line of code:

```csharp
            NativeMethods.StgOpenStorage(storageFilePath, null,
                accesMode | NativeMethods.STGM.SHARE_EXCLUSIVE, IntPtr.Zero, 0, out fileStorage);
```
Hence if two separate threads attempt to open the same .msg one gets a NULL in the fileStorage (which should probably be reported better).   Is there a reason exclusive access is used even when readonly access is request.  

It seems it would be better if STGM.SHARE_DENY_WRITE were specified when Read only is used and only specify SHARE_EXCLUSIVE when Write access is requested.  This would allow multiple threads and processes to read the same msg file at the same time.

**Comment by Sicos1977** [comment]
I changed the code to use STGM.SHARE_DENY_WRITE. There was never a reason to use STGM.SHARE_EXCLUSIVE. It was just there and it worked for me :-)
