### ISSUE TITLE
Not able to read the Contact Information

### ISSUE THREAD

**Issue by perumalsamya** [Sicos1977/MSGReader#88]
I am using the below code
            using (var msg = new MsgReader.Outlook.Storage.Message("test.msg"))
            {
               // The below code gives me always null
                var contact = msg.Contact;
            }
Let me know what I am missing.

**Comment by Sicos1977** [comment]
The contact information is only set when the msg file is of the type IPM.Contact

**Comment by perumalsamya** [comment]
Sorry... It was my fault. 
You have done a awesome work.
