### ISSUE TITLE
BodyText null

### ISSUE THREAD

**Issue by chrisintegro** [Sicos1977/MSGReader#89]
Hi, When I parse the MSG file with MSGReader I want to get just the text from the body.  However the BodyText property is null when there is HTML/Rich Text in the email body.  Is there anyway to get the plain text?
```
using (var msg = new MsgReader.Outlook.Storage.Message(fileInputName)){
                var emailMsg = new EmailMsg();

                var subject = msg.Subject;
                Console.WriteLine("Subject: " + subject);
                emailMsg.Subject = subject;

                //Problems, need to just get the text of the email, but BodyText doesn't work if there's HTML???
                //Parse the Body/Bottom too.
                var bodyText = msg.BodyHtml;
                var bodyText2 = msg.BodyText;
                Console.WriteLine("Body: " + bodyText);
                emailMsg.Body = bodyText;
}
```

**Comment by Sicos1977** [comment]
If the BodyText property is null then the bodytext is just not there.

**Comment by mlsad3** [comment]
I am doing the following with .eml files: 
            var msgReader = new MsgReader.Reader();
            bool isHtml;
            var body = MsgReader.Reader.GetBodyOnly( fullPame, out isHtml );
            if ( isHtml )
            {
                // http://stackoverflow.com/a/732110/277601
                body = Regex.Replace( body, @"<[^>]+>", "" );
                body = System.Net.WebUtility.HtmlDecode( body );
            }

...that said, I am not sure if I have modified MsgReader for certain situations where GetBodyOnly doesn't work. Will have to look into that later
