### ISSUE TITLE
Request to make 'HeaderExtractor' public

### ISSUE THREAD

**Issue by Sharpiro** [Sicos1977/MSGReader#91]
I was wondering if you'd be open to making the 'HeaderExtractor' class public instead of internal.

Being able to parse those headers can be useful in the event you already have the headers text and do not need to open an MSG file to get them.

https://github.com/Sicos1977/MSGReader/blob/9ec031d0f94781d73acfb543eede40f0832f993a/MsgReader/Mime/Header/HeaderExtractor.cs#L14

**Comment by Sicos1977** [comment]
Sure why not, see commit #eca8870

**Comment by Sharpiro** [comment]
awesome, thanks
