### ISSUE TITLE
Filenames for Attachments in ExtractToStream

### ISSUE THREAD

**Issue by Richardsonke** [Sicos1977/MSGReader#94]
As far as I can tell, there's no way programmatically to get the filenames for the attachments when you use ExtractToStream().  All you get is a collection of Streams.  Is that correct?  If I created a pull request with an overload that provided those, would you be interested?

**Comment by Sicos1977** [comment]
Yes I would.

**Comment by Sicos1977** [comment]
Closing due to no response.
