### ISSUE TITLE
BodyHTML missing images

### ISSUE THREAD

**Issue by rmr964** [Sicos1977/MSGReader#95]
Hi,

Firstly, many thanks for sharing your project. It's a god send!

I've got a MSG file that I preview using the .NET WebBrowser control and it has embedded images. When I load the message into the MsgReader and view the BodyHTML as an HTML page, the images are missing. 

My VB .NET Code is:

       With New MsgReader.Outlook.Storage.Message(File.OpenRead(tmpFileName))
                sentOn = .SentOn
                recipientsTo = .GetEmailRecipients(MsgReader.Outlook.Storage.Recipient.RecipientType.To, False, False)
                recipientsCc = .GetEmailRecipients(MsgReader.Outlook.Storage.Recipient.RecipientType.Cc, False, False)
                emailSender = .Sender.Email
                subject = .Subject
                bodyHTML = .BodyHtml               
                'bodyRTF = .BodyRtf
                FromEmail = .Sender.Email
                FromDisplayName = .Sender.DisplayName
            End With

Any clues as to where I'm going wrong?

Many Thanks

**Comment by swsch** [comment]
Embedded as in

        html + attachments like so:
        <img src="cid:=2D5AE3E3.01D3AE2B.0F460C34.74519108_csseditor"><br>

or as in

        html with "pure" inline images like so:
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

In  the first case, I'd guess that the browser control can't find the 
attachment,  in  the second case it could be because the control does 
not support data uris.

s.


"rmr964" <notifications@github.com>, 10.03.2018, 16:27:


Hi,
Firstly, many thanks for sharing your project. It's a god send!
I've got a MSG file that I preview using the .NET WebBrowser control and it has embedded images. When I load the message into the MsgReader and view the BodyHTML as an HTML page, the images are missing.
My VB .NET Code is:
   With New MsgReader.Outlook.Storage.Message(File.OpenRead(tmpFileName))
            sentOn = .SentOn
            recipientsTo = .GetEmailRecipients(MsgReader.Outlook.Storage.Recipient.RecipientType.To, False, False)
            recipientsCc = .GetEmailRecipients(MsgReader.Outlook.Storage.Recipient.RecipientType.Cc, False, False)
            emailSender = .Sender.Email
            subject = .Subject
            bodyHTML = .BodyHtml               
            'bodyRTF = .BodyRtf
            FromEmail = .Sender.Email
            FromDisplayName = .Sender.DisplayName
        End With
Any clues as to where I'm going wrong?
Many Thanks

**Comment by rmr964** [comment]
Hi,

 

Many thanks for your quick reply. 

 

The images are attached as 

 

<img width="150" height="155" style="width:1.5625in;height:1.6145in" id="Picture_x0020_2" src="cid:image001.jpg@01D3B5E9.8AFC3BF0" alt="LOGO COLOR - SMALL">

 

The images are showing in the WebBrowser control, but when I use the VS debugger and use the HTML visualiser to inspect the .BodyHTML property, I don’t see the image

 



 

If I inspect the WebBrower1.DocumentText, I can see the image in the HTML visualizer

 

Regards

**Comment by swsch** [comment]
As far as I can tell, .BodyHTML includes only the message body,
i.e "what was typed". The images should show up in the attachments of the message.
If the Visualizer is only provided with the former, I can understand
why the latter won't render.

How are you setting WebBrowser1.DocumentText?

**Comment by rmr964** [comment]
I’m loading the message into the WebBrowser using the following code. I think the key thing is that all the embedded files are also extracted into the temp folder

 

  Dim tempFolder As String = Nothing

                Try

                    tempFolder = GetTemporaryFolder()

                    _tempFolders.Add(tempFolder)

                    Dim msgReader As MsgReader.Reader = New MsgReader.Reader

                    Dim files As String() = msgReader.ExtractToFolder(tmpFileName, tempFolder, True)

                    Dim errormsg As String = msgReader.GetErrorMessage

                    If Not String.IsNullOrEmpty(errormsg) Then

                        Throw New Exception(errormsg)

                    End If

 

                    If Not String.IsNullOrEmpty(files(0)) Then

                        WebBrowser1.Navigate(files(0))

                    End If

 

 

                Catch ex As Exception

                    If ((Not (tempFolder) Is Nothing) _

                AndAlso Directory.Exists(tempFolder)) Then

                        Directory.Delete(tempFolder, True)

                    End If

 

                    MessageBox.Show(ex.Message)

                End Try

 

Whereas I’m just using the following to load the message into Storage

 

      With New MsgReader.Outlook.Storage.Message(File.OpenRead(tmpFileName))

 

 

The difference between the two in the HTML source is :

 

Storage:

<img width="150" height="155" style="width:1.5625in;height:1.6145in" id="Picture_x0020_2" src="cid:image001.jpg@01D3B5E9.8AFC3BF0" alt="LOGO COLOR - SMALL">

 

WebBrowser1:

 

<img width="150" height="155" style="width:1.5625in;height:1.6145in" id="Picture_x0020_2" src="C:\Users\suppo\AppData\Local\Temp\b004ce9a-a36f-4feb-b0b0-479f096c5682\image001.jpg" alt="LOGO COLOR - SMALL">

 

 

Thanks

**Comment by Sicos1977** [comment]
Sorry for the late response but I was on a skiing holiday. Did you try to view the msg file with the MSGViewer that is part of this GitHub project?

**Comment by Sicos1977** [comment]
No response... closed

**Comment by ferronsw** [comment]
I'm having the same problem. The images are referenced as follows within the body:

`
<img border="0" width="176" height="193" style="width:1.8333in;height:2.0104in" id="_x0000_i1028" src="cid:image004.jpg@01D5090A.4EC453F0" alt="logo">
`

I'm opening an eml file and saving it as a html file to view it within an iframe on my website.
Do you have any suggestion on how to include these images in the html file?

**Comment by swsch** [comment]
If you can get to the image data, https://css-tricks.com/data-uris/ comes to mind for embedding images into HTML files

**Comment by ferronsw** [comment]
@swsch I saw that comment but didn't think it would help me. You're suggesting that I should write some logic to replace the "cid" url with the image data url?

**Comment by swsch** [comment]
yes. "include these images in the html file" comes down to that if you want a "stand-alone" HTML file with images. If MSGReader does not have a builtin function to do that, you'll have to implement it yourself. I wonder if Sicos1977 would accept a push request with that functionality ;->

If your requirements allow saving and referencing the images as external files, you would still need to rewrite the `src` attribute but save the worry about encoding the image data.

**Comment by cjames9001** [comment]
For what it’s worth I did this exact same thing. I looped through the images, created the data uri, replaced the src tag where the cid matched the image I created the data uri for. So it’s definitely a workable solution.

**Comment by ferronsw** [comment]
@cjames9001 good to know! Do you have a sample? Thx!

**Comment by eeskildsen** [comment]
Here's how I did it....

Dependencies:

* AngleSharp (https://www.nuget.org/packages/AngleSharp)
* MsgReader

Code:

```
using System.Linq;
using AngleSharp.Html.Dom;
using AngleSharp.Html.Parser;
using System.Text.RegularExpressions;
using AngleSharp;

static string ConvertMessageToHtmlWithInlineImages(string filePath)
{
    using MsgReader.Outlook.Storage.Message message = new(filePath);

    HtmlParser parser = new();
    using IHtmlDocument document = parser.ParseDocument(message.BodyHtml);

    var imagesAndAttachments = document.Images
        .Where(image => image.Source.StartsWith("cid:", StringComparison.InvariantCultureIgnoreCase))
        .Join(message.Attachments.Cast<MsgReader.Outlook.Storage.Message.Attachment>(), image => Regex.Match(image.Source, @"(?<=cid:).+?(?=@)")?.Value, attachment => attachment.FileName, (image, attachment) => (image, attachment));

    foreach (var imageAndAttachment in imagesAndAttachments)
    {
        string imageDataBase64 = System.Convert.ToBase64String(imageAndAttachment.attachment.Data);
        imageAndAttachment.image.Source = $"data:{imageAndAttachment.attachment.MimeType};base64,{imageDataBase64}";
    }

    return document.ToHtml();
}
```

**Comment by MKoen** [comment]
Thank you,@eeskildsen! It works!
