### ISSUE TITLE
Out of Memory Exception on Larger Attachments

### ISSUE THREAD

**Issue by darshanaspinx** [Sicos1977/MSGReader#96]
Hi,

When I use the MSGReader against a msg file with a larger attachment (181 MB), the library fails to load the attachment and throws a "Out of memory Exception".  I believe this has nothing to do with the computer's RAM (16GB). I may be wrong.. Please guide me on this.

Thanks.

![msgreaderbug](https://user-images.githubusercontent.com/7392557/37812760-c967714e-2eb5-11e8-8b45-471ee98e856c.png)

**Comment by Sicos1977** [comment]
Well this has to do with how .NET works. When something is loaded into a byte array then .NET tries to reserve a memory block on the HEAP. When this HEAP is fragmented then you can get a out of memory exception even if you have tons of memory in your pc.

See this for more information --> https://stackoverflow.com/questions/5250039/large-object-heap-fragmentation-clr-has-any-solution-to-it

What you can try to do is to force a garbage collection and then try again.
