### ISSUE TITLE
.msg missing smime.p7s file when email is signed

### ISSUE THREAD

**Issue by mickeycek** [Sicos1977/MSGReader#97]
If I open signed .eml message, there is "smime.p7s" with email signature and certificates in Attachments. But if i open signed .msg message, the signature file is missing.

I need to receive signatures AND certificates from file (not just basic information like SignatureIsValid, SignedOn, SignedBy).

**Comment by Sicos1977** [comment]
I never made an option to expose the certificate, just the SignedOn, SignedBy... properties so that you can validate when the message is signed and who did that. 

Can you send me the MSG file so that I can see if it is easy to expose the certificate.
Please send it to sicos2002@hotmail.com

**Comment by mickeycek** [comment]
I have sent you example on your mail.

**Comment by Sicos1977** [comment]
No not yet. I'll try to look into it this weekend

**Comment by Sicos1977** [comment]
I have added a property called SignedCertificate that exposes the certificate that is used when an E-mail is signed. Please get the latest source from GitHub and see if that solves your problem.

**Comment by mickeycek** [comment]
This is what i need.

Thank you,

Miha
