### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'MsgReader.resources ...

### ISSUE THREAD

**Issue by mickeycek** [Sicos1977/MSGReader#98]
I have posted my issue with this library on stackoverflow.

https://stackoverflow.com/questions/49570133/system-io-filenotfoundexception-could-not-load-file-or-assembly-resources

**Comment by Sicos1977** [comment]
Can you send me the file that is giving you the issue? Please send it to sicos2002@hotmail.com

**Comment by mickeycek** [comment]
It's not a specific message. I tried the same message after recycling application pool and then it worked.

**Comment by mickeycek** [comment]
Why was this closed? The issue is still there. After a while the service throws exception again. Recycling application pool is just a temporary solution.

**Comment by swsch** [comment]
I guess that the real *issue* concerning MSGReader is that the en-US locale seems to be missing.

Going by the stack trace, OPs *problem* is that his code is passing along a NULL MessageHeader.

**Comment by Sicos1977** [comment]
The en-US should not be missing. The reason why there is no dll for that is because en-US is the default language... so that should be compilated into the MSGReader.dll assembly itself.
