### ISSUE TITLE
ArgumentException with special eml file

### ISSUE THREAD

**Issue by gitgordon** [Sicos1977/MSGReader#99]
Hello,

if I try to open a eml file with MsgReader.Mime.Message an ArgumentException is thrown. With Thunderbird and Outlook I can open this file.

MSGReader Version: v2.1.3

Testfile 1: <https://raw.githubusercontent.com/redmine/redmine/master/test/fixtures/mail_handler/outlook_web_access_2010_html_only.eml>
Testfile 2: <https://raw.githubusercontent.com/redmine/redmine/master/test/fixtures/mail_handler/outlook_2010_html_only.eml>

German exception message: Die Zeichenfolge kann kein Minuszeichen enthalten, wenn die Basis nicht 10 ist.
Translated exception message: The string cannot contain a minus sign if the base is not 10.

StackTrace:
`System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
System.Convert.ToByte(String value, Int32 fromBase)
MsgReader.Mime.Decode.QuotedPrintable.DecodeEqualSign(String decode) 
MsgReader.Mime.Decode.QuotedPrintable.Rfc2047QuotedPrintableDecode(String toDecode, Boolean encodedWordVariant) 
MsgReader.Mime.Decode.QuotedPrintable.DecodeContentTransferEncoding(String toDecode) 
MsgReader.Mime.MessagePart.DecodeBody(Byte[] messageBody, ContentTransferEncoding contentTransferEncoding) 
MsgReader.Mime.MessagePart.ParseBody(Byte[] rawBody) 
MsgReader.Mime.MessagePart..ctor(Byte[] rawBody, MessageHeader headers) 
MsgReader.Mime.Message..ctor(Byte[] rawMessageContent, Boolean parseBody) 
MsgReader.Mime.Message..ctor(Byte[] rawMessageContent) `

Thank you.
Gordon

**Comment by swsch** [comment]
I may have found the reason:

According to the comments in Mime/Decode/QuotedPrintable.cs

    #region RemoveIllegalControlCharacters
    /// RFC 2045 states about robustness:<br/>
    /// <code>
    /// Control characters other than TAB, or CR and LF as parts of CRLF pairs,
    /// must not appear. 

If  I save your example file `outlook_2010_html_only.eml` and open it 
it vim, the editor reports "unix" file format, i.e. the line endings
would  only  be  marked  by a lonely LF, which is considered illegal, 
hence gets removed, which in turn makes the following snippet

    ...<link rel=3DFile=
    -List href=3D"cid:filelist.xml@01D08BD8.4D051580">
    
appear to be 

    <link rel=3DFile=-List href=3D"cid:filelist.xml@01D08BD8.4D051580">
    
which would explain the error message.

Is your original .eml file just like this, too?

Curious,
s.

**Comment by Sicos1977** [comment]
Is this still an issue?
